// 镜心 · 东方文人墨客 · 48 题
//
// 分布：12 维 × 4 题 = 48 题
// 每题 6 选项，主测一维，副影响 1-2 维
// delta 范围：主 ±1.5，副 ±0.5

import type { Item } from './item.types';

export const ITEMS_EAST_LITERATI: readonly Item[] = [
  // ── T1 思辨 ── 4 题
  {
    id: 'el-001',
    format: 'situational',
    prompt: '夜读有疑，不得其解',
    promptGloss: '深夜读书，遇到难解之处，你会怎么做？',
    options: [
      {
        text: '搁书而眠',
        gloss: '不急于求通，顺其自然',
        primary: { traitId: 1, delta: -1.2 },
        secondary: [{ traitId: 9, delta: -0.3 }],
      },
      {
        text: '退而求其次',
        gloss: '先记下要点，日后再解',
        primary: { traitId: 1, delta: -0.6 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
      {
        text: '反复诵读',
        gloss: '书读百遍，其义自见',
        primary: { traitId: 1, delta: 0.0 },
        secondary: [{ traitId: 8, delta: 0.3 }],
      },
      {
        text: '广引旁证',
        gloss: '参考其他书籍资料',
        primary: { traitId: 1, delta: 0.6 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
      {
        text: '穷其本末',
        gloss: '追问到底，不弄懂不罢休',
        primary: { traitId: 1, delta: 1.2 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '叩问师友',
        gloss: '向他人请教讨论',
        primary: { traitId: 1, delta: 0.3 },
        secondary: [{ traitId: 5, delta: 0.4 }],
      },
    ],
  },
  {
    id: 'el-002',
    format: 'imagery',
    prompt: '观山与观水',
    promptGloss: '登山和临水，你更喜欢哪一种？',
    options: [
      {
        text: '山',
        gloss: '稳重可靠，可以依靠',
        primary: { traitId: 1, delta: 0.5 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '水',
        gloss: '流动变化，灵活自如',
        primary: { traitId: 1, delta: -0.4 },
        secondary: [{ traitId: 11, delta: 0.3 }],
      },
      {
        text: '云山',
        gloss: '云雾缭绕的高山，超越形相',
        primary: { traitId: 1, delta: 1.3 },
        secondary: [{ traitId: 6, delta: 0.4 }],
      },
      {
        text: '溪涧',
        gloss: '山间小溪，道理就在日常',
        primary: { traitId: 1, delta: -0.9 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '海',
        gloss: '深邃广阔，难以测度',
        primary: { traitId: 1, delta: 1.0 },
        secondary: [{ traitId: 10, delta: 0.3 }],
      },
      {
        text: '丘',
        gloss: '不高不低，平凡普通',
        primary: { traitId: 1, delta: -0.2 },
      },
    ],
  },
  {
    id: 'el-003',
    format: 'aesthetic',
    prompt: '「道可道，非常道」',
    promptGloss: '对这句话，你最深的感触是什么？',
    options: [
      {
        text: '言之不尽',
        gloss: '语言无法完全表达真理',
        primary: { traitId: 1, delta: 1.2 },
        secondary: [{ traitId: 12, delta: -0.3 }],
      },
      {
        text: '知其然即可',
        gloss: '不必深究，明白表面就好',
        primary: { traitId: 1, delta: -1.0 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '可道者非道',
        gloss: '能说出来的都不是真正的道',
        primary: { traitId: 1, delta: 1.3 },
        secondary: [{ traitId: 6, delta: 0.3 }],
      },
      {
        text: '常道亦道',
        gloss: '日常道理也是道，不必玄远',
        primary: { traitId: 1, delta: 0.2 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '此玄谈耳',
        gloss: '这是空谈，不切实际',
        primary: { traitId: 1, delta: -1.3 },
        secondary: [{ traitId: 11, delta: -0.2 }],
      },
      {
        text: '言之即是',
        gloss: '说出来的就是道，言即是道',
        primary: { traitId: 1, delta: -0.6 },
        secondary: [{ traitId: 12, delta: 0.3 }],
      },
    ],
  },
  {
    id: 'el-004',
    format: 'ranking',
    prompt: '四事，汝心中最重者',
    promptGloss: '「理、情、势、术」── 你最看重哪一个？',
    options: [
      {
        text: '理',
        gloss: '以理为尊，道理最大',
        primary: { traitId: 1, delta: 1.4 },
        secondary: [{ traitId: 8, delta: 0.3 }],
      },
      {
        text: '情',
        gloss: '以情为真，真情实感',
        primary: { traitId: 1, delta: -0.4 },
        secondary: [{ traitId: 2, delta: 0.5 }],
      },
      {
        text: '势',
        gloss: '以势为用，顺势而为',
        primary: { traitId: 1, delta: -0.8 },
        secondary: [{ traitId: 3, delta: 0.4 }],
      },
      {
        text: '术',
        gloss: '以术为巧，方法技巧',
        primary: { traitId: 1, delta: -1.0 },
        secondary: [{ traitId: 11, delta: 0.3 }],
      },
      {
        text: '皆重',
        gloss: '四者都重要，不可偏废',
        primary: { traitId: 1, delta: 0.2 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '皆轻',
        gloss: '随事而行，不执一端',
        primary: { traitId: 1, delta: -0.5 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
    ],
  },

  // ── T2 情感 ── 4 题
  {
    id: 'el-005',
    format: 'situational',
    prompt: '挚友远行',
    promptGloss: '最好的朋友要远行千里，你会怎么做？',
    options: [
      {
        text: '临别无语',
        gloss: '默默相送，尽在不言中',
        primary: { traitId: 2, delta: -1.2 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '赋诗一首',
        gloss: '写一首诗送别',
        primary: { traitId: 2, delta: 0.8 },
        secondary: [{ traitId: 12, delta: 0.4 }],
      },
      {
        text: '挥泪相送',
        gloss: '真情流露，不掩饰悲伤',
        primary: { traitId: 2, delta: 1.4 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
      {
        text: '赠一薄物',
        gloss: '送一件小礼物寄托心意',
        primary: { traitId: 2, delta: 0.2 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '托人问候',
        gloss: '不亲自送，但会常联系',
        primary: { traitId: 2, delta: -0.6 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '与之同歌',
        gloss: '一起唱歌，以歌壮行',
        primary: { traitId: 2, delta: 1.2 },
        secondary: [{ traitId: 6, delta: 0.3 }],
      },
    ],
  },
  {
    id: 'el-006',
    format: 'imagery',
    prompt: '春与秋',
    promptGloss: '春天和秋天，你更喜欢哪个季节？',
    options: [
      {
        text: '春',
        gloss: '喜欢万物复苏、生机勃勃',
        primary: { traitId: 2, delta: 1.2 },
        secondary: [{ traitId: 6, delta: 0.3 }],
      },
      {
        text: '秋',
        gloss: '喜欢秋高气爽、沉静安宁',
        primary: { traitId: 2, delta: -0.6 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
      {
        text: '皆爱',
        gloss: '四季都有美好，顺其自然',
        primary: { traitId: 2, delta: 0.0 },
        secondary: [{ traitId: 9, delta: 0.2 }],
      },
      {
        text: '皆不爱',
        gloss: '不为季节所动，自有心境',
        primary: { traitId: 2, delta: -1.0 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '夏',
        gloss: '喜欢热烈奔放、活力四射',
        primary: { traitId: 2, delta: 0.8 },
        secondary: [{ traitId: 3, delta: 0.3 }],
      },
      {
        text: '冬',
        gloss: '喜欢冬日静穆、深沉内敛',
        primary: { traitId: 2, delta: -0.8 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-007',
    format: 'aesthetic',
    prompt: '「悲莫悲兮生别离」',
    promptGloss: '对这句话，你最深的感触是什么？',
    options: [
      {
        text: '悲',
        gloss: '离别是人生最大的悲伤',
        primary: { traitId: 2, delta: 1.4 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
      {
        text: '别',
        gloss: '离别是人生的常态',
        primary: { traitId: 2, delta: 0.6 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '生',
        gloss: '活着本身就可贵，不必太悲伤',
        primary: { traitId: 2, delta: -0.4 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
      {
        text: '此情之常',
        gloss: '离别是常事，不必过于悲伤',
        primary: { traitId: 2, delta: -1.2 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '此情之痛',
        gloss: '这种痛楚刻骨铭心',
        primary: { traitId: 2, delta: 1.0 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
      {
        text: '无言',
        gloss: '悲伤到深处，反而无言',
        primary: { traitId: 2, delta: -0.6 },
        secondary: [{ traitId: 12, delta: -0.2 }],
      },
    ],
  },
  {
    id: 'el-008',
    format: 'situational',
    prompt: '闻人死讯',
    promptGloss: '听说一个认识的人去世了，你会怎么做？',
    options: [
      {
        text: '恸哭一场',
        gloss: '放声大哭，以哭寄托哀思',
        primary: { traitId: 2, delta: 1.4 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
      {
        text: '静坐默哀',
        gloss: '安静坐着，默默悼念',
        primary: { traitId: 2, delta: -0.6 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '作一文以祭',
        gloss: '写一篇文章纪念他',
        primary: { traitId: 2, delta: 0.4 },
        secondary: [{ traitId: 12, delta: 0.4 }],
      },
      {
        text: '为身后事奔走',
        gloss: '帮忙处理后事，以实际行动悼念',
        primary: { traitId: 2, delta: -1.0 },
        secondary: [{ traitId: 3, delta: 0.4 }],
      },
      {
        text: '不以为意',
        gloss: '以理性看待生死，不过分悲伤',
        primary: { traitId: 2, delta: -1.3 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '托人致唁',
        gloss: '托人带去唁电，表达哀思',
        primary: { traitId: 2, delta: -0.2 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
    ],
  },

  // ── T3 行动 ── 4 题
  {
    id: 'el-009',
    format: 'situational',
    prompt: '事有可为',
    promptGloss: '看到一件事值得去做，你会怎么做？',
    options: [
      {
        text: '即刻行之',
        gloss: '说干就干，雷厉风行',
        primary: { traitId: 3, delta: 1.4 },
        secondary: [{ traitId: 11, delta: 0.3 }],
      },
      {
        text: '审而后动',
        gloss: '三思而后行，谨慎行事',
        primary: { traitId: 3, delta: -0.8 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '与人共议',
        gloss: '和大家商量，集思广益',
        primary: { traitId: 3, delta: 0.4 },
        secondary: [{ traitId: 5, delta: 0.4 }],
      },
      {
        text: '先观其势',
        gloss: '观察形势，等待时机',
        primary: { traitId: 3, delta: -1.0 },
        secondary: [{ traitId: 11, delta: -0.3 }],
      },
      {
        text: '躬自任之',
        gloss: '亲自承担，责无旁贷',
        primary: { traitId: 3, delta: 1.0 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '不为之',
        gloss: '这不是我该做的事',
        primary: { traitId: 3, delta: -1.4 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
    ],
  },
  {
    id: 'el-010',
    format: 'imagery',
    prompt: '剑与箫',
    promptGloss: '剑和箫，你更喜欢哪种器物？',
    options: [
      {
        text: '剑',
        gloss: '锋利果决，行动力强',
        primary: { traitId: 3, delta: 1.2 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '箫',
        gloss: '声音悠扬，内敛深沉',
        primary: { traitId: 3, delta: -1.0 },
        secondary: [{ traitId: 6, delta: 0.4 }],
      },
      {
        text: '笔',
        gloss: '以文字表达，思想为器',
        primary: { traitId: 3, delta: 0.0 },
        secondary: [{ traitId: 12, delta: 0.4 }],
      },
      {
        text: '琴',
        gloss: '和谐中正，以和为贵',
        primary: { traitId: 3, delta: -0.6 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '弓',
        gloss: '目标明确，精准有力',
        primary: { traitId: 3, delta: 1.0 },
        secondary: [{ traitId: 11, delta: 0.3 }],
      },
      {
        text: '皆不取',
        gloss: '不以器物为意，以无为用',
        primary: { traitId: 3, delta: -1.3 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-011',
    format: 'aesthetic',
    prompt: '「知而行之」',
    promptGloss: '知道了却不去做，你觉得对吗？',
    options: [
      {
        text: '知必行',
        gloss: '知道了就必须去做',
        primary: { traitId: 3, delta: 1.4 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '知难行',
        gloss: '知道容易，做到难',
        primary: { traitId: 3, delta: -0.6 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '行先于知',
        gloss: '先做起来，边做边学',
        primary: { traitId: 3, delta: 0.6 },
        secondary: [{ traitId: 11, delta: 0.2 }],
      },
      {
        text: '知不必然行',
        gloss: '知道是一回事，做是另一回事',
        primary: { traitId: 3, delta: -1.2 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '知行合一',
        gloss: '知和行是一体的',
        primary: { traitId: 3, delta: 0.2 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
      {
        text: '行难知更难',
        gloss: '行动难，真知更难',
        primary: { traitId: 3, delta: -0.8 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-012',
    format: 'situational',
    prompt: '民有疾苦',
    promptGloss: '听说民间有疾苦，你会怎么做？',
    options: [
      {
        text: '上书直陈',
        gloss: '向上级反映情况',
        primary: { traitId: 3, delta: 0.4 },
        secondary: [{ traitId: 4, delta: 0.3 }],
      },
      {
        text: '躬身救助',
        gloss: '亲自去帮助救济',
        primary: { traitId: 3, delta: 1.3 },
        secondary: [{ traitId: 2, delta: 0.3 }],
      },
      {
        text: '聚众议事',
        gloss: '组织大家一起商量解决',
        primary: { traitId: 3, delta: 0.6 },
        secondary: [{ traitId: 5, delta: 0.4 }],
      },
      {
        text: '默而记之',
        gloss: '记在心里，留待日后',
        primary: { traitId: 3, delta: -1.0 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
      {
        text: '托友代办',
        gloss: '委托朋友代为处理',
        primary: { traitId: 3, delta: -0.4 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '不以为意',
        gloss: '这不是我能管的',
        primary: { traitId: 3, delta: -1.4 },
        secondary: [{ traitId: 9, delta: -0.3 }],
      },
    ],
  },

  // ── T4 革新 ── 4 题
  {
    id: 'el-013',
    format: 'situational',
    prompt: '古制已坏',
    promptGloss: '看到旧制度已经坏了，你会怎么做？',
    options: [
      {
        text: '复其旧制',
        gloss: '恢复老规矩，以复古为新',
        primary: { traitId: 4, delta: -1.4 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
      {
        text: '修其残缺',
        gloss: '修补完善，小步改进',
        primary: { traitId: 4, delta: -0.6 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '因时损益',
        gloss: '根据时代调整，该减的减，该增的增',
        primary: { traitId: 4, delta: 0.0 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '另立新制',
        gloss: '建立新制度，破旧立新',
        primary: { traitId: 4, delta: 1.2 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '悉数推倒',
        gloss: '全部推翻，彻底革命',
        primary: { traitId: 4, delta: 1.4 },
        secondary: [{ traitId: 11, delta: 0.3 }],
      },
      {
        text: '不置可否',
        gloss: '不表态，观望再说',
        primary: { traitId: 4, delta: -0.8 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
    ],
  },
  {
    id: 'el-014',
    format: 'ranking',
    prompt: '四字，汝最重',
    promptGloss: '「守、变、破、立」── 你最看重哪个字？',
    options: [
      {
        text: '守',
        gloss: '坚守传统，以守为立',
        primary: { traitId: 4, delta: -1.4 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '变',
        gloss: '顺应变化，以变为常',
        primary: { traitId: 4, delta: 0.4 },
        secondary: [{ traitId: 11, delta: 0.2 }],
      },
      {
        text: '破',
        gloss: '打破旧规，以破为快',
        primary: { traitId: 4, delta: 1.2 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '立',
        gloss: '建立新规，以立为功',
        primary: { traitId: 4, delta: 0.8 },
        secondary: [{ traitId: 3, delta: 0.4 }],
      },
      {
        text: '守破之间',
        gloss: '在守和破之间找平衡',
        primary: { traitId: 4, delta: -0.2 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '破立相生',
        gloss: '破就是立，立就是破',
        primary: { traitId: 4, delta: 1.4 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
    ],
  },
  {
    id: 'el-015',
    format: 'aesthetic',
    prompt: '「天变不足畏」',
    promptGloss: '对这句话，你最深的感触是什么？',
    options: [
      {
        text: '敢',
        gloss: '敢于变革，无所畏惧',
        primary: { traitId: 4, delta: 1.4 },
        secondary: [{ traitId: 11, delta: 0.3 }],
      },
      {
        text: '狂',
        gloss: '有勇气但可能过头',
        primary: { traitId: 4, delta: 0.4 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '慎',
        gloss: '谨慎为上，不轻举妄动',
        primary: { traitId: 4, delta: -1.0 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '信',
        gloss: '有信心，有信念',
        primary: { traitId: 4, delta: -0.6 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '智',
        gloss: '用智慧去变革',
        primary: { traitId: 4, delta: 0.6 },
        secondary: [{ traitId: 1, delta: 0.4 }],
      },
      {
        text: '仁',
        gloss: '以仁爱为本，不伤害他人',
        primary: { traitId: 4, delta: -1.4 },
        secondary: [{ traitId: 2, delta: 0.3 }],
      },
    ],
  },
  {
    id: 'el-016',
    format: 'imagery',
    prompt: '种子与根',
    promptGloss: '种子和根，你更喜欢哪一个？',
    options: [
      {
        text: '种子',
        gloss: '新的开始，充满可能',
        primary: { traitId: 4, delta: 1.2 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
      {
        text: '根',
        gloss: '扎根本土，传统深厚',
        primary: { traitId: 4, delta: -1.0 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
      {
        text: '苗',
        gloss: '正在生长，充满生机',
        primary: { traitId: 4, delta: 0.4 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '花',
        gloss: '绽放美丽，展现价值',
        primary: { traitId: 4, delta: 0.0 },
        secondary: [{ traitId: 6, delta: 0.3 }],
      },
      {
        text: '果',
        gloss: '结出果实，有所成就',
        primary: { traitId: 4, delta: -0.4 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
      {
        text: '土',
        gloss: '厚德载物，滋养一切',
        primary: { traitId: 4, delta: -1.2 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
    ],
  },

  // ── T5 群我 ── 4 题
  {
    id: 'el-017',
    format: 'situational',
    prompt: '群议有违',
    promptGloss: '大家的意见和你不同，你会怎么做？',
    options: [
      {
        text: '从众',
        gloss: '少数服从多数，以和为贵',
        primary: { traitId: 5, delta: 1.0 },
        secondary: [{ traitId: 7, delta: -0.4 }],
      },
      {
        text: '直言己见',
        gloss: '坚持自己的看法，直接表达',
        primary: { traitId: 5, delta: -1.0 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '折中调和',
        gloss: '找中间方案，兼顾各方',
        primary: { traitId: 5, delta: 0.4 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '退而不争',
        gloss: '退出争论，不浪费时间',
        primary: { traitId: 5, delta: 0.8 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '引经据典',
        gloss: '用道理和证据说服人',
        primary: { traitId: 5, delta: -0.4 },
        secondary: [{ traitId: 1, delta: 0.4 }],
      },
      {
        text: '议而不决',
        gloss: '讨论但不做决定，留待日后',
        primary: { traitId: 5, delta: 0.0 },
        secondary: [{ traitId: 11, delta: -0.2 }],
      },
    ],
  },
  {
    id: 'el-018',
    format: 'ranking',
    prompt: '四者之先',
    promptGloss: '「己、家、国、天下」── 你最看重哪个？',
    options: [
      {
        text: '己',
        gloss: '先顾好自己',
        primary: { traitId: 5, delta: -1.4 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '家',
        gloss: '家庭为重',
        primary: { traitId: 5, delta: -0.6 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '国',
        gloss: '国家为先',
        primary: { traitId: 5, delta: 0.4 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '天下',
        gloss: '以天下为己任',
        primary: { traitId: 5, delta: 1.4 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
      {
        text: '己家并重',
        gloss: '自己和家庭都重要',
        primary: { traitId: 5, delta: -0.8 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '国天同重',
        gloss: '国家和天下并重',
        primary: { traitId: 5, delta: 1.0 },
        secondary: [{ traitId: 4, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-019',
    format: 'aesthetic',
    prompt: '「独善其身」',
    promptGloss: '对这句话，你最深的感触是什么？',
    options: [
      {
        text: '善',
        gloss: '以向善为志向',
        primary: { traitId: 5, delta: -0.4 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '独',
        gloss: '喜欢独处，以独为高',
        primary: { traitId: 5, delta: -1.2 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '身',
        gloss: '看重自身修养',
        primary: { traitId: 5, delta: -0.8 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
      {
        text: '兼善',
        gloss: '善及于众，兼济天下',
        primary: { traitId: 5, delta: 1.4 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '先独后兼',
        gloss: '先完善自己，再帮助他人',
        primary: { traitId: 5, delta: 0.2 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '先兼后独',
        gloss: '先帮助他人，再完善自己',
        primary: { traitId: 5, delta: 0.8 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-020',
    format: 'imagery',
    prompt: '孤峰与众山',
    promptGloss: '孤峰和众山，你更倾向哪个？',
    options: [
      {
        text: '孤峰',
        gloss: '独立特行，以独立为美',
        primary: { traitId: 5, delta: -1.2 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '众山',
        gloss: '连绵起伏，以群体为美',
        primary: { traitId: 5, delta: 1.0 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '远山',
        gloss: '遥相呼应，以相望为美',
        primary: { traitId: 5, delta: 0.2 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
      {
        text: '丘壑',
        gloss: '高低错落，以差异为美',
        primary: { traitId: 5, delta: 0.4 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
      {
        text: '平川',
        gloss: '开阔平坦，以开阔为美',
        primary: { traitId: 5, delta: 0.6 },
        secondary: [{ traitId: 9, delta: 0.2 }],
      },
      {
        text: '天际',
        gloss: '无边无际，以无我为美',
        primary: { traitId: 5, delta: -0.4 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
    ],
  },

  // ── T6 审美 ── 4 题
  {
    id: 'el-021',
    format: 'imagery',
    prompt: '工笔与写意',
    promptGloss: '工笔画的细腻和写意画的放达，你更喜欢哪种？',
    options: [
      {
        text: '工笔',
        gloss: '精细入微，一丝不苟',
        primary: { traitId: 6, delta: -1.0 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
      {
        text: '写意',
        gloss: '意在笔先，挥洒自如',
        primary: { traitId: 6, delta: 1.4 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
      {
        text: '兼工',
        gloss: '工意结合，细腻又洒脱',
        primary: { traitId: 6, delta: 0.0 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '白描',
        gloss: '朴素简洁，不加修饰',
        primary: { traitId: 6, delta: -0.6 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '泼墨',
        gloss: '大胆挥洒，气势磅礴',
        primary: { traitId: 6, delta: 1.0 },
        secondary: [{ traitId: 4, delta: 0.3 }],
      },
      {
        text: '设色',
        gloss: '色彩丰富，华丽美观',
        primary: { traitId: 6, delta: 0.4 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-022',
    format: 'aesthetic',
    prompt: '「大音希声」',
    promptGloss: '对这句话，你最深的感触是什么？',
    options: [
      {
        text: '希',
        gloss: '稀有的才是最珍贵的',
        primary: { traitId: 6, delta: 1.4 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
      {
        text: '大',
        gloss: '宏大深远，境界开阔',
        primary: { traitId: 6, delta: 0.6 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
      {
        text: '声',
        gloss: '有声之美，直观可感',
        primary: { traitId: 6, delta: -0.8 },
        secondary: [{ traitId: 12, delta: 0.2 }],
      },
      {
        text: '无',
        gloss: '无声胜有声，以无为美',
        primary: { traitId: 6, delta: 1.2 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '有',
        gloss: '有形有象，具体可感',
        primary: { traitId: 6, delta: -1.2 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '中和',
        gloss: '中庸和谐，不偏不倚',
        primary: { traitId: 6, delta: -0.2 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-023',
    format: 'ranking',
    prompt: '四韵，汝最倾',
    promptGloss: '「清、丽、雅、雄」── 你最倾向哪种风格？',
    options: [
      {
        text: '清',
        gloss: '清新脱俗，清雅高洁',
        primary: { traitId: 6, delta: 1.0 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '丽',
        gloss: '华丽优美，光彩照人',
        primary: { traitId: 6, delta: 0.4 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '雅',
        gloss: '典雅端庄，温文尔雅',
        primary: { traitId: 6, delta: 0.8 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
      {
        text: '雄',
        gloss: '雄浑壮阔，气势恢宏',
        primary: { traitId: 6, delta: -0.4 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '皆可',
        gloss: '各种风格都可以欣赏',
        primary: { traitId: 6, delta: -0.8 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '皆不可',
        gloss: '超越风格，以无韵为韵',
        primary: { traitId: 6, delta: -1.2 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-024',
    format: 'imagery',
    prompt: '梅与牡丹',
    promptGloss: '梅花和牡丹，你更喜欢哪种花？',
    options: [
      {
        text: '梅',
        gloss: '傲雪凌霜，以瘦为美',
        primary: { traitId: 6, delta: 1.0 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '牡丹',
        gloss: '富贵华丽，以盛为美',
        primary: { traitId: 6, delta: -0.6 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '兰',
        gloss: '幽谷清香，以幽为美',
        primary: { traitId: 6, delta: 1.2 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '菊',
        gloss: '淡泊隐逸，以淡为美',
        primary: { traitId: 6, delta: 0.8 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '荷',
        gloss: '出淤泥不染，以洁为美',
        primary: { traitId: 6, delta: 0.6 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '皆爱',
        gloss: '四季有花，随时欣赏',
        primary: { traitId: 6, delta: -0.8 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
    ],
  },

  // ── T7 意志 ── 4 题
  {
    id: 'el-025',
    format: 'situational',
    prompt: '困于逆境',
    promptGloss: '身处逆境，你会怎么做？',
    options: [
      {
        text: '刚强不屈',
        gloss: '咬牙坚持，绝不屈服',
        primary: { traitId: 7, delta: 1.4 },
        secondary: [{ traitId: 3, delta: 0.3 }],
      },
      {
        text: '顺其自然',
        gloss: '顺应形势，以柔克刚',
        primary: { traitId: 7, delta: -1.0 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '隐忍以图',
        gloss: '暂时忍耐，等待时机',
        primary: { traitId: 7, delta: -0.4 },
        secondary: [{ traitId: 11, delta: -0.3 }],
      },
      {
        text: '以死抗争',
        gloss: '宁死不屈，以死明志',
        primary: { traitId: 7, delta: 1.2 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '远走避祸',
        gloss: '远离是非，保全自身',
        primary: { traitId: 7, delta: -1.2 },
        secondary: [{ traitId: 9, delta: -0.3 }],
      },
      {
        text: '与人共济',
        gloss: '团结他人，共同面对',
        primary: { traitId: 7, delta: 0.4 },
        secondary: [{ traitId: 5, delta: 0.4 }],
      },
    ],
  },
  {
    id: 'el-026',
    format: 'aesthetic',
    prompt: '「宁折不弯」',
    promptGloss: '对这句话，你最深的感触是什么？',
    options: [
      {
        text: '折',
        gloss: '宁折不弯，以正直为贵',
        primary: { traitId: 7, delta: 1.4 },
        secondary: [{ traitId: 4, delta: 0.2 }],
      },
      {
        text: '弯',
        gloss: '能屈能伸，以灵活为智',
        primary: { traitId: 7, delta: -1.4 },
        secondary: [{ traitId: 11, delta: 0.2 }],
      },
      {
        text: '折弯相宜',
        gloss: '该折则折，该弯则弯',
        primary: { traitId: 7, delta: 0.0 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '不折不弯',
        gloss: '保持中道，不偏不倚',
        primary: { traitId: 7, delta: -0.4 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '宁弯亦存',
        gloss: '活着最重要，留得青山在',
        primary: { traitId: 7, delta: -1.0 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
      {
        text: '宁折不存',
        gloss: '义之所在，虽死不辞',
        primary: { traitId: 7, delta: 1.2 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-027',
    format: 'imagery',
    prompt: '石与水',
    promptGloss: '石头和水，你更欣赏哪个？',
    options: [
      {
        text: '石',
        gloss: '坚定不移，以坚为德',
        primary: { traitId: 7, delta: 1.2 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '水',
        gloss: '柔韧变通，以柔为德',
        primary: { traitId: 7, delta: -1.2 },
        secondary: [{ traitId: 11, delta: 0.2 }],
      },
      {
        text: '山',
        gloss: '沉稳厚重，以重为德',
        primary: { traitId: 7, delta: 0.8 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '风',
        gloss: '自由流动，以动为德',
        primary: { traitId: 7, delta: 0.2 },
        secondary: [{ traitId: 4, delta: 0.2 }],
      },
      {
        text: '云',
        gloss: '飘逸洒脱，以散为德',
        primary: { traitId: 7, delta: -0.6 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
      {
        text: '土',
        gloss: '厚德载物，以厚为德',
        primary: { traitId: 7, delta: 0.4 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-028',
    format: 'situational',
    prompt: '有辱加身',
    promptGloss: '受到侮辱，你会怎么做？',
    options: [
      {
        text: '拔剑而起',
        gloss: '立即反击，以牙还牙',
        primary: { traitId: 7, delta: 1.4 },
        secondary: [{ traitId: 3, delta: 0.3 }],
      },
      {
        text: '忍而不发',
        gloss: '强忍怒气，暂不发作',
        primary: { traitId: 7, delta: -0.6 },
        secondary: [{ traitId: 11, delta: -0.2 }],
      },
      {
        text: '一笑置之',
        gloss: '淡然处之，不放在心上',
        primary: { traitId: 7, delta: -1.0 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '事后以功明',
        gloss: '用成就证明自己',
        primary: { traitId: 7, delta: 0.4 },
        secondary: [{ traitId: 10, delta: 0.3 }],
      },
      {
        text: '托人辩白',
        gloss: '请人帮忙解释澄清',
        primary: { traitId: 7, delta: -0.4 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '自省其过',
        gloss: '反省自己是否有错',
        primary: { traitId: 7, delta: -0.8 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
    ],
  },

  // ── T8 学识 ── 4 题
  {
    id: 'el-029',
    format: 'ranking',
    prompt: '四部，汝最重',
    promptGloss: '「经、史、子、集」── 你最看重哪一类？',
    options: [
      {
        text: '经',
        gloss: '经典根本，以经为尊',
        primary: { traitId: 8, delta: 0.6 },
        secondary: [{ traitId: 4, delta: -0.2 }],
      },
      {
        text: '史',
        gloss: '历史借鉴，以史为鉴',
        primary: { traitId: 8, delta: 0.2 },
        secondary: [{ traitId: 10, delta: 0.4 }],
      },
      {
        text: '子',
        gloss: '思想智慧，以子为思',
        primary: { traitId: 8, delta: 0.8 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
      {
        text: '集',
        gloss: '文学情感，以集为情',
        primary: { traitId: 8, delta: -0.6 },
        secondary: [{ traitId: 2, delta: 0.4 }],
      },
      {
        text: '皆读',
        gloss: '博览群书，以博为学',
        primary: { traitId: 8, delta: -1.0 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '专一',
        gloss: '精通一门，以专为学',
        primary: { traitId: 8, delta: 1.0 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-030',
    format: 'situational',
    prompt: '学有未通',
    promptGloss: '学问有不通处，你会怎么做？',
    options: [
      {
        text: '穷研十年',
        gloss: '深入钻研，不弄通不罢休',
        primary: { traitId: 8, delta: 1.4 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '广取他学',
        gloss: '广泛涉猎，触类旁通',
        primary: { traitId: 8, delta: -1.0 },
        secondary: [{ traitId: 4, delta: 0.2 }],
      },
      {
        text: '转习他业',
        gloss: '换个方向，另辟蹊径',
        primary: { traitId: 8, delta: -0.6 },
        secondary: [{ traitId: 11, delta: 0.2 }],
      },
      {
        text: '问于师友',
        gloss: '请教他人，集思广益',
        primary: { traitId: 8, delta: -0.2 },
        secondary: [{ traitId: 5, delta: 0.3 }],
      },
      {
        text: '先记其要',
        gloss: '记下要点，日后再解',
        primary: { traitId: 8, delta: 0.4 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '付诸实用',
        gloss: '用到实践中去验证',
        primary: { traitId: 8, delta: -1.2 },
        secondary: [{ traitId: 3, delta: 0.3 }],
      },
    ],
  },
  {
    id: 'el-031',
    format: 'aesthetic',
    prompt: '「吾生也有涯，而知也无涯」',
    promptGloss: '对这句话，你最深的感触是什么？',
    options: [
      {
        text: '有涯',
        gloss: '生命有限，要珍惜时光',
        primary: { traitId: 8, delta: -0.6 },
        secondary: [{ traitId: 10, delta: 0.3 }],
      },
      {
        text: '无涯',
        gloss: '知识无穷，学无止境',
        primary: { traitId: 8, delta: 1.4 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '以有涯逐无涯',
        gloss: '用有限追求无限，虽苦犹乐',
        primary: { traitId: 8, delta: 0.8 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '殆已',
        gloss: '这样追求很危险，要适可而止',
        primary: { traitId: 8, delta: -1.2 },
        secondary: [{ traitId: 9, delta: -0.3 }],
      },
      {
        text: '知止',
        gloss: '知道适可而止，是智慧',
        primary: { traitId: 8, delta: -0.8 },
        secondary: [{ traitId: 11, delta: -0.2 }],
      },
      {
        text: '知足',
        gloss: '知足常乐，不贪多',
        primary: { traitId: 8, delta: -0.4 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-032',
    format: 'imagery',
    prompt: '江与井',
    promptGloss: '江河和水井，你更倾向哪个？',
    options: [
      {
        text: '江',
        gloss: '江河广阔，以博为学',
        primary: { traitId: 8, delta: -1.2 },
        secondary: [{ traitId: 4, delta: 0.2 }],
      },
      {
        text: '井',
        gloss: '水井深邃，以专为学',
        primary: { traitId: 8, delta: 1.4 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '海',
        gloss: '大海无涯，以广为学',
        primary: { traitId: 8, delta: 0.6 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
      {
        text: '泉',
        gloss: '泉水活源，以活为学',
        primary: { traitId: 8, delta: 0.4 },
        secondary: [{ traitId: 11, delta: 0.2 }],
      },
      {
        text: '溪',
        gloss: '溪流清澈，以清为学',
        primary: { traitId: 8, delta: 0.0 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
      {
        text: '湖',
        gloss: '湖水平静，以静为学',
        primary: { traitId: 8, delta: -0.4 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
    ],
  },

  // ── T9 处世 ── 4 题
  {
    id: 'el-033',
    format: 'situational',
    prompt: '时不予我',
    promptGloss: '时运不济，你会怎么做？',
    options: [
      {
        text: '出而行世',
        gloss: '积极入世，努力改变',
        primary: { traitId: 9, delta: 1.0 },
        secondary: [{ traitId: 3, delta: 0.3 }],
      },
      {
        text: '处而自修',
        gloss: '退而自修，提升自己',
        primary: { traitId: 9, delta: -0.8 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
      {
        text: '隐而不仕',
        gloss: '隐居不仕，保全志节',
        primary: { traitId: 9, delta: -1.4 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '行藏以时',
        gloss: '根据时势决定进退',
        primary: { traitId: 9, delta: 0.2 },
        secondary: [{ traitId: 11, delta: 0.2 }],
      },
      {
        text: '出而复归',
        gloss: '出去试试，不行就回来',
        primary: { traitId: 9, delta: -0.4 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '为而不争',
        gloss: '做事但不争名夺利',
        primary: { traitId: 9, delta: -0.6 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-034',
    format: 'aesthetic',
    prompt: '「穷则独善其身，达则兼善天下」',
    promptGloss: '对这句话，你最深的感触是什么？',
    options: [
      {
        text: '穷',
        gloss: '困顿时也要坚守',
        primary: { traitId: 9, delta: -0.6 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '达',
        gloss: '显达时要兼济天下',
        primary: { traitId: 9, delta: 1.0 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '独善',
        gloss: '独善其身也是一种境界',
        primary: { traitId: 9, delta: -1.2 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '兼善',
        gloss: '兼济天下才是大愿',
        primary: { traitId: 9, delta: 1.4 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '穷达皆善',
        gloss: '无论穷达都要向善',
        primary: { traitId: 9, delta: 0.2 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '穷达皆忘',
        gloss: '超越穷达，无我境界',
        primary: { traitId: 9, delta: -0.8 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-035',
    format: 'imagery',
    prompt: '舟与岸',
    promptGloss: '船和岸，你更喜欢哪个？',
    options: [
      {
        text: '舟',
        gloss: '行船水上，以行为乐',
        primary: { traitId: 9, delta: 1.4 },
        secondary: [{ traitId: 11, delta: 0.2 }],
      },
      {
        text: '岸',
        gloss: '停泊靠岸，以止为安',
        primary: { traitId: 9, delta: -1.2 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '泊',
        gloss: '停泊休息，以泊为度',
        primary: { traitId: 9, delta: -0.2 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '渡',
        gloss: '渡人渡己，以渡为用',
        primary: { traitId: 9, delta: 0.4 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '灯塔',
        gloss: '指引方向，以守为照',
        primary: { traitId: 9, delta: -0.6 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
      {
        text: '云帆',
        gloss: '扬帆远航，以远为志',
        primary: { traitId: 9, delta: 1.0 },
        secondary: [{ traitId: 4, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-036',
    format: 'situational',
    prompt: '友有显达',
    promptGloss: '朋友显达了而自己还没有，你会怎么做？',
    options: [
      {
        text: '贺而不慕',
        gloss: '祝贺但不羡慕',
        primary: { traitId: 9, delta: -0.4 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '慕而求进',
        gloss: '羡慕并努力追赶',
        primary: { traitId: 9, delta: 1.0 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '退而自安',
        gloss: '退一步，安于自己的处境',
        primary: { traitId: 9, delta: -1.0 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '绝之',
        gloss: '断绝来往，眼不见为净',
        primary: { traitId: 9, delta: -1.4 },
        secondary: [{ traitId: 5, delta: -0.2 }],
      },
      {
        text: '随而借势',
        gloss: '跟随并借助朋友的力量',
        primary: { traitId: 9, delta: 0.6 },
        secondary: [{ traitId: 11, delta: 0.2 }],
      },
      {
        text: '不改其常',
        gloss: '保持常态，不因此改变',
        primary: { traitId: 9, delta: -0.2 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
    ],
  },

  // ── T10 时间 ── 4 题
  {
    id: 'el-037',
    format: 'imagery',
    prompt: '朝与暮',
    promptGloss: '清晨和黄昏，你更喜欢哪个时刻？',
    options: [
      {
        text: '朝',
        gloss: '朝气蓬勃，充满希望',
        primary: { traitId: 10, delta: -0.6 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '暮',
        gloss: '暮色苍茫，归于安宁',
        primary: { traitId: 10, delta: 0.8 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '夜',
        gloss: '夜深人静，思想深邃',
        primary: { traitId: 10, delta: 1.2 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '旦',
        gloss: '破晓之初，万象更新',
        primary: { traitId: 10, delta: -1.0 },
        secondary: [{ traitId: 4, delta: 0.2 }],
      },
      {
        text: '午',
        gloss: '日正当中，光明盛大',
        primary: { traitId: 10, delta: -0.4 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '皆爱',
        gloss: '每个时刻都有美好',
        primary: { traitId: 10, delta: 0.0 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-038',
    format: 'situational',
    prompt: '功在千秋',
    promptGloss: '你的作为可以为百世立功，你愿意吗？',
    options: [
      {
        text: '愿',
        gloss: '志在长远，以远为志',
        primary: { traitId: 10, delta: 1.4 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '不愿',
        gloss: '活在当下，以今世为足',
        primary: { traitId: 10, delta: -1.0 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '随缘',
        gloss: '顺其自然，不刻意追求',
        primary: { traitId: 10, delta: 0.4 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '不必',
        gloss: '无为而治，不必留名',
        primary: { traitId: 10, delta: -0.6 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
      {
        text: '为而不居',
        gloss: '做了但不居功',
        primary: { traitId: 10, delta: 0.8 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '传而不朽',
        gloss: '追求不朽，留名后世',
        primary: { traitId: 10, delta: 1.0 },
        secondary: [{ traitId: 12, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-039',
    format: 'aesthetic',
    prompt: '「不朽」',
    promptGloss: '对这两个字，你最深的感触是什么？',
    options: [
      {
        text: '立言',
        gloss: '著书立说，以文字不朽',
        primary: { traitId: 10, delta: 1.2 },
        secondary: [{ traitId: 8, delta: 0.3 }],
      },
      {
        text: '立德',
        gloss: '修身立德，以品德不朽',
        primary: { traitId: 10, delta: 1.0 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '立功',
        gloss: '建功立业，以功绩不朽',
        primary: { traitId: 10, delta: 0.8 },
        secondary: [{ traitId: 3, delta: 0.3 }],
      },
      {
        text: '不必朽',
        gloss: '不求不朽，顺其自然',
        primary: { traitId: 10, delta: -1.0 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '随缘',
        gloss: '朽与不朽，随缘就好',
        primary: { traitId: 10, delta: -0.4 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '立心',
        gloss: '为天地立心，以精神不朽',
        primary: { traitId: 10, delta: 1.4 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
    ],
  },
  {
    id: 'el-040',
    format: 'ranking',
    prompt: '三时，汝最重',
    promptGloss: '「昨日、今日、明日」── 你最看重哪个？',
    options: [
      {
        text: '昨日',
        gloss: '以史为鉴，从前事学习',
        primary: { traitId: 10, delta: 0.4 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
      {
        text: '今日',
        gloss: '把握当下，以现在为要',
        primary: { traitId: 10, delta: -0.8 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '明日',
        gloss: '展望未来，以远为志',
        primary: { traitId: 10, delta: 1.4 },
        secondary: [{ traitId: 4, delta: 0.2 }],
      },
      {
        text: '昨日已往',
        gloss: '过去就过去了，不纠结',
        primary: { traitId: 10, delta: -0.4 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '今日当行',
        gloss: '今天的事今天就做',
        primary: { traitId: 10, delta: -1.0 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '明日当期',
        gloss: '期待明天会更好',
        primary: { traitId: 10, delta: 0.8 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
    ],
  },

  // ── T11 风险 ── 4 题
  {
    id: 'el-041',
    format: 'situational',
    prompt: '机不可失',
    promptGloss: '良机一闪即逝，你会怎么做？',
    options: [
      {
        text: '即下决断',
        gloss: '当机立断，抓住机会',
        primary: { traitId: 11, delta: 1.4 },
        secondary: [{ traitId: 3, delta: 0.3 }],
      },
      {
        text: '退而待之',
        gloss: '稳妥为上，等待更好时机',
        primary: { traitId: 11, delta: -1.2 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '半进半退',
        gloss: '试探性前进，保留退路',
        primary: { traitId: 11, delta: 0.2 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '与人共议',
        gloss: '和大家商量再做决定',
        primary: { traitId: 11, delta: -0.6 },
        secondary: [{ traitId: 5, delta: 0.3 }],
      },
      {
        text: '观其始末',
        gloss: '观察清楚再做决定',
        primary: { traitId: 11, delta: -0.8 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
      {
        text: '舍机取势',
        gloss: '放弃机会，选择更稳妥的路',
        primary: { traitId: 11, delta: 0.6 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
    ],
  },
  {
    id: 'el-042',
    format: 'imagery',
    prompt: '弈与弈',
    promptGloss: '落子无悔，你觉得如何？',
    options: [
      {
        text: '无悔',
        gloss: '果断决策，落子不悔',
        primary: { traitId: 11, delta: 1.2 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '常悔',
        gloss: '谨慎小心，经常后悔',
        primary: { traitId: 11, delta: -1.2 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '慎而落',
        gloss: '深思熟虑后再落子',
        primary: { traitId: 11, delta: -0.6 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '落而慎',
        gloss: '落子后谨慎应对',
        primary: { traitId: 11, delta: -0.4 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '随棋',
        gloss: '顺其自然，随遇而安',
        primary: { traitId: 11, delta: 0.4 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '不落',
        gloss: '不下最好，避免错误',
        primary: { traitId: 11, delta: -0.8 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-043',
    format: 'aesthetic',
    prompt: '「不入虎穴，焉得虎子」',
    promptGloss: '对这句话，你最深的感触是什么？',
    options: [
      {
        text: '虎穴',
        gloss: '敢于冒险，以险为功',
        primary: { traitId: 11, delta: 1.4 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '虎子',
        gloss: '目标明确，以得为愿',
        primary: { traitId: 11, delta: 0.6 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '不入',
        gloss: '安全第一，以不入为智',
        primary: { traitId: 11, delta: -1.4 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '入而不执',
        gloss: '进入但不执着，随缘而得',
        primary: { traitId: 11, delta: 0.0 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
      {
        text: '入而有备',
        gloss: '做好准备再进入',
        primary: { traitId: 11, delta: -0.6 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '不入亦得',
        gloss: '不冒险也能成功',
        primary: { traitId: 11, delta: -0.8 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-044',
    format: 'situational',
    prompt: '国难临头',
    promptGloss: '国家有难，你会怎么做？',
    options: [
      {
        text: '赴难如归',
        gloss: '挺身而出，以身殉国',
        primary: { traitId: 11, delta: 1.4 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '避地远祸',
        gloss: '远离危险，保全自身',
        primary: { traitId: 11, delta: -1.4 },
        secondary: [{ traitId: 9, delta: -0.3 }],
      },
      {
        text: '隐于山林',
        gloss: '隐居避世，保全志节',
        primary: { traitId: 11, delta: -0.8 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '从众以避',
        gloss: '跟随大家，共同应对',
        primary: { traitId: 11, delta: -0.4 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '暗中图复',
        gloss: '暗中谋划，伺机而动',
        primary: { traitId: 11, delta: 0.4 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
      {
        text: '待时而起',
        gloss: '等待时机，再起而为',
        primary: { traitId: 11, delta: 0.6 },
        secondary: [{ traitId: 10, delta: 0.2 }],
      },
    ],
  },

  // ── T12 表达 ── 4 题
  {
    id: 'el-045',
    format: 'imagery',
    prompt: '白与文',
    promptGloss: '白话和文言，你更倾向哪种？',
    options: [
      {
        text: '白话',
        gloss: '通俗易懂，直白真实',
        primary: { traitId: 12, delta: -1.4 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '文言',
        gloss: '典雅精炼，韵味悠长',
        primary: { traitId: 12, delta: 1.4 },
        secondary: [{ traitId: 8, delta: 0.3 }],
      },
      {
        text: '半文半白',
        gloss: '文白相间，雅俗共赏',
        primary: { traitId: 12, delta: 0.0 },
        secondary: [{ traitId: 5, delta: 0.2 }],
      },
      {
        text: '口语',
        gloss: '生活化，亲切自然',
        primary: { traitId: 12, delta: -1.0 },
        secondary: [{ traitId: 2, delta: 0.2 }],
      },
      {
        text: '诗语',
        gloss: '诗意盎然，意境优美',
        primary: { traitId: 12, delta: 1.0 },
        secondary: [{ traitId: 6, delta: 0.3 }],
      },
      {
        text: '皆不可',
        gloss: '超越语言，以心传心',
        primary: { traitId: 12, delta: -0.6 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-046',
    format: 'situational',
    prompt: '欲言又止',
    promptGloss: '有话想说又说不尽，你会怎么做？',
    options: [
      {
        text: '书以代之',
        gloss: '写下来，用文字表达',
        primary: { traitId: 12, delta: 0.6 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
      {
        text: '歌以咏之',
        gloss: '唱出来，用歌声传达',
        primary: { traitId: 12, delta: 1.2 },
        secondary: [{ traitId: 6, delta: 0.3 }],
      },
      {
        text: '画以形之',
        gloss: '画出来，用图像呈现',
        primary: { traitId: 12, delta: 1.0 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
      {
        text: '默而化之',
        gloss: '不说，用行动感化',
        primary: { traitId: 12, delta: -0.8 },
        secondary: [{ traitId: 3, delta: 0.2 }],
      },
      {
        text: '直陈其意',
        gloss: '直接说明白',
        primary: { traitId: 12, delta: -1.2 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '托物以喻',
        gloss: '借物比喻，含蓄表达',
        primary: { traitId: 12, delta: 0.4 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
    ],
  },
  {
    id: 'el-047',
    format: 'aesthetic',
    prompt: '「言有尽而意无穷」',
    promptGloss: '对这句话，你最深的感触是什么？',
    options: [
      {
        text: '言有尽',
        gloss: '语言有限，表达有边界',
        primary: { traitId: 12, delta: -0.6 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '意无穷',
        gloss: '意境深远，余韵悠长',
        primary: { traitId: 12, delta: 1.0 },
        secondary: [{ traitId: 6, delta: 0.3 }],
      },
      {
        text: '言意相生',
        gloss: '言和意相互生发',
        primary: { traitId: 12, delta: 0.6 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '不言而意',
        gloss: '不说话也能传达意思',
        primary: { traitId: 12, delta: -0.2 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '言之凿凿',
        gloss: '说话要有根据，实实在在',
        primary: { traitId: 12, delta: -1.0 },
        secondary: [{ traitId: 7, delta: 0.2 }],
      },
      {
        text: '意在言先',
        gloss: '意思在语言之前，意在言外',
        primary: { traitId: 12, delta: 1.2 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
    ],
  },
  {
    id: 'el-048',
    format: 'ranking',
    prompt: '四体，汝最擅',
    promptGloss: '「诗、词、文、赋」── 你最擅长哪种？',
    options: [
      {
        text: '诗',
        gloss: '诗歌凝练，意境深远',
        primary: { traitId: 12, delta: 0.4 },
        secondary: [{ traitId: 6, delta: 0.2 }],
      },
      {
        text: '词',
        gloss: '词牌婉约，情感细腻',
        primary: { traitId: 12, delta: 1.0 },
        secondary: [{ traitId: 2, delta: 0.3 }],
      },
      {
        text: '文',
        gloss: '散文自由，思想流畅',
        primary: { traitId: 12, delta: 0.6 },
        secondary: [{ traitId: 1, delta: 0.2 }],
      },
      {
        text: '赋',
        gloss: '赋体铺陈，气势恢宏',
        primary: { traitId: 12, delta: 1.2 },
        secondary: [{ traitId: 8, delta: 0.2 }],
      },
      {
        text: '皆不擅',
        gloss: '不擅长文体，质朴无华',
        primary: { traitId: 12, delta: -1.2 },
        secondary: [{ traitId: 9, delta: -0.2 }],
      },
      {
        text: '皆兼擅',
        gloss: '各种文体都能驾驭',
        primary: { traitId: 12, delta: -0.6 },
        secondary: [{ traitId: 8, delta: 0.3 }],
      },
    ],
  },
];
