// 镜心 · 科技巨擘（西方）· 48 题
// 12 维 × 4 题；半文言 / 科学语感，侧重思辨 / 革新 / 学识 / 风险

import type { Item } from './item.types';

export const ITEMS_WEST_SCIENTIST: readonly Item[] = [
  // ── T1 思辨 ──
  {
    id: 'ws-001',
    format: 'situational',
    prompt: '自然之序',
    promptGloss: '万物运行，汝信何种秩序？',
    options: [
      { text: '听之任之', gloss: '不问其理', primary: { traitId: 1, delta: -1.5 } },
      { text: '奉为神意', gloss: '以神为序', primary: { traitId: 1, delta: -0.8 } },
      { text: '归为常理', gloss: '以常为度', primary: { traitId: 1, delta: 0.0 } },
      { text: '推演其理', gloss: '以理为度', primary: { traitId: 1, delta: 0.8 } },
      { text: '立方程以式', gloss: '以数为律', primary: { traitId: 1, delta: 1.2 } },
      { text: '穷其第一因', gloss: '直追本原', primary: { traitId: 1, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-002',
    format: 'situational',
    prompt: '旧说之破',
    promptGloss: '权威之言与新证相违，汝何从？',
    options: [
      { text: '信古为上', gloss: '不疑旧说', primary: { traitId: 1, delta: -1.5 } },
      { text: '默而不言', gloss: '不评旧论', primary: { traitId: 1, delta: -0.6 } },
      { text: '折中存之', gloss: '两可之间', primary: { traitId: 1, delta: 0.0 } },
      { text: '以实验决', gloss: '以验为据', primary: { traitId: 1, delta: 0.8 } },
      { text: '公然破之', gloss: '以新破旧', primary: { traitId: 1, delta: 1.2 } },
      { text: '范式更替', gloss: '以新代旧', primary: { traitId: 1, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-003',
    format: 'imagery',
    prompt: '可见与可知',
    promptGloss: '汝欲见何物？',
    options: [
      { text: '眼前之影', gloss: '以见为真', primary: { traitId: 1, delta: -1.2 } },
      { text: '经验之集', gloss: '以验为真', primary: { traitId: 1, delta: -0.4 } },
      { text: '模型之图', gloss: '以图为真', primary: { traitId: 1, delta: 0.6 } },
      { text: '数学之式', gloss: '以式为真', primary: { traitId: 1, delta: 1.0 } },
      { text: '逻辑之链', gloss: '以推为真', primary: { traitId: 1, delta: 1.2 } },
      { text: '先验之构', gloss: '以理为先', primary: { traitId: 1, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-004',
    format: 'situational',
    prompt: '未证之理',
    promptGloss: '一理尚未证，汝敢言其有乎？',
    options: [
      { text: '不敢言', gloss: '以不证不言', primary: { traitId: 1, delta: -1.5 } },
      { text: '存疑可也', gloss: '暂不立论', primary: { traitId: 1, delta: -0.6 } },
      { text: '以理推之', gloss: '推而不证', primary: { traitId: 1, delta: 0.4 } },
      { text: '假设以立', gloss: '立而待证', primary: { traitId: 1, delta: 0.8 } },
      { text: '敢言之', gloss: '以理为足', primary: { traitId: 1, delta: 1.2 } },
      { text: '立而证之', gloss: '以行为证', primary: { traitId: 1, delta: 1.5 } },
    ],
  },

  // ── T2 情感 ──
  {
    id: 'ws-005',
    format: 'situational',
    prompt: '穷理之苦',
    promptGloss: '皓首穷经未必有成，汝何以自处？',
    options: [
      { text: '以理节情', gloss: '以智驭情', primary: { traitId: 2, delta: -1.2 } },
      { text: '淡然处之', gloss: '不强求', primary: { traitId: 2, delta: -0.4 } },
      { text: '平常以对', gloss: '不以为苦', primary: { traitId: 2, delta: 0.0 } },
      { text: '以志驱之', gloss: '以志为度', primary: { traitId: 2, delta: 0.6 } },
      { text: '乐在苦中', gloss: '以苦为乐', primary: { traitId: 2, delta: 1.2 } },
      { text: '忘乎所以', gloss: '以痴为度', primary: { traitId: 2, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-006',
    format: 'situational',
    prompt: '同道之讥',
    promptGloss: '同辈讥汝痴，汝何以应？',
    options: [
      { text: '怒而争之', gloss: '以怒应讥', primary: { traitId: 2, delta: -1.0 } },
      { text: '不答不理', gloss: '以默应讥', primary: { traitId: 2, delta: 0.0 } },
      { text: '笑而纳之', gloss: '以笑纳讥', primary: { traitId: 2, delta: 0.6 } },
      { text: '徐徐辩之', gloss: '以理服之', primary: { traitId: 2, delta: 0.4 } },
      { text: '以行证之', gloss: '不辩而行', primary: { traitId: 2, delta: 1.0 } },
      { text: '化讥为力', gloss: '以讥为鞭', primary: { traitId: 2, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-007',
    format: 'imagery',
    prompt: '冷月之思',
    promptGloss: '汝于独处，心境为何？',
    options: [
      { text: '寒冰', gloss: '以冷为度', primary: { traitId: 2, delta: -1.2 } },
      { text: '古井', gloss: '以静为度', primary: { traitId: 2, delta: -0.6 } },
      { text: '明镜', gloss: '以明为度', primary: { traitId: 2, delta: 0.0 } },
      { text: '灯焰', gloss: '以明为度', primary: { traitId: 2, delta: 0.6 } },
      { text: '烈火', gloss: '以炽为度', primary: { traitId: 2, delta: 1.2 } },
      { text: '太阳', gloss: '以极炽为度', primary: { traitId: 2, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-008',
    format: 'situational',
    prompt: '真理之美',
    promptGloss: '当一理之美动汝心，汝何以应？',
    options: [
      { text: '不动于色', gloss: '以理节美', primary: { traitId: 2, delta: -1.2 } },
      { text: '淡然记之', gloss: '不以为意', primary: { traitId: 2, delta: -0.4 } },
      { text: '欣然会之', gloss: '以会为度', primary: { traitId: 2, delta: 0.4 } },
      { text: '动容以叹', gloss: '以叹为度', primary: { traitId: 2, delta: 0.8 } },
      { text: '心为所摄', gloss: '以摄为度', primary: { traitId: 2, delta: 1.2 } },
      { text: '忘言忘身', gloss: '以忘为度', primary: { traitId: 2, delta: 1.5 } },
    ],
  },

  // ── T3 行动 ──
  {
    id: 'ws-009',
    format: 'situational',
    prompt: '手脑之先',
    promptGloss: '汝先思，抑或先行？',
    options: [
      { text: '坐而论道', gloss: '以思为先', primary: { traitId: 3, delta: -1.5 } },
      { text: '思半而行', gloss: '以中为度', primary: { traitId: 3, delta: -0.4 } },
      { text: '思后行', gloss: '以思导行', primary: { traitId: 3, delta: 0.4 } },
      { text: '行中思', gloss: '以行促思', primary: { traitId: 3, delta: 0.8 } },
      { text: '先行后思', gloss: '以行为先', primary: { traitId: 3, delta: 1.2 } },
      { text: '手脑合一', gloss: '以合为道', primary: { traitId: 3, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-010',
    format: 'situational',
    prompt: '千试一得',
    promptGloss: '一器之成必经千次失败，汝当如何？',
    options: [
      { text: '不试', gloss: '不为之', primary: { traitId: 3, delta: -1.5 } },
      { text: '试而不成止', gloss: '不耐久试', primary: { traitId: 3, delta: -0.8 } },
      { text: '百试', gloss: '以百为度', primary: { traitId: 3, delta: 0.0 } },
      { text: '千试', gloss: '以千为度', primary: { traitId: 3, delta: 0.8 } },
      { text: '万试', gloss: '以万为度', primary: { traitId: 3, delta: 1.2 } },
      { text: '试至天荒', gloss: '不止不息', primary: { traitId: 3, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-011',
    format: 'imagery',
    prompt: '纸上与器间',
    promptGloss: '汝之所得，归于何处？',
    options: [
      { text: '纸上', gloss: '止于笔端', primary: { traitId: 3, delta: -1.2 } },
      { text: '图中', gloss: '以图为归', primary: { traitId: 3, delta: -0.4 } },
      { text: '实验', gloss: '以验为归', primary: { traitId: 3, delta: 0.6 } },
      { text: '机中', gloss: '以器为归', primary: { traitId: 3, delta: 1.0 } },
      { text: '万用', gloss: '以用为归', primary: { traitId: 3, delta: 1.2 } },
      { text: '造物', gloss: '以创为归', primary: { traitId: 3, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-012',
    format: 'situational',
    prompt: '屡挫屡战',
    promptGloss: '试而不成、复试复败，汝当如何？',
    options: [
      { text: '沮丧而止', gloss: '以止为度', primary: { traitId: 3, delta: -1.5 } },
      { text: '暂歇再试', gloss: '以暂为度', primary: { traitId: 3, delta: -0.4 } },
      { text: '审思其因', gloss: '以思促行', primary: { traitId: 3, delta: 0.4 } },
      { text: '改法再试', gloss: '以变为度', primary: { traitId: 3, delta: 0.8 } },
      { text: '愈挫愈奋', gloss: '以挫为度', primary: { traitId: 3, delta: 1.2 } },
      { text: '以身为殉', gloss: '以死为度', primary: { traitId: 3, delta: 1.5 } },
    ],
  },

  // ── T4 革新 ──
  {
    id: 'ws-013',
    format: 'situational',
    prompt: '旧理已穷',
    promptGloss: '旧理穷而新理未立，汝当如何？',
    options: [
      { text: '守之', gloss: '不求变', primary: { traitId: 4, delta: -1.5 } },
      { text: '小修', gloss: '以小为度', primary: { traitId: 4, delta: -0.4 } },
      { text: '择善而从', gloss: '以用为度', primary: { traitId: 4, delta: 0.4 } },
      { text: '另立新理', gloss: '以新为度', primary: { traitId: 4, delta: 1.0 } },
      { text: '破旧而立', gloss: '以破为立', primary: { traitId: 4, delta: 1.2 } },
      { text: '范式革命', gloss: '以革命为度', primary: { traitId: 4, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-014',
    format: 'situational',
    prompt: '新理之出',
    promptGloss: '新理已得，世人疑之，汝当如何？',
    options: [
      { text: '藏而不出', gloss: '以藏为度', primary: { traitId: 4, delta: -1.0 } },
      { text: '待时而出', gloss: '以时为度', primary: { traitId: 4, delta: -0.4 } },
      { text: '自验而出', gloss: '以自为度', primary: { traitId: 4, delta: 0.4 } },
      { text: '公之于众', gloss: '以众为度', primary: { traitId: 4, delta: 0.8 } },
      { text: '强推之', gloss: '以力为度', primary: { traitId: 4, delta: 1.2 } },
      { text: '任天下评说', gloss: '以不辩为辩', primary: { traitId: 4, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-015',
    format: 'imagery',
    prompt: '旧瓶新酒',
    promptGloss: '新理已得，汝欲何载？',
    options: [
      { text: '旧瓶', gloss: '以旧载新', primary: { traitId: 4, delta: -0.8 } },
      { text: '半新半旧', gloss: '以中为度', primary: { traitId: 4, delta: 0.0 } },
      { text: '新瓶旧酒', gloss: '以新载旧', primary: { traitId: 4, delta: 0.4 } },
      { text: '新瓶新酒', gloss: '以新载新', primary: { traitId: 4, delta: 0.8 } },
      { text: '破瓶倾酒', gloss: '以破为度', primary: { traitId: 4, delta: 1.2 } },
      { text: '无瓶无酒', gloss: '以不立为度', primary: { traitId: 4, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-016',
    format: 'situational',
    prompt: '新代旧',
    promptGloss: '新理已立，旧制尚存，汝何从？',
    options: [
      { text: '守旧', gloss: '以旧为度', primary: { traitId: 4, delta: -1.2 } },
      { text: '新旧并行', gloss: '以并行度', primary: { traitId: 4, delta: -0.4 } },
      { text: '以旧证新', gloss: '以旧为证', primary: { traitId: 4, delta: 0.4 } },
      { text: '以新辅旧', gloss: '以新为辅', primary: { traitId: 4, delta: 0.6 } },
      { text: '以新代旧', gloss: '以新代旧', primary: { traitId: 4, delta: 1.0 } },
      { text: '化旧为新', gloss: '以化为度', primary: { traitId: 4, delta: 1.5 } },
    ],
  },

  // ── T5 群我 ──
  {
    id: 'ws-017',
    format: 'situational',
    prompt: '私秘与公器',
    promptGloss: '汝之所得，藏之为私，抑或公之？',
    options: [
      { text: '秘而不宣', gloss: '以秘为度', primary: { traitId: 5, delta: -1.2 } },
      { text: '传于弟子', gloss: '以师为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '藏于学会', gloss: '以会为度', primary: { traitId: 5, delta: 0.0 } },
      { text: '公之于刊', gloss: '以刊为度', primary: { traitId: 5, delta: 0.8 } },
      { text: '传于全欧', gloss: '以全为度', primary: { traitId: 5, delta: 1.2 } },
      { text: '遗于万世', gloss: '以万为度', primary: { traitId: 5, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-018',
    format: 'situational',
    prompt: '学派之争',
    promptGloss: '学派相争，汝当何从？',
    options: [
      { text: '党同伐异', gloss: '以争为度', primary: { traitId: 5, delta: -1.2 } },
      { text: '守己之门', gloss: '以守为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '不偏不党', gloss: '以中为度', primary: { traitId: 5, delta: 0.0 } },
      { text: '择优而从', gloss: '以择为度', primary: { traitId: 5, delta: 0.4 } },
      { text: '合而为一', gloss: '以合为度', primary: { traitId: 5, delta: 1.0 } },
      { text: '立为公学', gloss: '以公为度', primary: { traitId: 5, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-019',
    format: 'imagery',
    prompt: '一灯与千灯',
    promptGloss: '汝之灯，欲照几隅？',
    options: [
      { text: '一隅', gloss: '以一为度', primary: { traitId: 5, delta: -1.0 } },
      { text: '一室', gloss: '以室为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '一城', gloss: '以城为度', primary: { traitId: 5, delta: 0.2 } },
      { text: '一国', gloss: '以国为度', primary: { traitId: 5, delta: 0.6 } },
      { text: '一洲', gloss: '以洲为度', primary: { traitId: 5, delta: 1.0 } },
      { text: '万邦共照', gloss: '以万为度', primary: { traitId: 5, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-020',
    format: 'situational',
    prompt: '独研与共研',
    promptGloss: '为学当独，抑或共？',
    options: [
      { text: '独研', gloss: '以独为度', primary: { traitId: 5, delta: -0.6 } },
      { text: '半独半共', gloss: '以中为度', primary: { traitId: 5, delta: 0.0 } },
      { text: '合众共研', gloss: '以合为度', primary: { traitId: 5, delta: 0.6 } },
      { text: '立学会共研', gloss: '以会为度', primary: { traitId: 5, delta: 1.0 } },
      { text: '跨国共研', gloss: '以国为度', primary: { traitId: 5, delta: 1.2 } },
      { text: '天下共研', gloss: '以天下为度', primary: { traitId: 5, delta: 1.5 } },
    ],
  },

  // ── T6 审美 ──
  {
    id: 'ws-021',
    format: 'imagery',
    prompt: '方程之美',
    promptGloss: '汝观一理，何者动汝？',
    options: [
      { text: '用之美', gloss: '以用为美', primary: { traitId: 6, delta: -1.0 } },
      { text: '简之美', gloss: '以简为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '整之美', gloss: '以整为美', primary: { traitId: 6, delta: 0.0 } },
      { text: '对之美', gloss: '以对为美', primary: { traitId: 6, delta: 0.4 } },
      { text: '和之美', gloss: '以和为美', primary: { traitId: 6, delta: 0.8 } },
      { text: '神之美', gloss: '以神为美', primary: { traitId: 6, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-022',
    format: 'situational',
    prompt: '器之形',
    promptGloss: '一器之形，汝以何为上？',
    options: [
      { text: '唯用', gloss: '以用为度', primary: { traitId: 6, delta: -1.0 } },
      { text: '朴', gloss: '以朴为度', primary: { traitId: 6, delta: -0.4 } },
      { text: '清', gloss: '以清为度', primary: { traitId: 6, delta: 0.0 } },
      { text: '雅', gloss: '以雅为度', primary: { traitId: 6, delta: 0.4 } },
      { text: '华', gloss: '以华为度', primary: { traitId: 6, delta: 0.8 } },
      { text: '极美', gloss: '以极为美', primary: { traitId: 6, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-023',
    format: 'situational',
    prompt: '图样之饰',
    promptGloss: '一图之绘，繁简如何？',
    options: [
      { text: '极简', gloss: '以简为度', primary: { traitId: 6, delta: -1.0 } },
      { text: '简', gloss: '以简为度', primary: { traitId: 6, delta: -0.4 } },
      { text: '适中', gloss: '以适为度', primary: { traitId: 6, delta: 0.0 } },
      { text: '繁', gloss: '以繁为度', primary: { traitId: 6, delta: 0.4 } },
      { text: '极繁', gloss: '以极为度', primary: { traitId: 6, delta: 1.0 } },
      { text: '繁而有序', gloss: '以序为度', primary: { traitId: 6, delta: 0.8 } },
    ],
  },
  {
    id: 'ws-024',
    format: 'imagery',
    prompt: '宇宙之象',
    promptGloss: '汝于宇宙之美，何者动汝？',
    options: [
      { text: '秩序', gloss: '以序为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '对偶', gloss: '以对为美', primary: { traitId: 6, delta: 0.0 } },
      { text: '繁星', gloss: '以多为美', primary: { traitId: 6, delta: 0.4 } },
      { text: '幽微', gloss: '以微为美', primary: { traitId: 6, delta: 0.8 } },
      { text: '宏阔', gloss: '以大为美', primary: { traitId: 6, delta: 1.2 } },
      { text: '至美', gloss: '以至美为度', primary: { traitId: 6, delta: 1.5 } },
    ],
  },

  // ── T7 意志 ──
  {
    id: 'ws-025',
    format: 'situational',
    prompt: '千试不成',
    promptGloss: '千试而不成，汝当如何？',
    options: [
      { text: '止而不试', gloss: '以止为度', primary: { traitId: 7, delta: -1.5 } },
      { text: '改途以试', gloss: '以变为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '稳步以试', gloss: '以稳为度', primary: { traitId: 7, delta: 0.4 } },
      { text: '百折不回', gloss: '以折为度', primary: { traitId: 7, delta: 1.0 } },
      { text: '死而后已', gloss: '以死为度', primary: { traitId: 7, delta: 1.5 } },
      { text: '以乐承苦', gloss: '以乐为度', primary: { traitId: 7, delta: 1.2 } },
    ],
  },
  {
    id: 'ws-026',
    format: 'situational',
    prompt: '众讥汝痴',
    promptGloss: '众人讥汝痴狂，汝当如何？',
    options: [
      { text: '改弦易辙', gloss: '以从众止', primary: { traitId: 7, delta: -1.5 } },
      { text: '暂避其锋', gloss: '以避为度', primary: { traitId: 7, delta: -0.6 } },
      { text: '徐徐以辩', gloss: '以辩为度', primary: { traitId: 7, delta: 0.0 } },
      { text: '自持以行', gloss: '以行为度', primary: { traitId: 7, delta: 0.8 } },
      { text: '以身为殉', gloss: '以死为度', primary: { traitId: 7, delta: 1.5 } },
      { text: '不辩不答', gloss: '以不答为度', primary: { traitId: 7, delta: 0.6 } },
    ],
  },
  {
    id: 'ws-027',
    format: 'imagery',
    prompt: '金刚与卵石',
    promptGloss: '汝欲为金刚石，抑或卵石？',
    options: [
      { text: '卵石', gloss: '以柔为度', primary: { traitId: 7, delta: -1.0 } },
      { text: '砂砾', gloss: '以散为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '青石', gloss: '以刚为度', primary: { traitId: 7, delta: 0.4 } },
      { text: '金刚石', gloss: '以极刚为度', primary: { traitId: 7, delta: 1.0 } },
      { text: '砺石', gloss: '以磨为度', primary: { traitId: 7, delta: 0.8 } },
      { text: '水晶', gloss: '以明为度', primary: { traitId: 7, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-028',
    format: 'situational',
    prompt: '穷途之叹',
    promptGloss: '穷途而道不行，汝何以自处？',
    options: [
      { text: '改道', gloss: '以变为度', primary: { traitId: 7, delta: -0.8 } },
      { text: '独行', gloss: '以独为度', primary: { traitId: 7, delta: 0.4 } },
      { text: '传之于人', gloss: '以传为度', primary: { traitId: 7, delta: 1.0 } },
      { text: '著书立说', gloss: '以言为度', primary: { traitId: 7, delta: 1.2 } },
      { text: '死守', gloss: '以死为度', primary: { traitId: 7, delta: 1.5 } },
      { text: '退而传道', gloss: '以退为度', primary: { traitId: 7, delta: 0.6 } },
    ],
  },

  // ── T8 学识 ──
  {
    id: 'ws-029',
    format: 'situational',
    prompt: '学之博约',
    promptGloss: '学当博，抑或约？',
    options: [
      { text: '唯约', gloss: '以约为度', primary: { traitId: 8, delta: -0.4 } },
      { text: '半约半博', gloss: '以中为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '唯博', gloss: '以博为度', primary: { traitId: 8, delta: 0.4 } },
      { text: '由约入博', gloss: '以约始博终', primary: { traitId: 8, delta: 0.8 } },
      { text: '由博返约', gloss: '以博始约终', primary: { traitId: 8, delta: 1.0 } },
      { text: '博而能约', gloss: '以博约兼为度', primary: { traitId: 8, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-030',
    format: 'situational',
    prompt: '古今之学',
    promptGloss: '今人之学，胜于古人乎？',
    options: [
      { text: '古胜今', gloss: '以古为度', primary: { traitId: 8, delta: -1.0 } },
      { text: '古为基', gloss: '以古为基', primary: { traitId: 8, delta: -0.4 } },
      { text: '各有所长', gloss: '以兼为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '今为古继', gloss: '以继为度', primary: { traitId: 8, delta: 0.4 } },
      { text: '今胜于古', gloss: '以今为度', primary: { traitId: 8, delta: 0.8 } },
      { text: '日新又新', gloss: '以新为度', primary: { traitId: 8, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-031',
    format: 'imagery',
    prompt: '井与海',
    promptGloss: '汝欲为井，抑或海？',
    options: [
      { text: '井', gloss: '以井为度', primary: { traitId: 8, delta: -0.6 } },
      { text: '池', gloss: '以池为度', primary: { traitId: 8, delta: -0.2 } },
      { text: '湖', gloss: '以湖为度', primary: { traitId: 8, delta: 0.2 } },
      { text: '江', gloss: '以江为度', primary: { traitId: 8, delta: 0.6 } },
      { text: '海', gloss: '以海为度', primary: { traitId: 8, delta: 1.0 } },
      { text: '海纳百川', gloss: '以纳为度', primary: { traitId: 8, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-032',
    format: 'situational',
    prompt: '通才与专才',
    promptGloss: '为学当通才，抑或专才？',
    options: [
      { text: '唯专', gloss: '以专为度', primary: { traitId: 8, delta: -0.4 } },
      { text: '半专半通', gloss: '以中为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '唯通', gloss: '以通为度', primary: { traitId: 8, delta: 0.4 } },
      { text: '由专入通', gloss: '以专始通终', primary: { traitId: 8, delta: 0.8 } },
      { text: '由通入专', gloss: '以通始专终', primary: { traitId: 8, delta: 1.0 } },
      { text: '专而能通', gloss: '以兼为度', primary: { traitId: 8, delta: 1.5 } },
    ],
  },

  // ── T9 处世 ──
  {
    id: 'ws-033',
    format: 'situational',
    prompt: '仕与隐',
    promptGloss: '才成之后，汝欲何往？',
    options: [
      { text: '出仕', gloss: '以进为度', primary: { traitId: 9, delta: -1.2 } },
      { text: '半仕半隐', gloss: '以中为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '退而专学', gloss: '以退为度', primary: { traitId: 9, delta: 0.4 } },
      { text: '退而传学', gloss: '以传为度', primary: { traitId: 9, delta: 1.0 } },
      { text: '退而忘名', gloss: '以忘为度', primary: { traitId: 9, delta: 1.5 } },
      { text: '归田著书', gloss: '以终为度', primary: { traitId: 9, delta: 1.2 } },
    ],
  },
  {
    id: 'ws-034',
    format: 'situational',
    prompt: '得志与失意',
    promptGloss: '得志则行，失意则隐，汝取何为？',
    options: [
      { text: '得志则行', gloss: '以得为度', primary: { traitId: 9, delta: -0.6 } },
      { text: '得志亦止', gloss: '以止为度', primary: { traitId: 9, delta: 0.4 } },
      { text: '失意亦行', gloss: '以行为度', primary: { traitId: 9, delta: -0.8 } },
      { text: '行藏以时', gloss: '以时为度', primary: { traitId: 9, delta: 0.0 } },
      { text: '行藏由己', gloss: '以己为度', primary: { traitId: 9, delta: 1.0 } },
      { text: '行藏由理', gloss: '以理为度', primary: { traitId: 9, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-035',
    format: 'imagery',
    prompt: '舟与塔',
    promptGloss: '汝欲为舟，抑或塔？',
    options: [
      { text: '舟', gloss: '以行为度', primary: { traitId: 9, delta: -1.0 } },
      { text: '舴艋', gloss: '以小为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '帆', gloss: '以动为度', primary: { traitId: 9, delta: 0.0 } },
      { text: '塔', gloss: '以立为度', primary: { traitId: 9, delta: 0.8 } },
      { text: '灯塔', gloss: '以守为度', primary: { traitId: 9, delta: 1.2 } },
      { text: '孤岛', gloss: '以独为度', primary: { traitId: 9, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-036',
    format: 'situational',
    prompt: '身后之名',
    promptGloss: '身后之名，汝欲何为？',
    options: [
      { text: '不计', gloss: '以不名为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '求当世名', gloss: '以当世为度', primary: { traitId: 9, delta: -0.2 } },
      { text: '求百世名', gloss: '以百世为度', primary: { traitId: 9, delta: 0.4 } },
      { text: '求万世名', gloss: '以万世为度', primary: { traitId: 9, delta: 1.0 } },
      { text: '求千古名', gloss: '以千古为度', primary: { traitId: 9, delta: 1.5 } },
      { text: '以名为累', gloss: '以忘为度', primary: { traitId: 9, delta: -0.6 } },
    ],
  },

  // ── T10 时间 ──
  {
    id: 'ws-037',
    format: 'situational',
    prompt: '百代之功',
    promptGloss: '一理之成，可传百代，汝欲何用？',
    options: [
      { text: '急功', gloss: '以急为度', primary: { traitId: 10, delta: -1.2 } },
      { text: '十年', gloss: '以十为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '一世', gloss: '以一世为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '百世', gloss: '以百世为度', primary: { traitId: 10, delta: 0.8 } },
      { text: '万世', gloss: '以万世为度', primary: { traitId: 10, delta: 1.2 } },
      { text: '与天地齐', gloss: '以永为度', primary: { traitId: 10, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-038',
    format: 'situational',
    prompt: '一器与千代',
    promptGloss: '一器可传千代，汝欲为之乎？',
    options: [
      { text: '不传', gloss: '以一身为度', primary: { traitId: 10, delta: -1.2 } },
      { text: '传于子孙', gloss: '以家为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '传于当世', gloss: '以当世为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '传于百世', gloss: '以百世为度', primary: { traitId: 10, delta: 0.8 } },
      { text: '传于万世', gloss: '以万世为度', primary: { traitId: 10, delta: 1.2 } },
      { text: '与天地齐', gloss: '以永为度', primary: { traitId: 10, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-039',
    format: 'imagery',
    prompt: '寸阴与尺璧',
    promptGloss: '寸阴与尺璧，汝取何为贵？',
    options: [
      { text: '寸阴', gloss: '以寸阴为度', primary: { traitId: 10, delta: -0.6 } },
      { text: '兼取', gloss: '以兼为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '尺璧', gloss: '以尺璧为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '古之所贵', gloss: '以古为度', primary: { traitId: 10, delta: 0.6 } },
      { text: '寸阴难买', gloss: '以难为度', primary: { traitId: 10, delta: 1.0 } },
      { text: '与化同流', gloss: '以化为度', primary: { traitId: 10, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-040',
    format: 'situational',
    prompt: '今与古',
    promptGloss: '今人之术，胜于古人乎？',
    options: [
      { text: '今胜古', gloss: '以今为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '古胜今', gloss: '以古为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '各有所长', gloss: '以兼为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '今为古继', gloss: '以继为度', primary: { traitId: 10, delta: 0.6 } },
      { text: '古为今基', gloss: '以基为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '与化同新', gloss: '以化为度', primary: { traitId: 10, delta: 1.5 } },
    ],
  },

  // ── T11 风险 ──
  {
    id: 'ws-041',
    format: 'situational',
    prompt: '未验之器',
    promptGloss: '一器未验，汝敢用之乎？',
    options: [
      { text: '不敢', gloss: '以不为度', primary: { traitId: 11, delta: -1.5 } },
      { text: '小试之', gloss: '以试为度', primary: { traitId: 11, delta: -0.6 } },
      { text: '半用半试', gloss: '以中为度', primary: { traitId: 11, delta: 0.0 } },
      { text: '敢用之', gloss: '以敢为度', primary: { traitId: 11, delta: 0.8 } },
      { text: '以身为试', gloss: '以身为度', primary: { traitId: 11, delta: 1.2 } },
      { text: '以死为度', gloss: '以死为度', primary: { traitId: 11, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-042',
    format: 'situational',
    prompt: '以身为验',
    promptGloss: '欲验新理，汝以何为试？',
    options: [
      { text: '不敢试', gloss: '不涉险', primary: { traitId: 11, delta: -1.5 } },
      { text: '以物试', gloss: '以物为度', primary: { traitId: 11, delta: -0.8 } },
      { text: '以兽试', gloss: '以兽为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '以己试', gloss: '以己为度', primary: { traitId: 11, delta: 0.6 } },
      { text: '以亲属试', gloss: '以亲为度', primary: { traitId: 11, delta: 0.4 } },
      { text: '以身为殉', gloss: '以死为度', primary: { traitId: 11, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-043',
    format: 'imagery',
    prompt: '孤舟与巨浪',
    promptGloss: '新理如孤舟入海，汝何以对？',
    options: [
      { text: '不渡', gloss: '以不渡为度', primary: { traitId: 11, delta: -1.5 } },
      { text: '近岸行', gloss: '以近为度', primary: { traitId: 11, delta: -0.6 } },
      { text: '半海', gloss: '以中为度', primary: { traitId: 11, delta: 0.0 } },
      { text: '远航', gloss: '以远为度', primary: { traitId: 11, delta: 0.6 } },
      { text: '穷海', gloss: '以穷为度', primary: { traitId: 11, delta: 1.0 } },
      { text: '与海同化', gloss: '以化为度', primary: { traitId: 11, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-044',
    format: 'situational',
    prompt: '新理之争',
    promptGloss: '新理一立，旧派阻之，汝当如何？',
    options: [
      { text: '退让', gloss: '以让为度', primary: { traitId: 11, delta: -1.2 } },
      { text: '婉转', gloss: '以婉为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '稳进', gloss: '以稳为度', primary: { traitId: 11, delta: 0.4 } },
      { text: '强推', gloss: '以强为度', primary: { traitId: 11, delta: 1.0 } },
      { text: '以死争之', gloss: '以死为度', primary: { traitId: 11, delta: 1.5 } },
      { text: '以行证之', gloss: '以行为度', primary: { traitId: 11, delta: 0.6 } },
    ],
  },

  // ── T12 表达 ──
  {
    id: 'ws-045',
    format: 'situational',
    prompt: '一理之传',
    promptGloss: '一理已成，汝欲何传？',
    options: [
      { text: '默而不宣', gloss: '以默为度', primary: { traitId: 12, delta: -1.2 } },
      { text: '口传', gloss: '以口为度', primary: { traitId: 12, delta: -0.6 } },
      { text: '笔传', gloss: '以笔为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '图传', gloss: '以图为度', primary: { traitId: 12, delta: 0.4 } },
      { text: '式传', gloss: '以式为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '公理化', gloss: '以公为度', primary: { traitId: 12, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-046',
    format: 'situational',
    prompt: '著书之辞',
    promptGloss: '著书之辞，汝取何格？',
    options: [
      { text: '极简', gloss: '以简为度', primary: { traitId: 12, delta: -0.8 } },
      { text: '简', gloss: '以简为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '适', gloss: '以适为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '繁', gloss: '以繁为度', primary: { traitId: 12, delta: 0.4 } },
      { text: '极繁', gloss: '以繁为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '图穷理现', gloss: '以图为度', primary: { traitId: 12, delta: 0.8 } },
    ],
  },
  {
    id: 'ws-047',
    format: 'imagery',
    prompt: '言之器',
    promptGloss: '传理之器，汝欲何为？',
    options: [
      { text: '口耳', gloss: '以口为度', primary: { traitId: 12, delta: -1.2 } },
      { text: '册页', gloss: '以册为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '书', gloss: '以书为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '图', gloss: '以图为度', primary: { traitId: 12, delta: 0.6 } },
      { text: '式', gloss: '以式为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '模', gloss: '以模为度', primary: { traitId: 12, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-048',
    format: 'situational',
    prompt: '万言之传',
    promptGloss: '一理之传，汝欲万言以传，抑或千言以传？',
    options: [
      { text: '千言', gloss: '以千为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '半千', gloss: '以半为度', primary: { traitId: 12, delta: -0.6 } },
      { text: '百言', gloss: '以百为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '十言', gloss: '以十为度', primary: { traitId: 12, delta: 0.4 } },
      { text: '一言', gloss: '以一为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '无言', gloss: '以不立为度', primary: { traitId: 12, delta: 1.5 } },
    ],
  },
];
