// 镜心 · 科技先贤 · 48 题
// 12 维 × 4 题；侧重思辨 / 革新 / 学识 / 风险

import type { Item } from './item.types';

export const ITEMS_EAST_SCIENTIST: readonly Item[] = [
  // ── T1 思辨 ──
  {
    id: 'esci-001',
    format: 'situational',
    prompt: '万物有源',
    promptGloss: '天下万物，何以为知？',
    options: [
      { text: '观象', gloss: '以目为知', primary: { traitId: 1, delta: -0.6 } },
      { text: '察理', gloss: '以思为知', primary: { traitId: 1, delta: 0.6 } },
      {
        text: '格物',
        gloss: '以物为知',
        primary: { traitId: 1, delta: 1.2 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
      { text: '穷理', gloss: '以理为至', primary: { traitId: 1, delta: 1.4 } },
      {
        text: '致用',
        gloss: '以用为知',
        primary: { traitId: 1, delta: 0.4 },
        secondary: [{ traitId: 3, delta: 0.3 }],
      },
      { text: '不求甚解', gloss: '以浑为知', primary: { traitId: 1, delta: -1.0 } },
    ],
  },
  {
    id: 'esci-002',
    format: 'situational',
    prompt: '新理之惑',
    promptGloss: '一理新出，与旧说相悖，汝当何从？',
    options: [
      { text: '信古', gloss: '从旧', primary: { traitId: 1, delta: -1.2 } },
      { text: '慎择', gloss: '以理度之', primary: { traitId: 1, delta: 0.4 } },
      { text: '穷理以验', gloss: '以验为据', primary: { traitId: 1, delta: 1.2 } },
      {
        text: '唯新是从',
        gloss: '以新为是',
        primary: { traitId: 1, delta: 0.4 },
        secondary: [{ traitId: 4, delta: 0.3 }],
      },
      {
        text: '古为体新为用',
        gloss: '融贯',
        primary: { traitId: 1, delta: 0.8 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
      { text: '存而不论', gloss: '不评', primary: { traitId: 1, delta: -0.6 } },
    ],
  },
  {
    id: 'esci-003',
    format: 'imagery',
    prompt: '以器载道',
    promptGloss: '道之精微，汝欲何载？',
    options: [
      { text: '口耳', gloss: '以声为载', primary: { traitId: 1, delta: -0.8 } },
      { text: '文墨', gloss: '以书为载', primary: { traitId: 1, delta: 0.4 } },
      { text: '器物', gloss: '以器为载', primary: { traitId: 1, delta: 1.0 } },
      { text: '图数', gloss: '以数为载', primary: { traitId: 1, delta: 1.4 } },
      {
        text: '心神',
        gloss: '以心为载',
        primary: { traitId: 1, delta: -0.4 },
        secondary: [{ traitId: 2, delta: 0.3 }],
      },
      { text: '无言', gloss: '以不载为载', primary: { traitId: 1, delta: -0.6 } },
    ],
  },
  {
    id: 'esci-004',
    format: 'situational',
    prompt: '万理之归',
    promptGloss: '万物各有其理，汝以何理为归？',
    options: [
      { text: '天理', gloss: '以天为归', primary: { traitId: 1, delta: 0.6 } },
      {
        text: '物理',
        gloss: '以物为归',
        primary: { traitId: 1, delta: 1.2 },
        secondary: [{ traitId: 8, delta: 0.3 }],
      },
      { text: '数理', gloss: '以数为归', primary: { traitId: 1, delta: 1.4 } },
      { text: '事理', gloss: '以事为归', primary: { traitId: 1, delta: 0.4 } },
      { text: '心理', gloss: '以心为归', primary: { traitId: 1, delta: -0.6 } },
      { text: '无理', gloss: '以不归为归', primary: { traitId: 1, delta: -1.0 } },
    ],
  },

  // ── T2 情感 ──
  {
    id: 'esci-005',
    format: 'situational',
    prompt: '为学之苦',
    promptGloss: '穷经皓首，未必有成，汝何以自处？',
    options: [
      { text: '以苦为乐', gloss: '乐在学中', primary: { traitId: 2, delta: 1.4 } },
      {
        text: '持志以行',
        gloss: '以志驱苦',
        primary: { traitId: 2, delta: 0.6 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      { text: '顺其自然', gloss: '不强求', primary: { traitId: 2, delta: 0.0 } },
      { text: '苦中寻乐', gloss: '以苦为阶', primary: { traitId: 2, delta: 0.8 } },
      { text: '逃苦求乐', gloss: '以乐为上', primary: { traitId: 2, delta: -1.0 } },
      { text: '不以为苦', gloss: '以无苦为度', primary: { traitId: 2, delta: 0.4 } },
    ],
  },
  {
    id: 'esci-006',
    format: 'situational',
    prompt: '以身为试',
    promptGloss: '欲证一理，当以身为试乎？',
    options: [
      { text: '不敢', gloss: '不涉险', primary: { traitId: 2, delta: -1.0 } },
      { text: '慎为之', gloss: '以慎为度', primary: { traitId: 2, delta: 0.0 } },
      {
        text: '必试之',
        gloss: '以身为度',
        primary: { traitId: 2, delta: 1.0 },
        secondary: [{ traitId: 11, delta: 0.4 }],
      },
      { text: '舍身以试', gloss: '以身殉道', primary: { traitId: 2, delta: 1.4 } },
      { text: '请人代试', gloss: '以人为度', primary: { traitId: 2, delta: -0.4 } },
      {
        text: '以理推之',
        gloss: '不试而推',
        primary: { traitId: 2, delta: 0.4 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
    ],
  },
  {
    id: 'esci-007',
    format: 'imagery',
    prompt: '冷板凳',
    promptGloss: '学问如冷板凳，汝何以坐？',
    options: [
      { text: '不坐', gloss: '以热为志', primary: { traitId: 2, delta: -0.8 } },
      { text: '暂坐', gloss: '以暂为度', primary: { traitId: 2, delta: -0.2 } },
      { text: '久坐', gloss: '以久为度', primary: { traitId: 2, delta: 0.4 } },
      { text: '安坐', gloss: '以安为度', primary: { traitId: 2, delta: 0.8 } },
      { text: '乐坐', gloss: '以乐为度', primary: { traitId: 2, delta: 1.2 } },
      { text: '忘坐', gloss: '以忘为度', primary: { traitId: 2, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-008',
    format: 'situational',
    prompt: '同道之讥',
    promptGloss: '同道讥汝迂腐，汝何以对？',
    options: [
      { text: '怒而争之', gloss: '以怒应讥', primary: { traitId: 2, delta: -0.4 } },
      { text: '不答', gloss: '以默为答', primary: { traitId: 2, delta: 0.6 } },
      { text: '笑而纳之', gloss: '以笑纳讥', primary: { traitId: 2, delta: 1.0 } },
      { text: '讽而答之', gloss: '以讥还讥', primary: { traitId: 2, delta: -0.6 } },
      {
        text: '徐徐辩之',
        gloss: '以理服人',
        primary: { traitId: 2, delta: 0.0 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
      { text: '以行证之', gloss: '不辩而行', primary: { traitId: 2, delta: 0.4 } },
    ],
  },

  // ── T3 行动 ──
  {
    id: 'esci-009',
    format: 'situational',
    prompt: '手脑之择',
    promptGloss: '汝以何为先？',
    options: [
      { text: '坐而论道', gloss: '以思为上', primary: { traitId: 3, delta: -1.2 } },
      { text: '半思半行', gloss: '思行并重', primary: { traitId: 3, delta: 0.0 } },
      { text: '思后行', gloss: '以思导行', primary: { traitId: 3, delta: 0.4 } },
      { text: '行中思', gloss: '以行促思', primary: { traitId: 3, delta: 0.6 } },
      { text: '先行后思', gloss: '以行为先', primary: { traitId: 3, delta: 1.0 } },
      { text: '手脑合一', gloss: '以合为道', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-010',
    format: 'situational',
    prompt: '一器之成',
    promptGloss: '一器之成必经千次试验，汝当如何？',
    options: [
      { text: '不试', gloss: '不为之', primary: { traitId: 3, delta: -1.2 } },
      { text: '试而不成则止', gloss: '不耐久试', primary: { traitId: 3, delta: -0.6 } },
      { text: '十试', gloss: '以十为度', primary: { traitId: 3, delta: 0.0 } },
      { text: '百试', gloss: '以百为度', primary: { traitId: 3, delta: 0.6 } },
      {
        text: '千试',
        gloss: '以千为度',
        primary: { traitId: 3, delta: 1.2 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      { text: '万试不止', gloss: '以恒为度', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-011',
    format: 'imagery',
    prompt: '纸上与器间',
    promptGloss: '学问于纸，汝欲成之何处？',
    options: [
      { text: '纸上', gloss: '不涉器', primary: { traitId: 3, delta: -1.0 } },
      { text: '半纸半器', gloss: '以纸为基', primary: { traitId: 3, delta: -0.4 } },
      { text: '由纸入器', gloss: '以器为归', primary: { traitId: 3, delta: 0.4 } },
      { text: '以器证纸', gloss: '以行为证', primary: { traitId: 3, delta: 0.8 } },
      { text: '以器为纸', gloss: '不立文字', primary: { traitId: 3, delta: 1.2 } },
      { text: '手脑相生', gloss: '以合为道', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-012',
    format: 'situational',
    prompt: '不期之成',
    promptGloss: '千试而不期一朝得成，汝当如何？',
    options: [
      { text: '沮丧而止', gloss: '不恒', primary: { traitId: 3, delta: -1.2 } },
      { text: '暂歇再试', gloss: '暂息', primary: { traitId: 3, delta: -0.4 } },
      { text: '审思其因', gloss: '以思促行', primary: { traitId: 3, delta: 0.2 } },
      {
        text: '更法再试',
        gloss: '以变为进',
        primary: { traitId: 3, delta: 0.6 },
        secondary: [{ traitId: 4, delta: 0.3 }],
      },
      {
        text: '愈挫愈试',
        gloss: '以苦为志',
        primary: { traitId: 3, delta: 1.2 },
        secondary: [{ traitId: 7, delta: 0.4 }],
      },
      { text: '以身相殉', gloss: '以死为度', primary: { traitId: 3, delta: 1.4 } },
    ],
  },

  // ── T4 革新 ──
  {
    id: 'esci-013',
    format: 'situational',
    prompt: '古法已穷',
    promptGloss: '古法已穷其变，汝当守之，抑或变之？',
    options: [
      { text: '守之', gloss: '不求变', primary: { traitId: 4, delta: -1.2 } },
      { text: '小变', gloss: '以小为度', primary: { traitId: 4, delta: -0.4 } },
      { text: '择善而变', gloss: '以用为度', primary: { traitId: 4, delta: 0.2 } },
      { text: '大破大立', gloss: '以破为立', primary: { traitId: 4, delta: 1.0 } },
      { text: '另辟蹊径', gloss: '以新为度', primary: { traitId: 4, delta: 1.2 } },
      { text: '破万法', gloss: '以破为道', primary: { traitId: 4, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-014',
    format: 'situational',
    prompt: '新器初成',
    promptGloss: '新器初成，世人疑之，汝当如何？',
    options: [
      { text: '藏而不出', gloss: '以藏为度', primary: { traitId: 4, delta: -0.8 } },
      { text: '待时而出', gloss: '以时为度', primary: { traitId: 4, delta: -0.2 } },
      { text: '自用而验', gloss: '以自为度', primary: { traitId: 4, delta: 0.4 } },
      { text: '公之于众', gloss: '以众为度', primary: { traitId: 4, delta: 0.8 } },
      { text: '强推之', gloss: '以力为度', primary: { traitId: 4, delta: 1.0 } },
      { text: '任其评说', gloss: '以不辩为辩', primary: { traitId: 4, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-015',
    format: 'imagery',
    prompt: '旧瓶与新酒',
    promptGloss: '新理已得，汝欲何载？',
    options: [
      { text: '旧瓶', gloss: '以古载新', primary: { traitId: 4, delta: -0.6 } },
      { text: '半新半旧', gloss: '以调和为度', primary: { traitId: 4, delta: 0.0 } },
      { text: '新瓶旧酒', gloss: '以新载古', primary: { traitId: 4, delta: 0.4 } },
      { text: '新瓶新酒', gloss: '以新载新', primary: { traitId: 4, delta: 0.8 } },
      { text: '破瓶倾酒', gloss: '以破为度', primary: { traitId: 4, delta: 1.2 } },
      { text: '无瓶无酒', gloss: '以不立为度', primary: { traitId: 4, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-016',
    format: 'situational',
    prompt: '以旧辅新',
    promptGloss: '新理已得，旧器尚可用，汝当何从？',
    options: [
      { text: '守旧器', gloss: '以旧为度', primary: { traitId: 4, delta: -1.0 } },
      { text: '新旧并行', gloss: '以并行度', primary: { traitId: 4, delta: 0.0 } },
      { text: '以旧证新', gloss: '以旧为证', primary: { traitId: 4, delta: 0.2 } },
      { text: '以新辅旧', gloss: '以新为辅', primary: { traitId: 4, delta: 0.6 } },
      { text: '以新代旧', gloss: '以新为度', primary: { traitId: 4, delta: 1.0 } },
      { text: '化旧为新', gloss: '以化代破', primary: { traitId: 4, delta: 1.4 } },
    ],
  },

  // ── T5 群我 ──
  {
    id: 'esci-017',
    format: 'situational',
    prompt: '私学与公学',
    promptGloss: '汝之所得，藏之为私学，抑或公之于众？',
    options: [
      { text: '藏于名山', gloss: '以藏为度', primary: { traitId: 5, delta: -0.8 } },
      { text: '传于子孙', gloss: '以家为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '传于门下', gloss: '以师为度', primary: { traitId: 5, delta: 0.0 } },
      { text: '公之于众', gloss: '以众为度', primary: { traitId: 5, delta: 1.0 } },
      { text: '编为定本', gloss: '以定本为度', primary: { traitId: 5, delta: 0.6 } },
      { text: '传于百世', gloss: '以永为度', primary: { traitId: 5, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-018',
    format: 'situational',
    prompt: '同业之争',
    promptGloss: '同业相争，汝当如何？',
    options: [
      { text: '争而不让', gloss: '以争为度', primary: { traitId: 5, delta: -1.0 } },
      { text: '争而有节', gloss: '以节为度', primary: { traitId: 5, delta: -0.2 } },
      { text: '各守其界', gloss: '以不争为度', primary: { traitId: 5, delta: 0.4 } },
      { text: '合而为一', gloss: '以合为度', primary: { traitId: 5, delta: 1.0 } },
      { text: '共为一流', gloss: '以合为度', primary: { traitId: 5, delta: 1.2 } },
      { text: '立为公学', gloss: '以公为度', primary: { traitId: 5, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-019',
    format: 'imagery',
    prompt: '一灯与千灯',
    promptGloss: '一灯能照几隅？',
    options: [
      { text: '一隅', gloss: '以一为度', primary: { traitId: 5, delta: -0.8 } },
      { text: '一室', gloss: '以室为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '一城', gloss: '以城为度', primary: { traitId: 5, delta: 0.2 } },
      { text: '一国', gloss: '以国为度', primary: { traitId: 5, delta: 0.6 } },
      { text: '天下', gloss: '以天下为度', primary: { traitId: 5, delta: 1.0 } },
      { text: '万世', gloss: '以万世为度', primary: { traitId: 5, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-020',
    format: 'situational',
    prompt: '独学与共学',
    promptGloss: '为学当独，抑或共？',
    options: [
      { text: '独学', gloss: '以独为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '半独半共', gloss: '以中为度', primary: { traitId: 5, delta: 0.0 } },
      { text: '共学', gloss: '以共为度', primary: { traitId: 5, delta: 0.6 } },
      { text: '主共辅独', gloss: '以共为体', primary: { traitId: 5, delta: 1.0 } },
      { text: '立学以共', gloss: '以公为度', primary: { traitId: 5, delta: 1.2 } },
      { text: '天下共学', gloss: '以众为度', primary: { traitId: 5, delta: 1.4 } },
    ],
  },

  // ── T6 审美 ──
  {
    id: 'esci-021',
    format: 'imagery',
    prompt: '器之美',
    promptGloss: '器物之饰，汝取何格？',
    options: [
      { text: '无饰', gloss: '以朴为美', primary: { traitId: 6, delta: -1.0 } },
      { text: '质朴', gloss: '以素为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '清雅', gloss: '以清为美', primary: { traitId: 6, delta: 0.0 } },
      { text: '庄重', gloss: '以庄为美', primary: { traitId: 6, delta: 0.4 } },
      { text: '华美', gloss: '以华为美', primary: { traitId: 6, delta: 0.8 } },
      { text: '极丽', gloss: '以极为美', primary: { traitId: 6, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-022',
    format: 'situational',
    prompt: '匠意之传',
    promptGloss: '一器之成，汝欲其传何？',
    options: [
      { text: '传其用', gloss: '以用为传', primary: { traitId: 6, delta: -0.6 } },
      { text: '传其巧', gloss: '以巧为传', primary: { traitId: 6, delta: 0.0 } },
      { text: '传其理', gloss: '以理为传', primary: { traitId: 6, delta: 0.4 } },
      { text: '传其意', gloss: '以意为传', primary: { traitId: 6, delta: 0.8 } },
      { text: '传其美', gloss: '以美为传', primary: { traitId: 6, delta: 1.0 } },
      { text: '传其魂', gloss: '以魂为传', primary: { traitId: 6, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-023',
    format: 'situational',
    prompt: '图样之饰',
    promptGloss: '图样之绘，汝欲其繁简如何？',
    options: [
      { text: '极简', gloss: '以简为度', primary: { traitId: 6, delta: -0.8 } },
      { text: '简', gloss: '以简为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '适中', gloss: '以适为度', primary: { traitId: 6, delta: 0.0 } },
      { text: '繁', gloss: '以繁为度', primary: { traitId: 6, delta: 0.4 } },
      { text: '极繁', gloss: '以极为度', primary: { traitId: 6, delta: 1.0 } },
      { text: '繁而有序', gloss: '以序为度', primary: { traitId: 6, delta: 0.6 } },
    ],
  },
  {
    id: 'esci-024',
    format: 'imagery',
    prompt: '器之形',
    promptGloss: '器之形制，汝欲其何？',
    options: [
      { text: '天圆地方', gloss: '以古为度', primary: { traitId: 6, delta: -0.4 } },
      { text: '方正', gloss: '以正为度', primary: { traitId: 6, delta: -0.2 } },
      { text: '方圆兼备', gloss: '以兼为度', primary: { traitId: 6, delta: 0.2 } },
      { text: '圆融', gloss: '以圆为度', primary: { traitId: 6, delta: 0.4 } },
      { text: '流线', gloss: '以动为度', primary: { traitId: 6, delta: 0.8 } },
      { text: '极简极动', gloss: '以动为度', primary: { traitId: 6, delta: 1.2 } },
    ],
  },

  // ── T7 意志 ──
  {
    id: 'esci-025',
    format: 'situational',
    prompt: '千试不成',
    promptGloss: '千试而不成，汝当如何？',
    options: [
      { text: '止而不试', gloss: '以止为度', primary: { traitId: 7, delta: -1.2 } },
      { text: '改途以试', gloss: '以变为度', primary: { traitId: 7, delta: 0.0 } },
      { text: '稳步以试', gloss: '以稳为度', primary: { traitId: 7, delta: 0.4 } },
      { text: '百折不回', gloss: '以折为度', primary: { traitId: 7, delta: 1.0 } },
      { text: '死而后已', gloss: '以死为度', primary: { traitId: 7, delta: 1.4 } },
      { text: '以乐承苦', gloss: '以乐为度', primary: { traitId: 7, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-026',
    format: 'situational',
    prompt: '人讥汝拙',
    promptGloss: '众人讥汝拙，汝当如何？',
    options: [
      { text: '改弦易辙', gloss: '从众而止', primary: { traitId: 7, delta: -1.2 } },
      { text: '暂避其锋', gloss: '以避为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '徐徐以辩', gloss: '以辩为度', primary: { traitId: 7, delta: 0.0 } },
      { text: '自持以行', gloss: '以行为证', primary: { traitId: 7, delta: 0.8 } },
      { text: '以身为殉', gloss: '以死为度', primary: { traitId: 7, delta: 1.4 } },
      { text: '不辩不答', gloss: '以不答为度', primary: { traitId: 7, delta: 0.6 } },
    ],
  },
  {
    id: 'esci-027',
    format: 'imagery',
    prompt: '金刚石',
    promptGloss: '汝欲为何石？',
    options: [
      { text: '卵石', gloss: '以柔为度', primary: { traitId: 7, delta: -0.6 } },
      { text: '璞玉', gloss: '以潜为度', primary: { traitId: 7, delta: 0.2 } },
      { text: '青石', gloss: '以刚为度', primary: { traitId: 7, delta: 0.6 } },
      { text: '金刚石', gloss: '以极刚为度', primary: { traitId: 7, delta: 1.0 } },
      { text: '砺石', gloss: '以磨为度', primary: { traitId: 7, delta: 0.8 } },
      { text: '水晶', gloss: '以明为度', primary: { traitId: 7, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-028',
    format: 'situational',
    prompt: '穷途之叹',
    promptGloss: '穷途而道不行，汝何以自处？',
    options: [
      { text: '改道', gloss: '以变为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '独行', gloss: '以独为度', primary: { traitId: 7, delta: 0.6 } },
      { text: '传之于人', gloss: '以传为度', primary: { traitId: 7, delta: 1.0 } },
      { text: '著书立说', gloss: '以言为度', primary: { traitId: 7, delta: 1.2 } },
      { text: '死守', gloss: '以死为度', primary: { traitId: 7, delta: 1.4 } },
      { text: '退而传道', gloss: '以退为度', primary: { traitId: 7, delta: 0.8 } },
    ],
  },

  // ── T8 学识 ──
  {
    id: 'esci-029',
    format: 'situational',
    prompt: '学之博约',
    promptGloss: '学当博，抑或约？',
    options: [
      { text: '约', gloss: '以约为度', primary: { traitId: 8, delta: 0.4 } },
      { text: '半约半博', gloss: '以中为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '博', gloss: '以博为度', primary: { traitId: 8, delta: -0.4 } },
      { text: '由约入博', gloss: '以约始博终', primary: { traitId: 8, delta: 0.8 } },
      { text: '由博返约', gloss: '以博始约终', primary: { traitId: 8, delta: 1.0 } },
      { text: '博而能约', gloss: '以博约兼为度', primary: { traitId: 8, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-030',
    format: 'situational',
    prompt: '东西之学',
    promptGloss: '东西之学，汝取何为？',
    options: [
      { text: '唯中', gloss: '以中为度', primary: { traitId: 8, delta: -0.4 } },
      { text: '唯西', gloss: '以西为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '中主西辅', gloss: '以中为体', primary: { traitId: 8, delta: 0.6 } },
      { text: '西主中辅', gloss: '以西为体', primary: { traitId: 8, delta: 0.4 } },
      { text: '融贯东西', gloss: '以合为度', primary: { traitId: 8, delta: 1.0 } },
      { text: '合而立新', gloss: '以新为度', primary: { traitId: 8, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-031',
    format: 'imagery',
    prompt: '井与海',
    promptGloss: '汝欲为井，抑或海？',
    options: [
      { text: '井', gloss: '以井为度', primary: { traitId: 8, delta: -0.4 } },
      { text: '池', gloss: '以池为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '湖', gloss: '以湖为度', primary: { traitId: 8, delta: 0.4 } },
      { text: '江', gloss: '以江为度', primary: { traitId: 8, delta: 0.8 } },
      { text: '海', gloss: '以海为度', primary: { traitId: 8, delta: 1.0 } },
      { text: '海纳百川', gloss: '以纳为度', primary: { traitId: 8, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-032',
    format: 'situational',
    prompt: '通才与专才',
    promptGloss: '为学当通才，抑或专才？',
    options: [
      { text: '专才', gloss: '以专为度', primary: { traitId: 8, delta: 0.4 } },
      { text: '半专半通', gloss: '以中为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '通才', gloss: '以通为度', primary: { traitId: 8, delta: -0.4 } },
      { text: '由专入通', gloss: '以专始通终', primary: { traitId: 8, delta: 0.8 } },
      { text: '由通入专', gloss: '以通始专终', primary: { traitId: 8, delta: 1.0 } },
      { text: '专而能通', gloss: '以兼为度', primary: { traitId: 8, delta: 1.2 } },
    ],
  },

  // ── T9 处世 ──
  {
    id: 'esci-033',
    format: 'situational',
    prompt: '仕与隐',
    promptGloss: '才成之后，汝欲何往？',
    options: [
      { text: '出仕', gloss: '以进为度', primary: { traitId: 9, delta: -1.0 } },
      { text: '半仕半隐', gloss: '以中为度', primary: { traitId: 9, delta: 0.0 } },
      { text: '退而专学', gloss: '以退为度', primary: { traitId: 9, delta: 0.8 } },
      { text: '退而传学', gloss: '以传为度', primary: { traitId: 9, delta: 1.2 } },
      { text: '退而忘名', gloss: '以忘为度', primary: { traitId: 9, delta: 1.4 } },
      { text: '归田著书', gloss: '以终为度', primary: { traitId: 9, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-034',
    format: 'situational',
    prompt: '得志与失意',
    promptGloss: '得志则行，失意则隐，汝取何为？',
    options: [
      { text: '得志则行', gloss: '以得为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '得志亦止', gloss: '以止为度', primary: { traitId: 9, delta: 0.4 } },
      { text: '失意亦行', gloss: '以行为度', primary: { traitId: 9, delta: -0.6 } },
      { text: '行藏以时', gloss: '以时为度', primary: { traitId: 9, delta: 0.0 } },
      { text: '行藏由己', gloss: '以己为度', primary: { traitId: 9, delta: 1.0 } },
      { text: '行藏由道', gloss: '以道为度', primary: { traitId: 9, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-035',
    format: 'imagery',
    prompt: '舟与岸',
    promptGloss: '汝欲为舟，抑或岸？',
    options: [
      { text: '舟', gloss: '以行为度', primary: { traitId: 9, delta: -0.8 } },
      { text: '舴艋', gloss: '以小为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '帆', gloss: '以动为度', primary: { traitId: 9, delta: 0.0 } },
      { text: '岸', gloss: '以止为度', primary: { traitId: 9, delta: 0.6 } },
      { text: '灯塔', gloss: '以守为度', primary: { traitId: 9, delta: 1.0 } },
      { text: '岛屿', gloss: '以独为度', primary: { traitId: 9, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-036',
    format: 'situational',
    prompt: '身后之名',
    promptGloss: '身后之名，汝欲何为？',
    options: [
      { text: '不计', gloss: '以不名为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '求当世名', gloss: '以当世为度', primary: { traitId: 9, delta: -0.2 } },
      { text: '求百世名', gloss: '以百世为度', primary: { traitId: 9, delta: 0.4 } },
      { text: '求万世名', gloss: '以万世为度', primary: { traitId: 9, delta: 1.0 } },
      { text: '求千古名', gloss: '以千古为度', primary: { traitId: 9, delta: 1.4 } },
      { text: '以名为累', gloss: '以忘为度', primary: { traitId: 9, delta: -0.6 } },
    ],
  },

  // ── T10 时间 ──
  {
    id: 'esci-037',
    format: 'situational',
    prompt: '百代之功',
    promptGloss: '一理之成，可传百代，汝欲何用？',
    options: [
      { text: '急功', gloss: '以急为度', primary: { traitId: 10, delta: -1.0 } },
      { text: '十年', gloss: '以十为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '一世', gloss: '以一世为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '百世', gloss: '以百世为度', primary: { traitId: 10, delta: 0.6 } },
      { text: '万世', gloss: '以万世为度', primary: { traitId: 10, delta: 1.2 } },
      { text: '与天地齐', gloss: '以永为度', primary: { traitId: 10, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-038',
    format: 'situational',
    prompt: '一器与千代',
    promptGloss: '一器可传千代，汝欲为之乎？',
    options: [
      { text: '不传', gloss: '以一身为度', primary: { traitId: 10, delta: -1.0 } },
      { text: '传于子孙', gloss: '以家为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '传于当世', gloss: '以当世为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '传于百世', gloss: '以百世为度', primary: { traitId: 10, delta: 0.6 } },
      { text: '传于万世', gloss: '以万世为度', primary: { traitId: 10, delta: 1.0 } },
      { text: '与天地齐', gloss: '以永为度', primary: { traitId: 10, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-039',
    format: 'imagery',
    prompt: '寸阴与尺璧',
    promptGloss: '寸阴与尺璧，汝取何为贵？',
    options: [
      { text: '寸阴', gloss: '以寸阴为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '兼取', gloss: '以兼为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '尺璧', gloss: '以尺璧为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '古之所贵', gloss: '以古为度', primary: { traitId: 10, delta: 0.6 } },
      { text: '寸阴难买', gloss: '以难为度', primary: { traitId: 10, delta: 1.0 } },
      { text: '与化同流', gloss: '以化为度', primary: { traitId: 10, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-040',
    format: 'situational',
    prompt: '今与古',
    promptGloss: '今人之术，胜于古人乎？',
    options: [
      { text: '今胜古', gloss: '以今为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '古胜今', gloss: '以古为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '各有所长', gloss: '以兼为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '今为古继', gloss: '以继为度', primary: { traitId: 10, delta: 0.6 } },
      { text: '古为今基', gloss: '以基为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '与化同新', gloss: '以化为度', primary: { traitId: 10, delta: 1.4 } },
    ],
  },

  // ── T11 风险 ──
  {
    id: 'esci-041',
    format: 'situational',
    prompt: '未验之器',
    promptGloss: '一器未验，汝敢用之乎？',
    options: [
      { text: '不敢', gloss: '以不为度', primary: { traitId: 11, delta: -1.2 } },
      { text: '小试之', gloss: '以试为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '半用半试', gloss: '以中为度', primary: { traitId: 11, delta: 0.0 } },
      { text: '敢用之', gloss: '以敢为度', primary: { traitId: 11, delta: 0.6 } },
      { text: '以身为试', gloss: '以身为度', primary: { traitId: 11, delta: 1.0 } },
      { text: '以死为度', gloss: '以死为度', primary: { traitId: 11, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-042',
    format: 'situational',
    prompt: '以身为验',
    promptGloss: '欲验新药，汝以何为试？',
    options: [
      { text: '不敢试', gloss: '不涉险', primary: { traitId: 11, delta: -1.2 } },
      { text: '以物试', gloss: '以物为度', primary: { traitId: 11, delta: -0.6 } },
      { text: '以兽试', gloss: '以兽为度', primary: { traitId: 11, delta: -0.2 } },
      { text: '以己试', gloss: '以己为度', primary: { traitId: 11, delta: 0.8 } },
      { text: '以亲属试', gloss: '以亲为度', primary: { traitId: 11, delta: 0.4 } },
      { text: '以身为殉', gloss: '以死为度', primary: { traitId: 11, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-043',
    format: 'imagery',
    prompt: '孤舟与巨浪',
    promptGloss: '新理如孤舟入海，汝何以对？',
    options: [
      { text: '不渡', gloss: '以不渡为度', primary: { traitId: 11, delta: -1.2 } },
      { text: '近岸行', gloss: '以近为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '半海', gloss: '以中为度', primary: { traitId: 11, delta: 0.0 } },
      { text: '远航', gloss: '以远为度', primary: { traitId: 11, delta: 0.6 } },
      { text: '穷海', gloss: '以穷为度', primary: { traitId: 11, delta: 1.0 } },
      { text: '与海同化', gloss: '以化为度', primary: { traitId: 11, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-044',
    format: 'situational',
    prompt: '新术之争',
    promptGloss: '新术一立，旧派阻之，汝当如何？',
    options: [
      { text: '退让', gloss: '以让为度', primary: { traitId: 11, delta: -1.0 } },
      { text: '婉转', gloss: '以婉为度', primary: { traitId: 11, delta: -0.2 } },
      { text: '稳进', gloss: '以稳为度', primary: { traitId: 11, delta: 0.4 } },
      { text: '强推', gloss: '以强为度', primary: { traitId: 11, delta: 1.0 } },
      { text: '以死争之', gloss: '以死为度', primary: { traitId: 11, delta: 1.4 } },
      { text: '以行证之', gloss: '以行为度', primary: { traitId: 11, delta: 0.6 } },
    ],
  },

  // ── T12 表达 ──
  {
    id: 'esci-045',
    format: 'situational',
    prompt: '一理之传',
    promptGloss: '一理已成，汝欲何传？',
    options: [
      { text: '默而不宣', gloss: '以默为度', primary: { traitId: 12, delta: -1.0 } },
      { text: '口传', gloss: '以口为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '笔传', gloss: '以笔为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '图传', gloss: '以图为度', primary: { traitId: 12, delta: 0.4 } },
      { text: '器传', gloss: '以器为度', primary: { traitId: 12, delta: 0.8 } },
      { text: '数传', gloss: '以数为度', primary: { traitId: 12, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-046',
    format: 'situational',
    prompt: '著书之辞',
    promptGloss: '著书之辞，汝取何格？',
    options: [
      { text: '极简', gloss: '以简为度', primary: { traitId: 12, delta: -0.8 } },
      { text: '简', gloss: '以简为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '适', gloss: '以适为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '繁', gloss: '以繁为度', primary: { traitId: 12, delta: 0.4 } },
      { text: '极繁', gloss: '以繁为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '图穷匕见', gloss: '以图为度', primary: { traitId: 12, delta: 0.6 } },
    ],
  },
  {
    id: 'esci-047',
    format: 'imagery',
    prompt: '言之器',
    promptGloss: '传理之器，汝欲何为？',
    options: [
      { text: '口耳', gloss: '以口为度', primary: { traitId: 12, delta: -1.0 } },
      { text: '竹简', gloss: '以简为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '书', gloss: '以书为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '图', gloss: '以图为度', primary: { traitId: 12, delta: 0.6 } },
      { text: '式', gloss: '以式为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '模', gloss: '以模为度', primary: { traitId: 12, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-048',
    format: 'situational',
    prompt: '万言之传',
    promptGloss: '一理之传，汝欲万言以传，抑或千言以传？',
    options: [
      { text: '千言', gloss: '以千为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '半千', gloss: '以半为度', primary: { traitId: 12, delta: -0.6 } },
      { text: '百言', gloss: '以百为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '十言', gloss: '以十为度', primary: { traitId: 12, delta: 0.4 } },
      { text: '一言', gloss: '以一为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '无言', gloss: '以不立为度', primary: { traitId: 12, delta: 1.4 } },
    ],
  },
];
