// 镜心 · 文哲巨擘（西方）· 48 题
// 12 维 × 4 题；侧重思辨 / 表达 / 意志 / 革新的哲学语感

import type { Item } from './item.types';

export const ITEMS_WEST_PHILOSOPHER: readonly Item[] = [
  // ── T1 思辨 ──
  {
    id: 'wp-001',
    format: 'situational',
    prompt: '真理之问',
    promptGloss: '逢众说纷纭，汝何以探其真？',
    options: [
      { text: '听而不问', gloss: '以知足为度', primary: { traitId: 1, delta: -1.2 } },
      { text: '援古为证', gloss: '以旧释新', primary: { traitId: 1, delta: -0.4 }, secondary: [{ traitId: 8, delta: 0.3 }] },
      { text: '兼听而择', gloss: '折衷取中', primary: { traitId: 1, delta: 0.2 } },
      { text: '步步推演', gloss: '以理为度', primary: { traitId: 1, delta: 1.0 }, secondary: [{ traitId: 8, delta: 0.4 }] },
      { text: '直指本心', gloss: '以悟为知', primary: { traitId: 1, delta: 0.4 }, secondary: [{ traitId: 6, delta: 0.4 }] },
      { text: '穷理至极', gloss: '形而上之', primary: { traitId: 1, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-002',
    format: 'situational',
    prompt: '普遍怀疑',
    promptGloss: '若一切皆可疑，汝如何立足？',
    options: [
      { text: '依于信仰', gloss: '以信而立', primary: { traitId: 1, delta: -1.2 } },
      { text: '凭于经验', gloss: '以验为实', primary: { traitId: 1, delta: -0.4 }, secondary: [{ traitId: 3, delta: 0.3 }] },
      { text: '赖于常识', gloss: '以常为度', primary: { traitId: 1, delta: 0.0 } },
      { text: '思于「我思」', gloss: '笛卡尔之径', primary: { traitId: 1, delta: 1.0 } },
      { text: '存于「彼在」', gloss: '海德格尔之径', primary: { traitId: 1, delta: 1.2 }, secondary: [{ traitId: 9, delta: 0.4 }] },
      { text: '毁于无根', gloss: '破而不立', primary: { traitId: 1, delta: 1.4 }, secondary: [{ traitId: 4, delta: 0.4 }] },
    ],
  },
  {
    id: 'wp-003',
    format: 'imagery',
    prompt: '洞穴之光',
    promptGloss: '汝居于可见之影，抑或奔向可知之光？',
    options: [
      { text: '安于影中', gloss: '不求其上', primary: { traitId: 1, delta: -1.2 } },
      { text: '偶窥其光', gloss: '半醒半寐', primary: { traitId: 1, delta: -0.4 } },
      { text: '知其有光', gloss: '知而未往', primary: { traitId: 1, delta: 0.0 } },
      { text: '转身向光', gloss: '知而求之', primary: { traitId: 1, delta: 1.0 } },
      { text: '出洞穴', gloss: '柏拉图之径', primary: { traitId: 1, delta: 1.2 }, secondary: [{ traitId: 4, delta: 0.4 }] },
      { text: '反身救人', gloss: '由明返暗', primary: { traitId: 1, delta: 1.4 }, secondary: [{ traitId: 5, delta: 0.4 }] },
    ],
  },
  {
    id: 'wp-004',
    format: 'situational',
    prompt: '抽象与具体',
    promptGloss: '汝更信何种思维？',
    options: [
      { text: '唯具体', gloss: '以触为真', primary: { traitId: 1, delta: -1.4 } },
      { text: '重具体', gloss: '以验为基', primary: { traitId: 1, delta: -0.6 } },
      { text: '兼取之', gloss: '相辅为用', primary: { traitId: 1, delta: 0.0 } },
      { text: '重抽象', gloss: '以理为度', primary: { traitId: 1, delta: 0.6 } },
      { text: '唯抽象', gloss: '形而上之', primary: { traitId: 1, delta: 1.2 } },
      { text: '形而上之', gloss: '以绝对为度', primary: { traitId: 1, delta: 1.4 } },
    ],
  },

  // ── T2 情感 ──
  {
    id: 'wp-005',
    format: 'situational',
    prompt: '激情与节制',
    promptGloss: '汝于情感，倾于何端？',
    options: [
      { text: '以智节情', gloss: '斯多葛之径', primary: { traitId: 2, delta: -1.0 } },
      { text: '静多于动', gloss: '以静为度', primary: { traitId: 2, delta: -0.4 } },
      { text: '不偏不倚', gloss: '执两用中', primary: { traitId: 2, delta: 0.0 } },
      { text: '动多于静', gloss: '以情为真', primary: { traitId: 2, delta: 0.6 } },
      { text: '纵情而往', gloss: '以情为道', primary: { traitId: 2, delta: 1.0 } },
      { text: '酒神之醉', gloss: '尼采之径', primary: { traitId: 2, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-006',
    format: 'situational',
    prompt: '哀人之死',
    promptGloss: '闻至亲之丧，汝当如何？',
    options: [
      { text: '哀而不泣', gloss: '以理节哀', primary: { traitId: 2, delta: -1.2 } },
      { text: '数日即止', gloss: '以时为度', primary: { traitId: 2, delta: -0.4 } },
      { text: '因人而异', gloss: '不强一律', primary: { traitId: 2, delta: 0.0 } },
      { text: '哀毁骨立', gloss: '以情为礼', primary: { traitId: 2, delta: 0.8 } },
      { text: '久难自已', gloss: '以情为真', primary: { traitId: 2, delta: 1.2 } },
      { text: '不泣而歌', gloss: '以悟度情', primary: { traitId: 2, delta: 1.4 }, secondary: [{ traitId: 9, delta: 0.4 }] },
    ],
  },
  {
    id: 'wp-007',
    format: 'imagery',
    prompt: '冷月与烈火',
    promptGloss: '汝之心性，更近何象？',
    options: [
      { text: '寒冰', gloss: '以冷为度', primary: { traitId: 2, delta: -1.2 } },
      { text: '冷月', gloss: '清而不热', primary: { traitId: 2, delta: -0.6 } },
      { text: '晨光', gloss: '温而不烈', primary: { traitId: 2, delta: 0.0 } },
      { text: '炉火', gloss: '温而持久', primary: { traitId: 2, delta: 0.6 } },
      { text: '烈焰', gloss: '以热为真', primary: { traitId: 2, delta: 1.2 } },
      { text: '火山', gloss: '以炽为道', primary: { traitId: 2, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-008',
    format: 'situational',
    prompt: '爱之形',
    promptGloss: '汝之爱，更倾何方？',
    options: [
      { text: '智性之爱', gloss: '柏拉图之径', primary: { traitId: 2, delta: -0.6 }, secondary: [{ traitId: 1, delta: 0.4 }] },
      { text: '友爱之爱', gloss: '亚里士多德之径', primary: { traitId: 2, delta: 0.0 }, secondary: [{ traitId: 5, delta: 0.3 }] },
      { text: '怜悯之爱', gloss: '以慈为度', primary: { traitId: 2, delta: 0.6 }, secondary: [{ traitId: 5, delta: 0.3 }] },
      { text: '激情之爱', gloss: '以恋为真', primary: { traitId: 2, delta: 1.0 } },
      { text: '忘我之爱', gloss: '以舍为度', primary: { traitId: 2, delta: 1.2 } },
      { text: '神性之爱', gloss: '以圣为度', primary: { traitId: 2, delta: 1.4 }, secondary: [{ traitId: 9, delta: 0.4 }] },
    ],
  },

  // ── T3 行动 ──
  {
    id: 'wp-009',
    format: 'situational',
    prompt: '静观与介入',
    promptGloss: '逢世之不义，汝当如何？',
    options: [
      { text: '静观其变', gloss: '斯多葛之径', primary: { traitId: 3, delta: -1.2 } },
      { text: '退而自修', gloss: '以修为本', primary: { traitId: 3, delta: -0.4 } },
      { text: '援笔而论', gloss: '以言代行', primary: { traitId: 3, delta: 0.0 }, secondary: [{ traitId: 12, delta: 0.3 }] },
      { text: '立言以唤', gloss: '启蒙之径', primary: { traitId: 3, delta: 0.8 }, secondary: [{ traitId: 12, delta: 0.4 }] },
      { text: '奋起而行', gloss: '革命之径', primary: { traitId: 3, delta: 1.2 } },
      { text: '以身殉道', gloss: '死生以之', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-010',
    format: 'situational',
    prompt: '时机之问',
    promptGloss: '机不可失，汝如何行？',
    options: [
      { text: '待其自至', gloss: '以静为度', primary: { traitId: 3, delta: -1.0 } },
      { text: '徐徐待之', gloss: '不争于时', primary: { traitId: 3, delta: -0.4 } },
      { text: '从容而行', gloss: '不急不缓', primary: { traitId: 3, delta: 0.2 } },
      { text: '即断即行', gloss: '雷厉风行', primary: { traitId: 3, delta: 1.0 }, secondary: [{ traitId: 7, delta: 0.3 }] },
      { text: '先发制人', gloss: '主动而出', primary: { traitId: 3, delta: 1.2 } },
      { text: '当机立断', gloss: '不容犹豫', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-011',
    format: 'imagery',
    prompt: '雷厉风行',
    promptGloss: '思想者之于行动，更近何象？',
    options: [
      { text: '静水', gloss: '以静为深', primary: { traitId: 3, delta: -0.8 } },
      { text: '缓流', gloss: '以缓为度', primary: { traitId: 3, delta: -0.2 } },
      { text: '常流', gloss: '以常为节', primary: { traitId: 3, delta: 0.2 } },
      { text: '疾风', gloss: '以疾为节', primary: { traitId: 3, delta: 0.8 } },
      { text: '雷霆', gloss: '以雷为节', primary: { traitId: 3, delta: 1.2 } },
      { text: '闪电', gloss: '一击即发', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-012',
    format: 'situational',
    prompt: '思与行',
    promptGloss: '思久而不行，汝当何为？',
    options: [
      { text: '不求行', gloss: '以思为足', primary: { traitId: 3, delta: -1.2 } },
      { text: '思而不倦', gloss: '以思为道', primary: { traitId: 3, delta: -0.4 }, secondary: [{ traitId: 1, delta: 0.3 }] },
      { text: '思而时行', gloss: '以时为度', primary: { traitId: 3, delta: 0.2 } },
      { text: '行而不怠', gloss: '以行为真', primary: { traitId: 3, delta: 1.0 } },
      { text: '先行后思', gloss: '以行证思', primary: { traitId: 3, delta: 1.2 } },
      { text: '即思即行', gloss: '思行合一', primary: { traitId: 3, delta: 1.4 } },
    ],
  },

  // ── T4 革新 ──
  {
    id: 'wp-013',
    format: 'situational',
    prompt: '传统之惑',
    promptGloss: '旧制百年，弊已显，汝当变否？',
    options: [
      { text: '坚守祖制', gloss: '不可动摇', primary: { traitId: 4, delta: -1.4 } },
      { text: '小修小补', gloss: '渐改', primary: { traitId: 4, delta: -0.6 } },
      { text: '择其善者', gloss: '去取之间', primary: { traitId: 4, delta: 0.0 } },
      { text: '根本重估', gloss: '尼采之径', primary: { traitId: 4, delta: 1.0 } },
      { text: '破旧立新', gloss: '以变为常', primary: { traitId: 4, delta: 1.4 } },
      { text: '凤凰涅槃', gloss: '毁而重生', primary: { traitId: 4, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-014',
    format: 'situational',
    prompt: '权威之问',
    promptGloss: '若师之所传与己见相悖，汝当如何？',
    options: [
      { text: '从师如父', gloss: '以师为天', primary: { traitId: 4, delta: -1.4 } },
      { text: '听其大端', gloss: '不强求全', primary: { traitId: 4, delta: -0.4 } },
      { text: '存而不论', gloss: '不评其短', primary: { traitId: 4, delta: 0.0 } },
      { text: '友爱吾师', gloss: '亚里士多德之径', primary: { traitId: 4, delta: 0.8 }, secondary: [{ traitId: 1, delta: 0.3 }] },
      { text: '但求真理', gloss: '真理至上', primary: { traitId: 4, delta: 1.2 } },
      { text: '自立法度', gloss: '自我立法', primary: { traitId: 4, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-015',
    format: 'imagery',
    prompt: '新瓶与旧酒',
    promptGloss: '汝更倾何喻？',
    options: [
      { text: '唯旧', gloss: '以古为美', primary: { traitId: 4, delta: -1.2 } },
      { text: '旧主新辅', gloss: '以古为体', primary: { traitId: 4, delta: -0.4 } },
      { text: '新旧并存', gloss: '相辅相成', primary: { traitId: 4, delta: 0.2 } },
      { text: '新主旧辅', gloss: '以新为用', primary: { traitId: 4, delta: 0.8 } },
      { text: '唯新', gloss: '以新为美', primary: { traitId: 4, delta: 1.2 } },
      { text: '破瓶', gloss: '不立任何', primary: { traitId: 4, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-016',
    format: 'situational',
    prompt: '破神之问',
    promptGloss: '若神已死，汝将何以立？',
    options: [
      { text: '神永在', gloss: '信而不疑', primary: { traitId: 4, delta: -1.4 } },
      { text: '神虽死', gloss: '道德不泯', primary: { traitId: 4, delta: -0.4 } },
      { text: '以礼代神', gloss: '以俗为度', primary: { traitId: 4, delta: 0.0 } },
      { text: '自我立法', gloss: '尼采之径', primary: { traitId: 4, delta: 1.0 } },
      { text: '超人而出', gloss: '以超人为本', primary: { traitId: 4, delta: 1.2 } },
      { text: '重估一切', gloss: '以锤为准', primary: { traitId: 4, delta: 1.4 } },
    ],
  },

  // ── T5 群我 ──
  {
    id: 'wp-017',
    format: 'situational',
    prompt: '我与众人',
    promptGloss: '汝之思，更近于独白，抑或对话？',
    options: [
      { text: '唯我', gloss: '以己为度', primary: { traitId: 5, delta: -1.2 } },
      { text: '自多于群', gloss: '以己为先', primary: { traitId: 5, delta: -0.4 } },
      { text: '可群可我', gloss: '因事而异', primary: { traitId: 5, delta: 0.2 } },
      { text: '群我相融', gloss: '交互主体', primary: { traitId: 5, delta: 0.8 } },
      { text: '以群为本', gloss: '以共为度', primary: { traitId: 5, delta: 1.2 } },
      { text: '为他者', gloss: '列维纳斯之径', primary: { traitId: 5, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-018',
    format: 'situational',
    prompt: '公共之言',
    promptGloss: '汝之论说，更近独白抑或商议？',
    options: [
      { text: '独白', gloss: '以己为真', primary: { traitId: 5, delta: -1.2 } },
      { text: '小众之论', gloss: '以同好为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '以言会友', gloss: '以友为度', primary: { traitId: 5, delta: 0.2 } },
      { text: '公共商议', gloss: '哈贝马斯之径', primary: { traitId: 5, delta: 0.8 } },
      { text: '为众立言', gloss: '以民为度', primary: { traitId: 5, delta: 1.2 } },
      { text: '为人类立言', gloss: '以人为度', primary: { traitId: 5, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-019',
    format: 'imagery',
    prompt: '独木与森林',
    promptGloss: '哲学者于世，更近何象？',
    options: [
      { text: '独木', gloss: '以一为度', primary: { traitId: 5, delta: -1.2 } },
      { text: '双木', gloss: '以友为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '木与林', gloss: '兼己与群', primary: { traitId: 5, delta: 0.2 } },
      { text: '森林', gloss: '以群为度', primary: { traitId: 5, delta: 0.8 } },
      { text: '众生一体', gloss: '以共为度', primary: { traitId: 5, delta: 1.2 } },
      { text: '万物相连', gloss: '以通为度', primary: { traitId: 5, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-020',
    format: 'situational',
    prompt: '启蒙之任',
    promptGloss: '若世人蒙昧，汝当如何？',
    options: [
      { text: '听其自然', gloss: '不强为人', primary: { traitId: 5, delta: -1.2 } },
      { text: '独善其身', gloss: '以己为足', primary: { traitId: 5, delta: -0.4 } },
      { text: '随缘而教', gloss: '不求广度', primary: { traitId: 5, delta: 0.0 } },
      { text: '立说传道', gloss: '以教为度', primary: { traitId: 5, delta: 0.8 } },
      { text: '开启民智', gloss: '启蒙之径', primary: { traitId: 5, delta: 1.2 } },
      { text: '为万世开太平', gloss: '以永为度', primary: { traitId: 5, delta: 1.4 } },
    ],
  },

  // ── T6 审美 ──
  {
    id: 'wp-021',
    format: 'imagery',
    prompt: '美之所向',
    promptGloss: '美之于汝，更近何象？',
    options: [
      { text: '几何', gloss: '以数为美', primary: { traitId: 6, delta: -1.0 } },
      { text: '对称', gloss: '以序为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '和谐', gloss: '以中为美', primary: { traitId: 6, delta: 0.0 } },
      { text: '崇高', gloss: '以大为美', primary: { traitId: 6, delta: 0.8 } },
      { text: '悲剧', gloss: '以痛为美', primary: { traitId: 6, delta: 1.2 } },
      { text: '荒诞', gloss: '加缪之径', primary: { traitId: 6, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-022',
    format: 'situational',
    prompt: '艺术之问',
    promptGloss: '艺术何以为真？',
    options: [
      { text: '模仿', gloss: '以摹为真', primary: { traitId: 6, delta: -1.0 } },
      { text: '再现', gloss: '以映为真', primary: { traitId: 6, delta: -0.4 } },
      { text: '表现', gloss: '以表为真', primary: { traitId: 6, delta: 0.0 } },
      { text: '形式', gloss: '以形为真', primary: { traitId: 6, delta: 0.6 } },
      { text: '灵韵', gloss: '本雅明之径', primary: { traitId: 6, delta: 1.0 } },
      { text: '美为无目的', gloss: '康德之径', primary: { traitId: 6, delta: 1.2 } },
    ],
  },
  {
    id: 'wp-023',
    format: 'situational',
    prompt: '美与善',
    promptGloss: '美与善，孰先？',
    options: [
      { text: '善先', gloss: '以善为度', primary: { traitId: 6, delta: -1.0 } },
      { text: '善主美辅', gloss: '以善为体', primary: { traitId: 6, delta: -0.4 } },
      { text: '相辅', gloss: '兼美与善', primary: { traitId: 6, delta: 0.2 } },
      { text: '美主善辅', gloss: '以美为体', primary: { traitId: 6, delta: 0.6 } },
      { text: '美先', gloss: '以美为度', primary: { traitId: 6, delta: 1.2 } },
      { text: '美善合一', gloss: '柏拉图之径', primary: { traitId: 6, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-024',
    format: 'imagery',
    prompt: '音乐之境',
    promptGloss: '听乐，汝更入何境？',
    options: [
      { text: '寂', gloss: '以静为度', primary: { traitId: 6, delta: -1.0 } },
      { text: '净', gloss: '以纯为度', primary: { traitId: 6, delta: -0.4 } },
      { text: '和', gloss: '以和为度', primary: { traitId: 6, delta: 0.0 } },
      { text: '壮', gloss: '以壮为度', primary: { traitId: 6, delta: 0.6 } },
      { text: '悲', gloss: '以悲为度', primary: { traitId: 6, delta: 1.0 } },
      { text: '醉', gloss: '以醉为度', primary: { traitId: 6, delta: 1.2 } },
    ],
  },

  // ── T7 意志 ──
  {
    id: 'wp-025',
    format: 'situational',
    prompt: '逆境之问',
    promptGloss: '逢至暗时刻，汝何以自处？',
    options: [
      { text: '顺而从之', gloss: '以顺为度', primary: { traitId: 7, delta: -1.4 } },
      { text: '隐忍待时', gloss: '以待为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '不偏不倚', gloss: '以中为度', primary: { traitId: 7, delta: 0.0 } },
      { text: '愈挫愈坚', gloss: '以刚为度', primary: { traitId: 7, delta: 1.0 } },
      { text: '以死明志', gloss: '以死为度', primary: { traitId: 7, delta: 1.4 } },
      { text: '死生如一', gloss: '以一为度', primary: { traitId: 7, delta: 1.2 } },
    ],
  },
  {
    id: 'wp-026',
    format: 'situational',
    prompt: '孤独之问',
    promptGloss: '众人皆醉，汝独醒，何以处？',
    options: [
      { text: '随之而醉', gloss: '以同为度', primary: { traitId: 7, delta: -1.4 } },
      { text: '随而不醉', gloss: '以同为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '不与争', gloss: '不与之较', primary: { traitId: 7, delta: 0.0 } },
      { text: '独守其明', gloss: '以独为度', primary: { traitId: 7, delta: 0.8 } },
      { text: '劝之使醒', gloss: '苏格拉底之径', primary: { traitId: 7, delta: 1.0 } },
      { text: '以死殉道', gloss: '以死为度', primary: { traitId: 7, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-027',
    format: 'imagery',
    prompt: '命运之绳',
    promptGloss: '意志之于命运，汝更信何方？',
    options: [
      { text: '唯命运', gloss: '以命为度', primary: { traitId: 7, delta: -1.4 } },
      { text: '命主志辅', gloss: '以命为体', primary: { traitId: 7, delta: -0.4 } },
      { text: '相半', gloss: '以半为度', primary: { traitId: 7, delta: 0.0 } },
      { text: '志主命辅', gloss: '以志为体', primary: { traitId: 7, delta: 0.8 } },
      { text: '唯意志', gloss: '叔本华之径', primary: { traitId: 7, delta: 1.2 } },
      { text: '超善恶', gloss: '尼采之径', primary: { traitId: 7, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-028',
    format: 'situational',
    prompt: '信与疑',
    promptGloss: '当理性之穷处，汝何以立？',
    options: [
      { text: '只信理', gloss: '以理为度', primary: { traitId: 7, delta: -1.0 } },
      { text: '信多于疑', gloss: '以信为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '因事而择', gloss: '不强求', primary: { traitId: 7, delta: 0.0 } },
      { text: '信而有疑', gloss: '以诚为度', primary: { traitId: 7, delta: 0.6 } },
      { text: '信仰之跃', gloss: '克尔凯郭尔之径', primary: { traitId: 7, delta: 1.2 } },
      { text: '信而无疑', gloss: '以信为真', primary: { traitId: 7, delta: 1.4 } },
    ],
  },

  // ── T8 学识 ──
  {
    id: 'wp-029',
    format: 'situational',
    prompt: '学问之径',
    promptGloss: '汝之学，更重何种方法？',
    options: [
      { text: '唯经验', gloss: '以验为度', primary: { traitId: 8, delta: -1.0 } },
      { text: '经验为主', gloss: '以验为体', primary: { traitId: 8, delta: -0.4 } },
      { text: '兼取之', gloss: '相辅为用', primary: { traitId: 8, delta: 0.0 } },
      { text: '理性为主', gloss: '以理为体', primary: { traitId: 8, delta: 0.8 } },
      { text: '唯理性', gloss: '笛卡尔之径', primary: { traitId: 8, delta: 1.2 } },
      { text: '先验与经验合', gloss: '康德之径', primary: { traitId: 8, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-030',
    format: 'situational',
    prompt: '一专与博学',
    promptGloss: '汝之学，更倾一端抑或广博？',
    options: [
      { text: '唯专一', gloss: '以专为本', primary: { traitId: 8, delta: -0.6 } },
      { text: '专一为主', gloss: '以专为体', primary: { traitId: 8, delta: 0.0 } },
      { text: '兼取之', gloss: '专博相辅', primary: { traitId: 8, delta: 0.4 } },
      { text: '广博为主', gloss: '以博为体', primary: { traitId: 8, delta: 0.8 } },
      { text: '唯博学', gloss: '以博为度', primary: { traitId: 8, delta: 1.0 } },
      { text: '哲学为王', gloss: '以哲为度', primary: { traitId: 8, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-031',
    format: 'imagery',
    prompt: '学问之器',
    promptGloss: '学问之于汝，更近何器？',
    options: [
      { text: '井水', gloss: '一隅之知', primary: { traitId: 8, delta: -0.8 } },
      { text: '溪流', gloss: '日积月累', primary: { traitId: 8, delta: -0.2 } },
      { text: '江河', gloss: '以学为江', primary: { traitId: 8, delta: 0.4 } },
      { text: '大江', gloss: '以学为大', primary: { traitId: 8, delta: 0.8 } },
      { text: '海洋', gloss: '以学为海', primary: { traitId: 8, delta: 1.2 } },
      { text: '海与天空', gloss: '以学为天', primary: { traitId: 8, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-032',
    format: 'situational',
    prompt: '学以致用',
    promptGloss: '学问为天下，抑为个人？',
    options: [
      { text: '不求用', gloss: '以知为足', primary: { traitId: 8, delta: -0.8 } },
      { text: '自修而已', gloss: '以己为度', primary: { traitId: 8, delta: -0.4 } },
      { text: '自用而已', gloss: '以用为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '以学为用', gloss: '培根之径', primary: { traitId: 8, delta: 0.6 } },
      { text: '为人类谋', gloss: '以人为度', primary: { traitId: 8, delta: 1.0 } },
      { text: '为天下立法', gloss: '以法为度', primary: { traitId: 8, delta: 1.2 } },
    ],
  },

  // ── T9 处世 ──
  {
    id: 'wp-033',
    format: 'situational',
    prompt: '入世与退隐',
    promptGloss: '哲学者于世，汝更倾何端？',
    options: [
      { text: '积极入世', gloss: '以进为度', primary: { traitId: 9, delta: -1.4 } },
      { text: '略有介入', gloss: '以进为体', primary: { traitId: 9, delta: -0.4 } },
      { text: '不偏不倚', gloss: '不求甚深', primary: { traitId: 9, delta: 0.2 } },
      { text: '小隐于市', gloss: '以隐为度', primary: { traitId: 9, delta: 0.8 } },
      { text: '大隐于野', gloss: '以野为度', primary: { traitId: 9, delta: 1.2 } },
      { text: '唯退而思', gloss: '以退为度', primary: { traitId: 9, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-034',
    format: 'situational',
    prompt: '权贵之问',
    promptGloss: '若权者招饮，汝当如何？',
    options: [
      { text: '欣然赴之', gloss: '以进为度', primary: { traitId: 9, delta: -1.4 } },
      { text: '偶一为之', gloss: '以进为体', primary: { traitId: 9, delta: -0.4 } },
      { text: '不拒不迎', gloss: '以中为度', primary: { traitId: 9, delta: 0.2 } },
      { text: '以言为度', gloss: '以言为度', primary: { traitId: 9, delta: 0.8 } },
      { text: '拒而守之', gloss: '以守为度', primary: { traitId: 9, delta: 1.2 } },
      { text: '远而不交', gloss: '以远为度', primary: { traitId: 9, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-035',
    format: 'imagery',
    prompt: '塔与井',
    promptGloss: '思想者于世，更近何象？',
    options: [
      { text: '井底', gloss: '以深为度', primary: { traitId: 9, delta: -1.4 } },
      { text: '井中', gloss: '以中为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '平地', gloss: '以平为度', primary: { traitId: 9, delta: 0.2 } },
      { text: '塔下', gloss: '以立为度', primary: { traitId: 9, delta: 0.8 } },
      { text: '塔中', gloss: '以望为度', primary: { traitId: 9, delta: 1.2 } },
      { text: '塔顶', gloss: '以高为度', primary: { traitId: 9, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-036',
    format: 'situational',
    prompt: '盛年与暮年',
    promptGloss: '盛年已过，汝欲何为？',
    options: [
      { text: '老骥伏枥', gloss: '以志为老', primary: { traitId: 9, delta: -1.0 } },
      { text: '仍有所为', gloss: '以行为老', primary: { traitId: 9, delta: -0.4 } },
      { text: '不急不缓', gloss: '以中为度', primary: { traitId: 9, delta: 0.2 } },
      { text: '退而思之', gloss: '以退为老', primary: { traitId: 9, delta: 0.8 } },
      { text: '传道授业', gloss: '以传为老', primary: { traitId: 9, delta: 1.2 } },
      { text: '归于无言', gloss: '以无言之', primary: { traitId: 9, delta: 1.4 } },
    ],
  },

  // ── T10 时间 ──
  {
    id: 'wp-037',
    format: 'situational',
    prompt: '永恒与当下',
    promptGloss: '汝之思，更倾永恒抑或当下？',
    options: [
      { text: '唯当下', gloss: '以今为度', primary: { traitId: 10, delta: -1.4 } },
      { text: '当下为主', gloss: '以今为体', primary: { traitId: 10, delta: -0.4 } },
      { text: '兼取之', gloss: '今永相辅', primary: { traitId: 10, delta: 0.0 } },
      { text: '永恒为主', gloss: '以永为体', primary: { traitId: 10, delta: 0.8 } },
      { text: '唯永恒', gloss: '柏拉图之径', primary: { traitId: 10, delta: 1.2 } },
      { text: '永恒轮回', gloss: '尼采之径', primary: { traitId: 10, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-038',
    format: 'situational',
    prompt: '历史之问',
    promptGloss: '汝于历史，更信何方？',
    options: [
      { text: '循环', gloss: '以环为度', primary: { traitId: 10, delta: -0.8 } },
      { text: '渐退', gloss: '以退为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '演进', gloss: '以进为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '辩证', gloss: '黑格尔之径', primary: { traitId: 10, delta: 0.8 } },
      { text: '断裂', gloss: '以断为度', primary: { traitId: 10, delta: 1.0 } },
      { text: '终结', gloss: '以末为度', primary: { traitId: 10, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-039',
    format: 'imagery',
    prompt: '时间之问',
    promptGloss: '汝之时间，更近何喻？',
    options: [
      { text: '直线', gloss: '以直为度', primary: { traitId: 10, delta: -0.8 } },
      { text: '流水', gloss: '以流为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '绵延', gloss: '柏格森之径', primary: { traitId: 10, delta: 0.6 } },
      { text: '圆环', gloss: '以环为度', primary: { traitId: 10, delta: 1.0 } },
      { text: '星丛', gloss: '本雅明之径', primary: { traitId: 10, delta: 1.2 } },
      { text: '永恒之今', gloss: '奥古斯丁之径', primary: { traitId: 10, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-040',
    format: 'situational',
    prompt: '身后之名',
    promptGloss: '身后之名，汝欲何为？',
    options: [
      { text: '不计身后', gloss: '以生为度', primary: { traitId: 10, delta: -1.2 } },
      { text: '随其自至', gloss: '不求之', primary: { traitId: 10, delta: -0.4 } },
      { text: '求当世名', gloss: '以当为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '求百世名', gloss: '以百为度', primary: { traitId: 10, delta: 0.8 } },
      { text: '求千世名', gloss: '以千为度', primary: { traitId: 10, delta: 1.2 } },
      { text: '名与身齐', gloss: '以一为度', primary: { traitId: 10, delta: 1.4 } },
    ],
  },

  // ── T11 风险 ──
  {
    id: 'wp-041',
    format: 'situational',
    prompt: '险中求真',
    promptGloss: '若真理需以命求之，汝当如何？',
    options: [
      { text: '安于不真', gloss: '以安为度', primary: { traitId: 11, delta: -1.4 } },
      { text: '小试其锋', gloss: '以试为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '不偏不倚', gloss: '以中为度', primary: { traitId: 11, delta: 0.2 } },
      { text: '以险求真', gloss: '以险为度', primary: { traitId: 11, delta: 1.0 } },
      { text: '以命殉真', gloss: '苏格拉底之径', primary: { traitId: 11, delta: 1.4 } },
      { text: '以死为真', gloss: '以死为度', primary: { traitId: 11, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-042',
    format: 'situational',
    prompt: '异端之问',
    promptGloss: '若汝之见被定为异端，汝当如何？',
    options: [
      { text: '从众而止', gloss: '以同为度', primary: { traitId: 11, delta: -1.4 } },
      { text: '改而不执', gloss: '以改为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '不拒不迎', gloss: '以中为度', primary: { traitId: 11, delta: 0.0 } },
      { text: '守而不移', gloss: '以守为度', primary: { traitId: 11, delta: 0.8 } },
      { text: '虽千万人吾往', gloss: '以一为度', primary: { traitId: 11, delta: 1.2 } },
      { text: '以身为炬', gloss: '以死为度', primary: { traitId: 11, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-043',
    format: 'imagery',
    prompt: '航于大海',
    promptGloss: '思想者如行舟，汝更信何方？',
    options: [
      { text: '系于岸', gloss: '以守为锚', primary: { traitId: 11, delta: -1.4 } },
      { text: '近岸行', gloss: '以近为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '随风而动', gloss: '以时为度', primary: { traitId: 11, delta: 0.2 } },
      { text: '远帆而行', gloss: '以远为度', primary: { traitId: 11, delta: 0.8 } },
      { text: '破浪而往', gloss: '以浪为度', primary: { traitId: 11, delta: 1.2 } },
      { text: '穷尽大海', gloss: '以穷为度', primary: { traitId: 11, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-044',
    format: 'situational',
    prompt: '成与败',
    promptGloss: '若所行必败，汝犹行乎？',
    options: [
      { text: '不求必败', gloss: '以安为度', primary: { traitId: 11, delta: -1.4 } },
      { text: '见可而止', gloss: '以止为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '因事而择', gloss: '不强求', primary: { traitId: 11, delta: 0.0 } },
      { text: '虽败犹行', gloss: '以行为度', primary: { traitId: 11, delta: 0.8 } },
      { text: '明知其败', gloss: '以败为度', primary: { traitId: 11, delta: 1.2 } },
      { text: '不悔其行', gloss: '以一为度', primary: { traitId: 11, delta: 1.4 } },
    ],
  },

  // ── T12 表达 ──
  {
    id: 'wp-045',
    format: 'situational',
    prompt: '言之格',
    promptGloss: '汝之论说，更近何风？',
    options: [
      { text: '质直', gloss: '以质为度', primary: { traitId: 12, delta: -1.2 } },
      { text: '简净', gloss: '以净为度', primary: { traitId: 12, delta: -0.6 } },
      { text: '雅正', gloss: '以雅为度', primary: { traitId: 12, delta: -0.2 } },
      { text: '明达', gloss: '以达为度', primary: { traitId: 12, delta: 0.4 } },
      { text: '雄辩', gloss: '以辩为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '诗化哲思', gloss: '以诗为度', primary: { traitId: 12, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-046',
    format: 'situational',
    prompt: '对话与独白',
    promptGloss: '汝之文风，更近何端？',
    options: [
      { text: '格言', gloss: '以言为体', primary: { traitId: 12, delta: -0.8 } },
      { text: '对话', gloss: '以对为体', primary: { traitId: 12, delta: -0.2 } },
      { text: '论述', gloss: '以论为体', primary: { traitId: 12, delta: 0.2 } },
      { text: '散文', gloss: '以散为体', primary: { traitId: 12, delta: 0.6 } },
      { text: '长论', gloss: '以长为体', primary: { traitId: 12, delta: 1.0 } },
      { text: '体系', gloss: '以系为体', primary: { traitId: 12, delta: 1.2 } },
    ],
  },
  {
    id: 'wp-047',
    format: 'imagery',
    prompt: '言为器',
    promptGloss: '言之于汝，更近何器？',
    options: [
      { text: '朴石', gloss: '以朴为器', primary: { traitId: 12, delta: -0.8 } },
      { text: '木铎', gloss: '以朴为用', primary: { traitId: 12, delta: -0.4 } },
      { text: '钟', gloss: '以重为器', primary: { traitId: 12, delta: 0.0 } },
      { text: '磬', gloss: '以雅为器', primary: { traitId: 12, delta: 0.4 } },
      { text: '琴', gloss: '以文为器', primary: { traitId: 12, delta: 0.8 } },
      { text: '黄钟大吕', gloss: '以极为器', primary: { traitId: 12, delta: 1.2 } },
    ],
  },
  {
    id: 'wp-048',
    format: 'situational',
    prompt: '言之轻重',
    promptGloss: '汝之立言，更重何种？',
    options: [
      { text: '寡言', gloss: '以寡为慎', primary: { traitId: 12, delta: -1.2 } },
      { text: '言简意赅', gloss: '以简为慎', primary: { traitId: 12, delta: -0.6 } },
      { text: '言之有物', gloss: '以实为慎', primary: { traitId: 12, delta: -0.2 } },
      { text: '言之成理', gloss: '以理为慎', primary: { traitId: 12, delta: 0.2 } },
      { text: '言之动听', gloss: '以巧为慎', primary: { traitId: 12, delta: 0.6 } },
      { text: '惊世骇俗', gloss: '以极为慎', primary: { traitId: 12, delta: 1.2 } },
    ],
  },
];
