// 镜心 · 治国能臣 · 48 题
// 12 维 × 4 题；侧重思辨 / 行动 / 意志 / 风险 / 处世

import type { Item } from './item.types';

export const ITEMS_EAST_STATEMAN: readonly Item[] = [
  // ── T1 思辨 ──
  {
    id: 'es-001',
    format: 'situational',
    prompt: '国弱而民贫',
    promptGloss: '国势衰弱而百姓困乏，汝当何先？',
    options: [
      { text: '先安民心', gloss: '缓变求稳', primary: { traitId: 1, delta: -0.8 } },
      {
        text: '先养民生',
        gloss: '与民休息',
        primary: { traitId: 1, delta: -0.4 },
        secondary: [{ traitId: 9, delta: 0.4 }],
      },
      {
        text: '先固边防',
        gloss: '练兵备战',
        primary: { traitId: 1, delta: 0.2 },
        secondary: [{ traitId: 7, delta: 0.4 }],
      },
      {
        text: '先变旧制',
        gloss: '以变图强',
        primary: { traitId: 1, delta: 1.0 },
        secondary: [{ traitId: 4, delta: 0.4 }],
      },
      {
        text: '先通工商',
        gloss: '藏富于民',
        primary: { traitId: 1, delta: 0.4 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
      {
        text: '先正法度',
        gloss: '以法立国',
        primary: { traitId: 1, delta: 1.2 },
        secondary: [{ traitId: 11, delta: 0.4 }],
      },
    ],
  },
  {
    id: 'es-002',
    format: 'situational',
    prompt: '朝有积弊',
    promptGloss: '朝中积弊甚久，欲一朝尽革，汝当如何？',
    options: [
      { text: '徐徐图之', gloss: '渐变缓改', primary: { traitId: 1, delta: -0.8 } },
      {
        text: '择其大者',
        gloss: '先改要害',
        primary: { traitId: 1, delta: 0.0 },
        secondary: [{ traitId: 3, delta: 0.4 }],
      },
      {
        text: '广引众议',
        gloss: '问策百官',
        primary: { traitId: 1, delta: 0.4 },
        secondary: [{ traitId: 5, delta: 0.4 }],
      },
      {
        text: '力推全变',
        gloss: '一朝尽革',
        primary: { traitId: 1, delta: 1.0 },
        secondary: [{ traitId: 11, delta: 0.4 }],
      },
      {
        text: '考其本末',
        gloss: '寻根溯源',
        primary: { traitId: 1, delta: 1.2 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
      {
        text: '不破不立',
        gloss: '破而后立',
        primary: { traitId: 1, delta: 1.4 },
        secondary: [{ traitId: 4, delta: 0.5 }],
      },
    ],
  },
  {
    id: 'es-003',
    format: 'imagery',
    prompt: '渡河与造舟',
    promptGloss: '为政如渡河，汝更信何法？',
    options: [
      {
        text: '造船',
        gloss: '以制度为本',
        primary: { traitId: 1, delta: 0.6 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
      {
        text: '搭桥',
        gloss: '以联络为用',
        primary: { traitId: 1, delta: 0.2 },
        secondary: [{ traitId: 5, delta: 0.4 }],
      },
      { text: '摸石头', gloss: '试探渐进', primary: { traitId: 1, delta: -0.8 } },
      {
        text: '改水路',
        gloss: '求其本源',
        primary: { traitId: 1, delta: 1.2 },
        secondary: [{ traitId: 9, delta: 0.4 }],
      },
      {
        text: '聚众力',
        gloss: '以群为基',
        primary: { traitId: 1, delta: -0.2 },
        secondary: [{ traitId: 5, delta: 0.5 }],
      },
      { text: '求圣智', gloss: '以法为道', primary: { traitId: 1, delta: 1.4 } },
    ],
  },
  {
    id: 'es-004',
    format: 'situational',
    prompt: '诸臣议政',
    promptGloss: '百官议政，众说纷纭，汝何以断？',
    options: [
      {
        text: '广听不议',
        gloss: '集思广益',
        primary: { traitId: 1, delta: -0.4 },
        secondary: [{ traitId: 5, delta: 0.4 }],
      },
      {
        text: '择一己见',
        gloss: '独断专行',
        primary: { traitId: 1, delta: 0.4 },
        secondary: [{ traitId: 11, delta: 0.4 }],
      },
      { text: '两利相权', gloss: '权衡取舍', primary: { traitId: 1, delta: 0.8 } },
      {
        text: '援古证今',
        gloss: '引经据典',
        primary: { traitId: 1, delta: 0.4 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
      {
        text: '推演至终',
        gloss: '形而上之',
        primary: { traitId: 1, delta: 1.4 },
        secondary: [{ traitId: 9, delta: 0.4 }],
      },
      {
        text: '听而不言',
        gloss: '以行验之',
        primary: { traitId: 1, delta: 0.0 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
    ],
  },

  // ── T2 情感 ──
  {
    id: 'es-005',
    format: 'situational',
    prompt: '老臣请辞',
    promptGloss: '老臣以年迈请辞，汝当如何？',
    options: [
      { text: '慰留再三', gloss: '动之以情', primary: { traitId: 2, delta: 1.0 } },
      {
        text: '厚赐归乡',
        gloss: '礼送以义',
        primary: { traitId: 2, delta: 0.4 },
        secondary: [{ traitId: 9, delta: 0.4 }],
      },
      { text: '严令留任', gloss: '持法不留情', primary: { traitId: 2, delta: -1.0 } },
      {
        text: '托以大事',
        gloss: '以信动之',
        primary: { traitId: 2, delta: 0.6 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '询其继者',
        gloss: '不泥于情',
        primary: { traitId: 2, delta: -0.6 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
      { text: '随其所欲', gloss: '以诚相待', primary: { traitId: 2, delta: 0.2 } },
    ],
  },
  {
    id: 'es-006',
    format: 'situational',
    prompt: '故旧犯法',
    promptGloss: '故旧犯法当刑，汝何以处？',
    options: [
      {
        text: '网开一面',
        gloss: '徇情',
        primary: { traitId: 2, delta: 1.0 },
        secondary: [{ traitId: 11, delta: -0.4 }],
      },
      { text: '减等论处', gloss: '量情', primary: { traitId: 2, delta: 0.4 } },
      { text: '依律论罪', gloss: '以法', primary: { traitId: 2, delta: -0.8 } },
      {
        text: '公事公办',
        gloss: '存大义',
        primary: { traitId: 2, delta: -1.0 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '使其自陈',
        gloss: '以情动法',
        primary: { traitId: 2, delta: 0.4 },
        secondary: [{ traitId: 5, delta: 0.3 }],
      },
      { text: '告而后诛', gloss: '恩威并用', primary: { traitId: 2, delta: 0.0 } },
    ],
  },
  {
    id: 'es-007',
    format: 'imagery',
    prompt: '春风与秋霜',
    promptGloss: '为政当行春风之化，抑或秋霜之威？',
    options: [
      {
        text: '春风',
        gloss: '以德化',
        primary: { traitId: 2, delta: 1.2 },
        secondary: [{ traitId: 6, delta: 0.3 }],
      },
      { text: '春多于秋', gloss: '德主刑辅', primary: { traitId: 2, delta: 0.6 } },
      { text: '半春半秋', gloss: '刚柔相济', primary: { traitId: 2, delta: 0.2 } },
      { text: '秋多于春', gloss: '刑主德辅', primary: { traitId: 2, delta: -0.6 } },
      { text: '秋霜', gloss: '以威治', primary: { traitId: 2, delta: -1.0 } },
      {
        text: '随季而行',
        gloss: '时变而治',
        primary: { traitId: 2, delta: 0.0 },
        secondary: [{ traitId: 9, delta: 0.4 }],
      },
    ],
  },
  {
    id: 'es-008',
    format: 'situational',
    prompt: '灾年告急',
    promptGloss: '大灾之年，百姓流离，汝何以应？',
    options: [
      { text: '痛惜流涕', gloss: '动于中', primary: { traitId: 2, delta: 1.2 } },
      {
        text: '发仓赈济',
        gloss: '以行济情',
        primary: { traitId: 2, delta: 0.6 },
        secondary: [{ traitId: 5, delta: 0.3 }],
      },
      {
        text: '减赋免役',
        gloss: '以政应灾',
        primary: { traitId: 2, delta: 0.0 },
        secondary: [{ traitId: 9, delta: 0.4 }],
      },
      {
        text: '徙民就食',
        gloss: '以术济灾',
        primary: { traitId: 2, delta: -0.4 },
        secondary: [{ traitId: 3, delta: 0.4 }],
      },
      { text: '借粮于邻', gloss: '以外援内', primary: { traitId: 2, delta: -0.6 } },
      {
        text: '以工代赈',
        gloss: '以劳济困',
        primary: { traitId: 2, delta: -0.2 },
        secondary: [{ traitId: 8, delta: 0.3 }],
      },
    ],
  },

  // ── T3 行动 ──
  {
    id: 'es-009',
    format: 'situational',
    prompt: '机不可失',
    promptGloss: '时局千载难逢，汝当如何？',
    options: [
      { text: '坐而论道', gloss: '谋定后动', primary: { traitId: 3, delta: -1.0 } },
      { text: '徐徐待时', gloss: '待其至', primary: { traitId: 3, delta: -0.6 } },
      { text: '从长计议', gloss: '慎其行', primary: { traitId: 3, delta: -0.2 } },
      {
        text: '即断即行',
        gloss: '雷厉风行',
        primary: { traitId: 3, delta: 0.8 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '当机立断',
        gloss: '一日千里',
        primary: { traitId: 3, delta: 1.2 },
        secondary: [{ traitId: 11, delta: 0.4 }],
      },
      { text: '先发制人', gloss: '不令而行', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'es-010',
    format: 'situational',
    prompt: '战与不战',
    promptGloss: '敌兵压境，汝当如何？',
    options: [
      { text: '避其锋芒', gloss: '不战而屈', primary: { traitId: 3, delta: -1.2 } },
      { text: '坚守不出', gloss: '以静制动', primary: { traitId: 3, delta: -0.4 } },
      {
        text: '遣使议和',
        gloss: '以谈止战',
        primary: { traitId: 3, delta: -0.8 },
        secondary: [{ traitId: 1, delta: 0.4 }],
      },
      {
        text: '整军待敌',
        gloss: '有备无患',
        primary: { traitId: 3, delta: 0.2 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '主动出击',
        gloss: '以攻为守',
        primary: { traitId: 3, delta: 1.0 },
        secondary: [{ traitId: 11, delta: 0.4 }],
      },
      { text: '决一死战', gloss: '以战求存', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'es-011',
    format: 'imagery',
    prompt: '雷厉风行',
    promptGloss: '为政当行何风？',
    options: [
      {
        text: '春雨',
        gloss: '润物无声',
        primary: { traitId: 3, delta: -0.6 },
        secondary: [{ traitId: 2, delta: 0.4 }],
      },
      { text: '和风', gloss: '从容不迫', primary: { traitId: 3, delta: -0.2 } },
      { text: '顺风', gloss: '顺势而行', primary: { traitId: 3, delta: 0.2 } },
      { text: '疾风', gloss: '不速不缓', primary: { traitId: 3, delta: 0.6 } },
      {
        text: '雷厉',
        gloss: '令出必行',
        primary: { traitId: 3, delta: 1.0 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '雷霆',
        gloss: '一击必杀',
        primary: { traitId: 3, delta: 1.4 },
        secondary: [{ traitId: 11, delta: 0.4 }],
      },
    ],
  },
  {
    id: 'es-012',
    format: 'situational',
    prompt: '仓促登坛',
    promptGloss: '大事猝至，不容缓议，汝当何为？',
    options: [
      { text: '先受而后图', gloss: '先应之', primary: { traitId: 3, delta: 0.0 } },
      { text: '固请而后受', gloss: '以礼定之', primary: { traitId: 3, delta: -0.4 } },
      { text: '避而待时', gloss: '不接', primary: { traitId: 3, delta: -1.0 } },
      {
        text: '受而任之',
        gloss: '当仁不让',
        primary: { traitId: 3, delta: 1.0 },
        secondary: [{ traitId: 7, delta: 0.4 }],
      },
      { text: '受而立断', gloss: '即事而定', primary: { traitId: 3, delta: 1.4 } },
      {
        text: '临危受命',
        gloss: '死生以之',
        primary: { traitId: 3, delta: 1.2 },
        secondary: [{ traitId: 9, delta: 0.4 }],
      },
    ],
  },

  // ── T4 革新 ──
  {
    id: 'es-013',
    format: 'situational',
    prompt: '古制之惑',
    promptGloss: '古制行之百年，弊已生矣，汝当变否？',
    options: [
      { text: '坚守祖制', gloss: '不可变', primary: { traitId: 4, delta: -1.2 } },
      { text: '小修小补', gloss: '渐改', primary: { traitId: 4, delta: -0.6 } },
      { text: '择其善者', gloss: '斟酌去取', primary: { traitId: 4, delta: 0.0 } },
      {
        text: '大刀阔斧',
        gloss: '力推新制',
        primary: { traitId: 4, delta: 1.0 },
        secondary: [{ traitId: 11, delta: 0.4 }],
      },
      { text: '破旧立新', gloss: '以变为常', primary: { traitId: 4, delta: 1.4 } },
      {
        text: '援西入中',
        gloss: '师夷长技',
        primary: { traitId: 4, delta: 0.8 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
    ],
  },
  {
    id: 'es-014',
    format: 'situational',
    prompt: '新法与旧臣',
    promptGloss: '欲行新法，而旧臣阻之，汝当如何？',
    options: [
      { text: '听其言而止', gloss: '从众', primary: { traitId: 4, delta: -1.0 } },
      { text: '和稀泥', gloss: '调和', primary: { traitId: 4, delta: -0.4 } },
      { text: '徐徐开导', gloss: '渐行', primary: { traitId: 4, delta: -0.2 } },
      {
        text: '强推新法',
        gloss: '不恤人言',
        primary: { traitId: 4, delta: 1.0 },
        secondary: [{ traitId: 11, delta: 0.4 }],
      },
      {
        text: '新旧并行',
        gloss: '双轨试行',
        primary: { traitId: 4, delta: 0.4 },
        secondary: [{ traitId: 5, delta: 0.3 }],
      },
      { text: '尽革旧制', gloss: '从源头变', primary: { traitId: 4, delta: 1.4 } },
    ],
  },
  {
    id: 'es-015',
    format: 'imagery',
    prompt: '水与器',
    promptGloss: '为政如水与器，何以为喻？',
    options: [
      { text: '水就器', gloss: '因循', primary: { traitId: 4, delta: -0.8 } },
      { text: '水柔器刚', gloss: '以柔克刚', primary: { traitId: 4, delta: -0.2 } },
      { text: '水器相成', gloss: '以用为本', primary: { traitId: 4, delta: 0.4 } },
      { text: '改器盛水', gloss: '变其用', primary: { traitId: 4, delta: 0.8 } },
      { text: '破器为水', gloss: '不拘于器', primary: { traitId: 4, delta: 1.4 } },
      {
        text: '铸新器',
        gloss: '以变为常',
        primary: { traitId: 4, delta: 1.0 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
    ],
  },
  {
    id: 'es-016',
    format: 'situational',
    prompt: '以新代旧',
    promptGloss: '新事物已显其利，旧事物当何以处？',
    options: [
      { text: '听其共存', gloss: '听其自然', primary: { traitId: 4, delta: -0.6 } },
      { text: '劝新戒旧', gloss: '以利诱之', primary: { traitId: 4, delta: 0.4 } },
      {
        text: '强令新代',
        gloss: '令出必行',
        primary: { traitId: 4, delta: 0.8 },
        secondary: [{ traitId: 11, delta: 0.4 }],
      },
      {
        text: '试之有成',
        gloss: '徐以新替',
        primary: { traitId: 4, delta: 0.6 },
        secondary: [{ traitId: 1, delta: 0.4 }],
      },
      { text: '破旧立新', gloss: '不破不立', primary: { traitId: 4, delta: 1.4 } },
      { text: '融新于旧', gloss: '以旧为基', primary: { traitId: 4, delta: 0.2 } },
    ],
  },

  // ── T5 群我 ──
  {
    id: 'es-017',
    format: 'situational',
    prompt: '民与我',
    promptGloss: '国事与私事相妨，汝何以取舍？',
    options: [
      { text: '国事为先', gloss: '以国为重', primary: { traitId: 5, delta: 1.0 } },
      { text: '公私两顾', gloss: '不偏不倚', primary: { traitId: 5, delta: 0.2 } },
      { text: '私重于公', gloss: '以身为本', primary: { traitId: 5, delta: -1.0 } },
      {
        text: '以身许国',
        gloss: '死生以之',
        primary: { traitId: 5, delta: 1.4 },
        secondary: [{ traitId: 7, delta: 0.4 }],
      },
      { text: '托于左右', gloss: '以众辅己', primary: { traitId: 5, delta: 0.4 } },
      { text: '独任其责', gloss: '不累他人', primary: { traitId: 5, delta: -0.4 } },
    ],
  },
  {
    id: 'es-018',
    format: 'situational',
    prompt: '求贤与自任',
    promptGloss: '有大任在前，汝当自任，抑或求贤以任？',
    options: [
      { text: '亲历亲为', gloss: '以己为能', primary: { traitId: 5, delta: -0.8 } },
      { text: '托于近臣', gloss: '以亲为凭', primary: { traitId: 5, delta: -0.2 } },
      {
        text: '选贤任能',
        gloss: '广开才路',
        primary: { traitId: 5, delta: 1.0 },
        secondary: [{ traitId: 8, delta: 0.3 }],
      },
      { text: '任众共议', gloss: '以群为智', primary: { traitId: 5, delta: 1.2 } },
      { text: '自任而委', gloss: '兼己与人', primary: { traitId: 5, delta: 0.4 } },
      {
        text: '任而不疑',
        gloss: '用人不疑',
        primary: { traitId: 5, delta: 0.6 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
    ],
  },
  {
    id: 'es-019',
    format: 'imagery',
    prompt: '独木与森林',
    promptGloss: '为政当如何借力？',
    options: [
      { text: '独木', gloss: '以一己之力', primary: { traitId: 5, delta: -0.8 } },
      { text: '双木', gloss: '以一己之辅', primary: { traitId: 5, delta: -0.2 } },
      { text: '木与林', gloss: '兼己与群', primary: { traitId: 5, delta: 0.4 } },
      { text: '森林', gloss: '以群为本', primary: { traitId: 5, delta: 1.0 } },
      { text: '群策群力', gloss: '合众智', primary: { traitId: 5, delta: 1.2 } },
      { text: '以民为林', gloss: '以民为本', primary: { traitId: 5, delta: 1.4 } },
    ],
  },
  {
    id: 'es-020',
    format: 'situational',
    prompt: '众议纷纷',
    promptGloss: '众论纷纷，汝当听谁？',
    options: [
      { text: '一己独断', gloss: '不听众言', primary: { traitId: 5, delta: -1.0 } },
      { text: '择一二言', gloss: '择善而从', primary: { traitId: 5, delta: 0.0 } },
      { text: '从众', gloss: '随大流', primary: { traitId: 5, delta: 0.6 } },
      { text: '广开言路', gloss: '以议为政', primary: { traitId: 5, delta: 1.0 } },
      { text: '以民为本', gloss: '听民声', primary: { traitId: 5, delta: 1.2 } },
      { text: '问于师友', gloss: '择亲而问', primary: { traitId: 5, delta: 0.4 } },
    ],
  },

  // ── T6 审美 ──
  {
    id: 'es-021',
    format: 'imagery',
    prompt: '朝堂之美',
    promptGloss: '朝堂之饰，汝取何格？',
    options: [
      { text: '朴素', gloss: '去华取朴', primary: { traitId: 6, delta: -0.8 } },
      { text: '清雅', gloss: '以淡为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '庄重', gloss: '以威为美', primary: { traitId: 6, delta: 0.0 } },
      { text: '辉煌', gloss: '以盛为美', primary: { traitId: 6, delta: 0.4 } },
      { text: '瑰丽', gloss: '以华为美', primary: { traitId: 6, delta: 0.8 } },
      { text: '极盛', gloss: '以极丽为美', primary: { traitId: 6, delta: 1.2 } },
    ],
  },
  {
    id: 'es-022',
    format: 'situational',
    prompt: '奏议之辞',
    promptGloss: '奏议之文，汝取何风？',
    options: [
      { text: '质朴直言', gloss: '以质为美', primary: { traitId: 6, delta: -0.8 } },
      { text: '简净有序', gloss: '以理为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '典雅有节', gloss: '以雅为美', primary: { traitId: 6, delta: 0.0 } },
      { text: '铺陈华美', gloss: '以辞为美', primary: { traitId: 6, delta: 0.6 } },
      { text: '文采斐然', gloss: '以文为美', primary: { traitId: 6, delta: 1.0 } },
      { text: '骈四俪六', gloss: '以极致为美', primary: { traitId: 6, delta: 1.2 } },
    ],
  },
  {
    id: 'es-023',
    format: 'situational',
    prompt: '礼乐之用',
    promptGloss: '礼乐之于政，汝何以视？',
    options: [
      { text: '虚文', gloss: '无足轻重', primary: { traitId: 6, delta: -1.0 } },
      { text: '辅政', gloss: '以美化俗', primary: { traitId: 6, delta: 0.0 } },
      {
        text: '化民',
        gloss: '以礼成俗',
        primary: { traitId: 6, delta: 0.6 },
        secondary: [{ traitId: 5, delta: 0.3 }],
      },
      { text: '经国', gloss: '以礼为纲', primary: { traitId: 6, delta: 1.0 } },
      {
        text: '美政',
        gloss: '政之极致',
        primary: { traitId: 6, delta: 1.2 },
        secondary: [{ traitId: 9, delta: 0.4 }],
      },
      { text: '无用之华', gloss: '不取', primary: { traitId: 6, delta: -0.8 } },
    ],
  },
  {
    id: 'es-024',
    format: 'imagery',
    prompt: '碑铭之志',
    promptGloss: '若立碑铭，汝欲何句留于世？',
    options: [
      { text: '默默无闻', gloss: '不留', primary: { traitId: 6, delta: -1.0 } },
      { text: '清慎勤', gloss: '以行为志', primary: { traitId: 6, delta: -0.4 } },
      { text: '惠民', gloss: '以民为志', primary: { traitId: 6, delta: 0.0 } },
      { text: '功业', gloss: '以功为志', primary: { traitId: 6, delta: 0.4 } },
      { text: '千古', gloss: '以名为志', primary: { traitId: 6, delta: 0.8 } },
      { text: '永世流芳', gloss: '以极致为志', primary: { traitId: 6, delta: 1.2 } },
    ],
  },

  // ── T7 意志 ──
  {
    id: 'es-025',
    format: 'situational',
    prompt: '屡挫屡战',
    promptGloss: '事经屡挫，汝当如何？',
    options: [
      { text: '知难而退', gloss: '不争', primary: { traitId: 7, delta: -1.4 } },
      { text: '暂退待时', gloss: '不争于一时', primary: { traitId: 7, delta: -0.6 } },
      { text: '稳扎稳打', gloss: '以持久战', primary: { traitId: 7, delta: 0.4 } },
      { text: '愈挫愈勇', gloss: '以苦为乐', primary: { traitId: 7, delta: 1.0 } },
      { text: '以死相争', gloss: '死而后已', primary: { traitId: 7, delta: 1.4 } },
      { text: '再接再厉', gloss: '以继为志', primary: { traitId: 7, delta: 0.8 } },
    ],
  },
  {
    id: 'es-026',
    format: 'situational',
    prompt: '众谤于身',
    promptGloss: '众口铄金，谤言满朝，汝当如何？',
    options: [
      { text: '改弦易辙', gloss: '顺众而止', primary: { traitId: 7, delta: -1.0 } },
      { text: '退而自陈', gloss: '求明', primary: { traitId: 7, delta: -0.4 } },
      { text: '不辩不争', gloss: '以静制动', primary: { traitId: 7, delta: 0.0 } },
      { text: '持节不屈', gloss: '以节自守', primary: { traitId: 7, delta: 0.8 } },
      { text: '以身为证', gloss: '死生以之', primary: { traitId: 7, delta: 1.4 } },
      { text: '反躬自省', gloss: '慎独', primary: { traitId: 7, delta: 0.4 } },
    ],
  },
  {
    id: 'es-027',
    format: 'imagery',
    prompt: '岁寒之木',
    promptGloss: '岁寒之时，汝欲为何木？',
    options: [
      { text: '落叶之木', gloss: '顺势而退', primary: { traitId: 7, delta: -0.8 } },
      { text: '常青之木', gloss: '以恒为志', primary: { traitId: 7, delta: 0.4 } },
      { text: '松柏', gloss: '后凋之志', primary: { traitId: 7, delta: 0.8 } },
      { text: '寒梅', gloss: '以苦为香', primary: { traitId: 7, delta: 1.0 } },
      { text: '铁木', gloss: '百折不移', primary: { traitId: 7, delta: 1.2 } },
      {
        text: '岁寒三友',
        gloss: '以友为志',
        primary: { traitId: 7, delta: 0.6 },
        secondary: [{ traitId: 5, delta: 0.3 }],
      },
    ],
  },
  {
    id: 'es-028',
    format: 'situational',
    prompt: '一意孤行',
    promptGloss: '上下皆言不可，汝犹当行乎？',
    options: [
      { text: '从众而止', gloss: '不违众', primary: { traitId: 7, delta: -1.0 } },
      { text: '察众言而动', gloss: '择善而从', primary: { traitId: 7, delta: 0.0 } },
      { text: '执中', gloss: '不偏不倚', primary: { traitId: 7, delta: 0.2 } },
      { text: '执意独行', gloss: '虽千万人吾往矣', primary: { traitId: 7, delta: 1.0 } },
      { text: '以身试道', gloss: '以死明志', primary: { traitId: 7, delta: 1.4 } },
      { text: '暂退而后图', gloss: '以退为进', primary: { traitId: 7, delta: 0.4 } },
    ],
  },

  // ── T8 学识 ──
  {
    id: 'es-029',
    format: 'situational',
    prompt: '读书与治事',
    promptGloss: '为政者，汝以何为先？',
    options: [
      { text: '不学而治', gloss: '以术为足', primary: { traitId: 8, delta: -1.2 } },
      { text: '学以辅治', gloss: '以学为用', primary: { traitId: 8, delta: 0.4 } },
      { text: '以学为治', gloss: '以学为本', primary: { traitId: 8, delta: 0.8 } },
      { text: '通识为要', gloss: '不求专精', primary: { traitId: 8, delta: -0.4 } },
      { text: '博学于政', gloss: '以学为政', primary: { traitId: 8, delta: 1.0 } },
      { text: '穷经致用', gloss: '以经为治', primary: { traitId: 8, delta: 1.2 } },
    ],
  },
  {
    id: 'es-030',
    format: 'situational',
    prompt: '一技与万技',
    promptGloss: '为政当一技专精，抑或万技皆通？',
    options: [
      { text: '一技', gloss: '以专为本', primary: { traitId: 8, delta: 0.4 } },
      { text: '一技为主', gloss: '以一御多', primary: { traitId: 8, delta: 0.8 } },
      { text: '数技', gloss: '以多为博', primary: { traitId: 8, delta: 0.0 } },
      { text: '通万技', gloss: '以博为要', primary: { traitId: 8, delta: -0.4 } },
      { text: '学以应用', gloss: '不学无术', primary: { traitId: 8, delta: 1.0 } },
      { text: '学贯古今', gloss: '以博为精', primary: { traitId: 8, delta: -0.6 } },
    ],
  },
  {
    id: 'es-031',
    format: 'imagery',
    prompt: '江海与杯水',
    promptGloss: '为政者所学，汝欲其为何？',
    options: [
      { text: '杯水', gloss: '一技足矣', primary: { traitId: 8, delta: -0.4 } },
      { text: '井水', gloss: '一隅之知', primary: { traitId: 8, delta: -0.2 } },
      { text: '溪流', gloss: '日积月累', primary: { traitId: 8, delta: 0.2 } },
      { text: '江河', gloss: '以学为江', primary: { traitId: 8, delta: 0.6 } },
      { text: '江海', gloss: '以学为海', primary: { traitId: 8, delta: 1.0 } },
      { text: '海纳百川', gloss: '以学为渊', primary: { traitId: 8, delta: 0.4 } },
    ],
  },
  {
    id: 'es-032',
    format: 'situational',
    prompt: '学以致用',
    promptGloss: '满腹经纶而百无一用，汝何以自处？',
    options: [
      { text: '藏之名山', gloss: '以学为高', primary: { traitId: 8, delta: -0.6 } },
      { text: '以学为隐', gloss: '不求闻达', primary: { traitId: 8, delta: -0.4 } },
      { text: '学以致用', gloss: '以用为本', primary: { traitId: 8, delta: 0.4 } },
      {
        text: '教化于众',
        gloss: '以学化人',
        primary: { traitId: 8, delta: 0.6 },
        secondary: [{ traitId: 5, delta: 0.3 }],
      },
      { text: '佐政以成', gloss: '以学成事', primary: { traitId: 8, delta: 1.0 } },
      { text: '开宗立派', gloss: '以学立言', primary: { traitId: 8, delta: 0.8 } },
    ],
  },

  // ── T9 处世 ──
  {
    id: 'es-033',
    format: 'situational',
    prompt: '急流勇退',
    promptGloss: '功成之后，汝欲何往？',
    options: [
      { text: '进而不止', gloss: '以进为志', primary: { traitId: 9, delta: -1.4 } },
      { text: '进退有度', gloss: '以时为度', primary: { traitId: 9, delta: 0.0 } },
      { text: '止于其位', gloss: '不求过分', primary: { traitId: 9, delta: 0.6 } },
      { text: '退而思过', gloss: '以退为省', primary: { traitId: 9, delta: 1.0 } },
      { text: '退而忘形', gloss: '以退为养', primary: { traitId: 9, delta: 1.4 } },
      { text: '功成不居', gloss: '以退为道', primary: { traitId: 9, delta: 1.2 } },
    ],
  },
  {
    id: 'es-034',
    format: 'situational',
    prompt: '入仕与退隐',
    promptGloss: '入仕数载，汝欲何往？',
    options: [
      { text: '鞠躬尽瘁', gloss: '死生以之', primary: { traitId: 9, delta: -1.0 } },
      { text: '一展宏图', gloss: '以进为志', primary: { traitId: 9, delta: -0.6 } },
      { text: '进退从容', gloss: '不急不缓', primary: { traitId: 9, delta: 0.2 } },
      { text: '择时而退', gloss: '以退为进', primary: { traitId: 9, delta: 0.8 } },
      { text: '退而传道', gloss: '以退为化', primary: { traitId: 9, delta: 1.2 } },
      { text: '归田园居', gloss: '以退为终', primary: { traitId: 9, delta: 1.4 } },
    ],
  },
  {
    id: 'es-035',
    format: 'imagery',
    prompt: '进与退',
    promptGloss: '为政之道，进退之机，汝欲何取？',
    options: [
      { text: '勇进', gloss: '以进为道', primary: { traitId: 9, delta: -1.0 } },
      { text: '缓进', gloss: '以进为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '进退有度', gloss: '不偏不倚', primary: { traitId: 9, delta: 0.2 } },
      { text: '退守', gloss: '以退为守', primary: { traitId: 9, delta: 0.8 } },
      { text: '勇退', gloss: '以退为道', primary: { traitId: 9, delta: 1.4 } },
      { text: '进退自如', gloss: '以变为常', primary: { traitId: 9, delta: 0.6 } },
    ],
  },
  {
    id: 'es-036',
    format: 'situational',
    prompt: '盛年与暮年',
    promptGloss: '盛年已过，汝欲何为？',
    options: [
      { text: '老骥伏枥', gloss: '以志为老', primary: { traitId: 9, delta: -0.8 } },
      { text: '守成而已', gloss: '以守为终', primary: { traitId: 9, delta: 0.4 } },
      { text: '以身为教', gloss: '以身为化', primary: { traitId: 9, delta: 1.0 } },
      { text: '传道授业', gloss: '以退为传', primary: { traitId: 9, delta: 1.2 } },
      { text: '归田著书', gloss: '以退为终', primary: { traitId: 9, delta: 1.4 } },
      { text: '老当益壮', gloss: '以老为进', primary: { traitId: 9, delta: -0.6 } },
    ],
  },

  // ── T10 时间 ──
  {
    id: 'es-037',
    format: 'situational',
    prompt: '立竿见影',
    promptGloss: '欲其功立现，汝取何法？',
    options: [
      { text: '急功近利', gloss: '以速为功', primary: { traitId: 10, delta: -1.0 } },
      { text: '小步快跑', gloss: '以渐为速', primary: { traitId: 10, delta: -0.4 } },
      { text: '见功即止', gloss: '不求久远', primary: { traitId: 10, delta: 0.0 } },
      { text: '立百年计', gloss: '以久为功', primary: { traitId: 10, delta: 0.8 } },
      { text: '为万世开太平', gloss: '以永为功', primary: { traitId: 10, delta: 1.4 } },
      { text: '不计一时', gloss: '以无为有', primary: { traitId: 10, delta: 0.6 } },
    ],
  },
  {
    id: 'es-038',
    format: 'situational',
    prompt: '今与古',
    promptGloss: '为政当法古，抑或师今？',
    options: [
      {
        text: '法古',
        gloss: '以古为师',
        primary: { traitId: 10, delta: -0.4 },
        secondary: [{ traitId: 8, delta: 0.3 }],
      },
      { text: '师今', gloss: '以今为师', primary: { traitId: 10, delta: 0.4 } },
      { text: '古为今用', gloss: '以用为度', primary: { traitId: 10, delta: 0.2 } },
      { text: '与时俱进', gloss: '以时为度', primary: { traitId: 10, delta: 0.6 } },
      { text: '百世为师', gloss: '以永为师', primary: { traitId: 10, delta: 1.2 } },
      { text: '万世为法', gloss: '以法为永', primary: { traitId: 10, delta: 1.4 } },
    ],
  },
  {
    id: 'es-039',
    format: 'imagery',
    prompt: '朝菌与冥灵',
    promptGloss: '汝欲为朝菌之知，抑或冥灵之寿？',
    options: [
      { text: '朝菌', gloss: '以一日为天', primary: { traitId: 10, delta: -0.8 } },
      { text: '蟪蛄', gloss: '以一季为天', primary: { traitId: 10, delta: -0.4 } },
      { text: '冥灵', gloss: '以千年为天', primary: { traitId: 10, delta: 0.6 } },
      { text: '大椿', gloss: '以万古为天', primary: { traitId: 10, delta: 1.2 } },
      { text: '彭祖', gloss: '以寿为极', primary: { traitId: 10, delta: 1.0 } },
      { text: '与天地齐', gloss: '以天地为身', primary: { traitId: 10, delta: 1.4 } },
    ],
  },
  {
    id: 'es-040',
    format: 'situational',
    prompt: '身后之名',
    promptGloss: '身后之名，汝欲何为？',
    options: [
      { text: '不计身后', gloss: '以生为要', primary: { traitId: 10, delta: -1.0 } },
      { text: '求当世名', gloss: '以名为生', primary: { traitId: 10, delta: -0.4 } },
      { text: '求后世名', gloss: '以名为后', primary: { traitId: 10, delta: 0.4 } },
      { text: '求百世名', gloss: '以名为百', primary: { traitId: 10, delta: 1.0 } },
      { text: '求万世名', gloss: '以名为永', primary: { traitId: 10, delta: 1.4 } },
      { text: '名与身孰亲', gloss: '以身为亲', primary: { traitId: 10, delta: -0.6 } },
    ],
  },

  // ── T11 风险 ──
  {
    id: 'es-041',
    format: 'situational',
    prompt: '险中求胜',
    promptGloss: '成败未卜，汝当如何？',
    options: [
      { text: '以稳为先', gloss: '不涉险', primary: { traitId: 11, delta: -1.2 } },
      { text: '小试其锋', gloss: '以试为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '中度行险', gloss: '以险为用', primary: { traitId: 11, delta: 0.4 } },
      { text: '以险求胜', gloss: '以险为道', primary: { traitId: 11, delta: 1.0 } },
      { text: '以死求生', gloss: '以死为赌', primary: { traitId: 11, delta: 1.4 } },
      { text: '以退避险', gloss: '以退为避', primary: { traitId: 11, delta: -0.8 } },
    ],
  },
  {
    id: 'es-042',
    format: 'situational',
    prompt: '一搏与保守',
    promptGloss: '赌国运以一搏，抑或守成以待？',
    options: [
      { text: '守成', gloss: '以守为策', primary: { traitId: 11, delta: -1.4 } },
      { text: '守中', gloss: '不偏不倚', primary: { traitId: 11, delta: -0.4 } },
      { text: '以攻代守', gloss: '以攻为策', primary: { traitId: 11, delta: 0.4 } },
      { text: '一搏', gloss: '以一为策', primary: { traitId: 11, delta: 1.0 } },
      { text: '倾国一搏', gloss: '以国为赌', primary: { traitId: 11, delta: 1.4 } },
      { text: '以退为进', gloss: '以退为策', primary: { traitId: 11, delta: -0.6 } },
    ],
  },
  {
    id: 'es-043',
    format: 'imagery',
    prompt: '行舟与锚',
    promptGloss: '为政如行舟，汝取何为？',
    options: [
      { text: '系于岸', gloss: '以守为锚', primary: { traitId: 11, delta: -1.4 } },
      { text: '半锚半行', gloss: '以守为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '随风而动', gloss: '以时为度', primary: { traitId: 11, delta: 0.4 } },
      { text: '扬帆远航', gloss: '以行为锚', primary: { traitId: 11, delta: 1.0 } },
      { text: '破浪前行', gloss: '以险为锚', primary: { traitId: 11, delta: 1.4 } },
      { text: '以风为帆', gloss: '以变为锚', primary: { traitId: 11, delta: 0.6 } },
    ],
  },
  {
    id: 'es-044',
    format: 'situational',
    prompt: '孤注一掷',
    promptGloss: '事已至此，孤注一掷乎？',
    options: [
      { text: '绝不孤注', gloss: '以稳为守', primary: { traitId: 11, delta: -1.2 } },
      { text: '稳中求胜', gloss: '不涉大险', primary: { traitId: 11, delta: -0.4 } },
      { text: '见机而动', gloss: '以机为度', primary: { traitId: 11, delta: 0.4 } },
      { text: '搏之一搏', gloss: '以一为策', primary: { traitId: 11, delta: 1.0 } },
      { text: '以死相搏', gloss: '以死为策', primary: { traitId: 11, delta: 1.4 } },
      { text: '退而求之', gloss: '以退为策', primary: { traitId: 11, delta: -0.8 } },
    ],
  },

  // ── T12 表达 ──
  {
    id: 'es-045',
    format: 'situational',
    prompt: '为政之言',
    promptGloss: '为政之言，汝欲何风？',
    options: [
      { text: '质直', gloss: '以质为言', primary: { traitId: 12, delta: -1.0 } },
      { text: '简净', gloss: '以净为言', primary: { traitId: 12, delta: -0.6 } },
      { text: '雅正', gloss: '以雅为言', primary: { traitId: 12, delta: -0.2 } },
      { text: '明达', gloss: '以达为言', primary: { traitId: 12, delta: 0.4 } },
      { text: '文丽', gloss: '以文为言', primary: { traitId: 12, delta: 0.8 } },
      { text: '辞章', gloss: '以辞为言', primary: { traitId: 12, delta: 1.2 } },
    ],
  },
  {
    id: 'es-046',
    format: 'situational',
    prompt: '上表奏议',
    promptGloss: '上表奏事，汝欲何辞？',
    options: [
      { text: '直陈其事', gloss: '以直为表', primary: { traitId: 12, delta: -1.0 } },
      { text: '引经据典', gloss: '以古为表', primary: { traitId: 12, delta: -0.2 } },
      { text: '援事说理', gloss: '以理为表', primary: { traitId: 12, delta: 0.0 } },
      { text: '曲尽其妙', gloss: '以巧为表', primary: { traitId: 12, delta: 0.6 } },
      { text: '骈四俪六', gloss: '以骈为表', primary: { traitId: 12, delta: 1.0 } },
      { text: '惊心动魄', gloss: '以极为表', primary: { traitId: 12, delta: 1.2 } },
    ],
  },
  {
    id: 'es-047',
    format: 'imagery',
    prompt: '言之器',
    promptGloss: '为政之言，汝取何器？',
    options: [
      { text: '瓦缶', gloss: '以朴为器', primary: { traitId: 12, delta: -0.8 } },
      { text: '木铎', gloss: '以朴为用', primary: { traitId: 12, delta: -0.4 } },
      { text: '钟', gloss: '以重为器', primary: { traitId: 12, delta: 0.0 } },
      { text: '磬', gloss: '以雅为器', primary: { traitId: 12, delta: 0.4 } },
      { text: '琴', gloss: '以文为器', primary: { traitId: 12, delta: 0.8 } },
      { text: '黄钟大吕', gloss: '以极为器', primary: { traitId: 12, delta: 1.2 } },
    ],
  },
  {
    id: 'es-048',
    format: 'situational',
    prompt: '言之轻重',
    promptGloss: '一言之失，社稷随之，汝何以谨言？',
    options: [
      { text: '寡言', gloss: '以寡为慎', primary: { traitId: 12, delta: -1.2 } },
      { text: '言简意赅', gloss: '以简为慎', primary: { traitId: 12, delta: -0.6 } },
      { text: '言之有物', gloss: '以实为慎', primary: { traitId: 12, delta: -0.2 } },
      { text: '言之成理', gloss: '以理为慎', primary: { traitId: 12, delta: 0.2 } },
      { text: '言之动听', gloss: '以巧为慎', primary: { traitId: 12, delta: 0.6 } },
      { text: '言之惊世', gloss: '以极为慎', primary: { traitId: 12, delta: 1.2 } },
    ],
  },
];
