export { api, default } from './base/client'

export { userApi } from './modules/user'
export { assessmentApi } from './modules/assessment'
export { achievementApi } from './modules/achievement'
export { trainingApi } from './modules/training'
export { moodApi } from './modules/mood'
export { settingsApi } from './modules/settings'

export type { ApiResponse, ApiError, RequestConfig, PaginatedResponse } from './types'
export type { User, CreateUserRequest, UpdateUserRequest } from './modules/user'
export type { Assessment, Answer, Submission } from './modules/assessment'
export type { Achievement } from './modules/achievement'
export type { TrainingRecord, CreateTrainingRequest } from './modules/training'
export type { MoodRecord, CreateMoodRequest } from './modules/mood'
export type { UserSettings, UpdateSettingsRequest } from './modules/settings'
