// 镜心 · 治国能臣 · 30 人
//
// 12 维向量分布策略：30 人 = 5 区段 × 6 人
//   A 极端外：思辨 ≥ 0.85 / 行动 ≥ 0.85 / 意志 ≥ 0.85 / 风险 ≥ 0.80 ── 商鞅、范雎、李斯、张居正、康有为、商鞅（已用）→ 用王猛代
//   B 偏外：思辨 0.65-0.85 ── 管仲、晏婴、诸葛亮、范仲淹、岳飞、林则徐
//   C 中段：0.40-0.60 ── 萧何、房玄龄、魏徵、文天祥、海瑞、梁启超
//   D 偏内：思辨 0.20-0.40 ── 张良、狄仁杰、徐阶、张之洞、李鸿章、周公
//   E 极端内：思辨 ≤ 0.20 ── 伊尹、姜尚、左宗棠、孙中山、刘伯温、范蠡

import type { Figure } from './figure.types';

export const FIGURES_EAST_STATEMAN: readonly Figure[] = [
  // ── A 极端外：变法 + 果决 + 刚毅 + 敢赌 ──
  {
    id: 'es-shangyang',
    name: '商鞅',
    era: '战国',
    domain: 'east-statesman',
    vector: [0.92, 0.35, 0.95, 0.98, 0.7, 0.3, 0.95, 0.85, 0.3, 0.6, 0.9, 0.4],
    signature: '治世不一道，便国不法古。',
    bio: '公孙氏，名鞅，卫国人。入秦说孝公行变法，废井田、开阡陌、奖军功、行县制。秦以富强。孝公卒，遭车裂，百姓哭之。',
    portrait: 'portraits/east-statesman/shangyang.svg',
    matchBlurb: '汝与 {{name}} 同，以法为骨，以变为道，敢为天下先。',
    anecdotes: [
      { title: '城门立木', body: '商鞅立三丈木于南门，募民徙之北门予五十金，以明不欺，民信之。' },
      { title: '徙木立信', body: '法令初颁，取信于民为要。' },
    ],
    echoes: ['es-li', 'es-fan', 'es-lisi'],
  },
  {
    id: 'es-fanju',
    name: '范雎',
    era: '战国',
    domain: 'east-statesman',
    vector: [0.9, 0.4, 0.9, 0.9, 0.55, 0.35, 0.88, 0.85, 0.35, 0.55, 0.85, 0.5],
    signature: '远交而近攻，得寸则王之寸也。',
    bio: '字叔，魏人。尝受辱于须贾，几死。走秦说昭王，倡「远交近攻」，废穰侯，逐华阳，相机而动，秦以日强。',
    portrait: 'portraits/east-statesman/fanju.svg',
    matchBlurb: '汝与 {{name}} 同，能忍辱而后发，知机而善断。',
    anecdotes: [
      { title: '绨袍恋恋', body: '范雎既相秦，念魏齐之辱，故有绨袍恋恋之讥。' },
      { title: '远交近攻', body: '为秦定下数十年外交战略。' },
    ],
    echoes: ['es-shangyang', 'es-lisi', 'es-zhangqiu'],
  },
  {
    id: 'es-lisi',
    name: '李斯',
    era: '秦',
    domain: 'east-statesman',
    vector: [0.88, 0.3, 0.92, 0.9, 0.5, 0.4, 0.85, 0.95, 0.25, 0.6, 0.88, 0.7],
    signature: '诟莫大于卑贱，而悲莫甚于穷困。',
    bio: '楚国上蔡人。师荀卿，学帝王术。入秦佐秦始皇统一天下，书同文、车同轨、行郡县。沙丘之变后被赵高所害，腰斩咸阳市。',
    portrait: 'portraits/east-statesman/lisi.svg',
    matchBlurb: '汝与 {{name}} 同，善书亦善政，能以尺牍定天下。',
    anecdotes: [
      {
        title: '仓鼠之叹',
        body: '李斯见吏舍厕中鼠食不洁，近人犬，数惊恐；观仓中鼠食积粟，居大庑之下，不见人犬之忧，乃叹。',
      },
      { title: '篆书定形', body: '李斯作《仓颉篇》，规范小篆，为汉字定型之祖。' },
    ],
    echoes: ['es-shangyang', 'es-fanju', 'es-zhangqiu'],
  },
  {
    id: 'es-zhangqiu',
    name: '张居正',
    era: '明',
    domain: 'east-statesman',
    vector: [0.86, 0.4, 0.95, 0.92, 0.65, 0.3, 0.92, 0.88, 0.3, 0.65, 0.85, 0.45],
    signature: '我非相，乃摄也。',
    bio: '字叔大，号太岳。湖广江陵人。万历初为相，行一条鞭法、清丈田亩、考成法，使万历前十年号为「万历中兴」。',
    portrait: 'portraits/east-statesman/zhangqiu.svg',
    matchBlurb: '汝与 {{name}} 同，执国如执秤，毫厘不让。',
    anecdotes: [
      { title: '一条鞭法', body: '将田赋、徭役、杂税并为银两计征，简化赋役。' },
      { title: '考成法', body: '以六部官员办事效率为考核，逾期者严处。' },
    ],
    echoes: ['es-shangyang', 'es-fanju', 'es-wangmeng'],
  },
  {
    id: 'es-kangyouwei',
    name: '康有为',
    era: '清',
    domain: 'east-statesman',
    vector: [0.88, 0.6, 0.85, 0.95, 0.6, 0.4, 0.78, 0.9, 0.4, 0.55, 0.9, 0.7],
    signature: '变者，天道也。',
    bio: '广东南海人。光绪进士。倡维新变法，撰《新学伪经考》《孔子改制考》。公车上书，百日维新，戊戌变法失败后流亡海外。',
    portrait: 'portraits/east-statesman/kangyouwei.svg',
    matchBlurb: '汝与 {{name}} 同，思以制度变天下，敢为天下先。',
    anecdotes: [
      {
        title: '公车上书',
        body: '1895 年甲午战败，康有为联合 18 省举人 1300 余人上书光绪帝，请求变法。',
      },
      { title: '百日维新', body: '103 天内颁数十道新政诏令，后被慈禧扼杀。' },
    ],
    echoes: ['es-shangyang', 'es-zhangqiu', 'es-liangqichao'],
  },
  {
    id: 'es-wangmeng',
    name: '王猛',
    era: '前秦',
    domain: 'east-statesman',
    vector: [0.85, 0.5, 0.9, 0.85, 0.5, 0.35, 0.9, 0.85, 0.4, 0.6, 0.8, 0.45],
    signature: '扪虱而谈天下事。',
    bio: '字景略，北海剧人。布衣时扪虱与桓温论天下，旁若无人。苻坚得之，比之诸葛孔明。相前秦，诛豪强、举贤才、治关中。',
    portrait: 'portraits/east-statesman/wangmeng.svg',
    matchBlurb: '汝与 {{name}} 同，貌寝而才高，乱世能自守。',
    anecdotes: [
      { title: '扪虱谈天下', body: '王猛布衣见桓温，谈天下事如指掌，扪虱而言，旁若无人。' },
      { title: '关中大治', body: '相苻坚十年，关中清晏，百姓丰乐。' },
    ],
    echoes: ['es-zhuge', 'es-zhangqiu', 'es-shangyang'],
  },

  // ── B 偏外：辅佐 + 守正 + 中度风险 ──
  {
    id: 'es-guanzhong',
    name: '管仲',
    era: '春秋',
    domain: 'east-statesman',
    vector: [0.8, 0.4, 0.8, 0.85, 0.7, 0.4, 0.7, 0.8, 0.45, 0.5, 0.7, 0.4],
    signature: '仓廪实而知礼节，衣食足而知荣辱。',
    bio: '名夷吾，字仲，颍上人。初事公子纠，后相齐桓公，九合诸侯，一匡天下。通工商、重盐铁，助桓公首霸。',
    portrait: 'portraits/east-statesman/guanzhong.svg',
    matchBlurb: '汝与 {{name}} 同，能通商惠工，使民得利而国自富。',
    anecdotes: [
      {
        title: '老马识途',
        body: '齐桓公伐山戎，归途迷。管仲曰：「老马之智可用也。」乃放老马而随之，遂得道。',
      },
      { title: '九合诸侯', body: '为齐桓公成就首霸之业。' },
    ],
    echoes: ['es-shangyang', 'es-fanju', 'es-zhuge'],
  },
  {
    id: 'es-yanying',
    name: '晏婴',
    era: '春秋',
    domain: 'east-statesman',
    vector: [0.82, 0.5, 0.7, 0.7, 0.75, 0.4, 0.8, 0.85, 0.5, 0.55, 0.6, 0.75],
    signature: '踊贵而屦贱。',
    bio: '字仲，谥平仲，齐国莱人。相齐灵公、庄公、景公三朝，以节俭、机敏、善辩闻名。',
    portrait: 'portraits/east-statesman/yanying.svg',
    matchBlurb: '汝与 {{name}} 同，善以辞令折冲樽俎，不战而屈人之兵。',
    anecdotes: [
      { title: '二桃杀三士', body: '晏婴设计使公孙接、田开疆、古冶子三勇士自刎。' },
      { title: '使楚不辱', body: '出使楚国，巧辞应对，使楚王不敢辱齐使。' },
    ],
    echoes: ['es-guanzhong', 'es-zhuge', 'es-weizheng'],
  },
  {
    id: 'es-zhuge',
    name: '诸葛亮',
    era: '蜀汉',
    domain: 'east-statesman',
    vector: [0.88, 0.5, 0.75, 0.7, 0.7, 0.5, 0.9, 0.95, 0.5, 0.7, 0.65, 0.65],
    signature: '鞠躬尽瘁，死而后已。',
    bio: '字孔明，号卧龙。琅邪阳都人。隐居隆中十年，刘备三顾而出。辅蜀汉，联吴抗曹，南征北伐。',
    portrait: 'portraits/east-statesman/zhuge.svg',
    matchBlurb: '汝与 {{name}} 同，能以一隅敌天下，知其不可而为之。',
    anecdotes: [
      { title: '草船借箭', body: '以草船诱曹军放箭，得箭十万。' },
      { title: '七擒孟获', body: '南征七擒七纵，使孟获心服。' },
      { title: '出师表', body: '临终前上表，忠贞昭然。' },
    ],
    echoes: ['es-wangmeng', 'es-fanju', 'es-weizheng'],
  },
  {
    id: 'es-fanzhongyan',
    name: '范仲淹',
    era: '宋',
    domain: 'east-statesman',
    vector: [0.8, 0.5, 0.75, 0.78, 0.8, 0.5, 0.85, 0.88, 0.4, 0.65, 0.7, 0.6],
    signature: '先天下之忧而忧，后天下之乐而乐。',
    bio: '字希文，苏州吴县人。幼时家贫，划粥断齑。庆历新政，推行明黜陟、抑侥幸。戍边西北，号令严明，西夏不敢犯。',
    portrait: 'portraits/east-statesman/fanzhongyan.svg',
    matchBlurb: '汝与 {{name}} 同，以天下为怀，以民为念。',
    anecdotes: [
      { title: '划粥断齑', body: '少时家贫，煮粥凉后切为四块，早晚取食。' },
      { title: '渔家傲', body: '塞下秋来风景异，写戍边将士之苦。' },
    ],
    echoes: ['es-zhuge', 'es-weizheng', 'es-haigui'],
  },
  {
    id: 'es-yuefei',
    name: '岳飞',
    era: '宋',
    domain: 'east-statesman',
    vector: [0.7, 0.7, 0.95, 0.6, 0.85, 0.5, 0.95, 0.6, 0.3, 0.7, 0.85, 0.4],
    signature: '精忠报国。',
    bio: '字鹏举，相州汤阴人。少时家贫，从周侗学武。宗泽部下，屡破金兵。岳家军令出如山，金人叹「撼山易，撼岳家军难」。',
    portrait: 'portraits/east-statesman/yuefei.svg',
    matchBlurb: '汝与 {{name}} 同，以忠义为骨，以军旅为家。',
    anecdotes: [
      { title: '精忠报国', body: '母刺其背「精忠报国」四字。' },
      { title: '风波亭', body: '为秦桧所害，年三十九。' },
    ],
    echoes: ['es-wentianxiang', 'es-haigui', 'es-zhuge'],
  },
  {
    id: 'es-linze',
    name: '林则徐',
    era: '清',
    domain: 'east-statesman',
    vector: [0.78, 0.55, 0.85, 0.75, 0.8, 0.45, 0.92, 0.75, 0.4, 0.55, 0.78, 0.5],
    signature: '苟利国家生死以，岂因祸福避趋之。',
    bio: '字元抚，又字少穆、石麟，福建侯官人。湖广总督时禁烟。虎门销烟，名震天下。后谪戍伊犁，犹兴修水利。',
    portrait: 'portraits/east-statesman/linze.svg',
    matchBlurb: '汝与 {{name}} 同，知其不可而为之，心系苍生。',
    anecdotes: [
      { title: '虎门销烟', body: '1839 年 6 月 3 日起，虎门海滩销鸦片 237 万斤。' },
      { title: '谪戍伊犁', body: '戍伊犁途中作「苟利国家生死以，岂因祸福避趋之」。' },
    ],
    echoes: ['es-haigui', 'es-haigui', 'es-wentianxiang'],
  },

  // ── C 中段：稳健 + 守正 + 中庸 ──
  {
    id: 'es-xiaohe',
    name: '萧何',
    era: '西汉',
    domain: 'east-statesman',
    vector: [0.6, 0.5, 0.6, 0.5, 0.7, 0.4, 0.65, 0.8, 0.5, 0.55, 0.55, 0.4],
    signature: '月下追韩信。',
    bio: '沛县人。初为沛吏，从刘邦起义。荐韩信、举贤才、治关中补给。',
    portrait: 'portraits/east-statesman/xiaohe.svg',
    matchBlurb: '汝与 {{name}} 同，能识人用人，幕后安定。',
    anecdotes: [
      { title: '月下追韩信', body: '闻韩信亡，萧何不及告刘邦，连夜追之，刘邦始信。' },
      { title: '制九章律', body: '汉初法制多出其手。' },
    ],
    echoes: ['es-fangxuanling', 'es-zhuge', 'es-zhoucheng'],
  },
  {
    id: 'es-fangxuanling',
    name: '房玄龄',
    era: '唐',
    domain: 'east-statesman',
    vector: [0.65, 0.5, 0.6, 0.5, 0.7, 0.5, 0.7, 0.85, 0.55, 0.55, 0.5, 0.55],
    signature: '孜孜为国，知无不为。',
    bio: '字乔，齐州临淄人。隋时举进士，谪归。佐李世民定天下。相太宗二十载，与杜如晦并称「房谋杜断」。',
    portrait: 'portraits/east-statesman/fangxuanling.svg',
    matchBlurb: '汝与 {{name}} 同，能谋善断，佐盛世之治。',
    anecdotes: [
      { title: '房谋杜断', body: '房玄龄善谋，杜如晦善断，唐初良相。' },
      { title: '修五代史', body: '主修梁、陈、北齐、北周、隋五代史。' },
    ],
    echoes: ['es-xiaohe', 'es-weizheng', 'es-zhuge'],
  },
  {
    id: 'es-weizheng',
    name: '魏徵',
    era: '唐',
    domain: 'east-statesman',
    vector: [0.78, 0.55, 0.65, 0.65, 0.7, 0.45, 0.85, 0.85, 0.4, 0.6, 0.6, 0.65],
    signature: '以人为镜，可以明得失。',
    bio: '字玄成，魏州曲城人。少孤出家。初事太子李建成，后佐太宗。敢谏，前后二百余事。',
    portrait: 'portraits/east-statesman/weizheng.svg',
    matchBlurb: '汝与 {{name}} 同，能以直声辅盛世，知无不言。',
    anecdotes: [
      { title: '十渐不克终', body: '上疏论太宗「十渐」，太宗嘉纳之。' },
      { title: '以人为镜', body: '太宗谓「以人为镜」即魏徵。' },
    ],
    echoes: ['es-fangxuanling', 'es-fanzhongyan', 'es-haigui'],
  },
  {
    id: 'es-wentianxiang',
    name: '文天祥',
    era: '宋',
    domain: 'east-statesman',
    vector: [0.75, 0.65, 0.65, 0.6, 0.85, 0.5, 0.95, 0.8, 0.4, 0.75, 0.7, 0.7],
    signature: '人生自古谁无死，留取丹心照汗青。',
    bio: '字宋瑞，一字履善，号文山。吉州庐陵人。宝祐四年状元。起兵抗元，兵败被执，作《过零丁洋》《正气歌》。',
    portrait: 'portraits/east-statesman/wentianxiang.svg',
    matchBlurb: '汝与 {{name}} 同，知其不可而守其节，不以死生易志。',
    anecdotes: [
      { title: '正气歌', body: '狱中所作「天地有正气，杂然赋流形」，千古名篇。' },
      { title: '从容就义', body: '大都柴市就义，年四十七。' },
    ],
    echoes: ['es-yuefei', 'es-haigui', 'es-zhuge'],
  },
  {
    id: 'es-haigui',
    name: '海瑞',
    era: '明',
    domain: 'east-statesman',
    vector: [0.7, 0.4, 0.7, 0.7, 0.7, 0.4, 0.95, 0.65, 0.4, 0.6, 0.65, 0.45],
    signature: '天下事，无一不可对人言。',
    bio: '字汝贤，号刚峰，广东琼山人。举人出身。任户部主事时上《治安疏》骂嘉靖。复出后清丈田亩、推行一条鞭法。',
    portrait: 'portraits/east-statesman/haigui.svg',
    matchBlurb: '汝与 {{name}} 同，直道而行，宁折不弯。',
    anecdotes: [
      { title: '骂嘉靖', body: '上《治安疏》直骂嘉靖帝「家家皆净而无财用」，下狱几死。' },
      { title: '备棺上疏', body: '自知触帝怒，预先备好棺材。' },
    ],
    echoes: ['es-weizheng', 'es-yuefei', 'es-linze'],
  },
  {
    id: 'es-liangqichao',
    name: '梁启超',
    era: '清',
    domain: 'east-statesman',
    vector: [0.75, 0.6, 0.65, 0.75, 0.7, 0.5, 0.7, 0.95, 0.5, 0.55, 0.6, 0.8],
    signature: '十年饮冰，难凉热血。',
    bio: '字卓如，号任公，广东新会人。师康有为，倡维新。流亡日本，办《清议报》《新民丛报》。',
    portrait: 'portraits/east-statesman/liangqichao.svg',
    matchBlurb: '汝与 {{name}} 同，思以新民而新国，文以载道。',
    anecdotes: [
      { title: '《时务报》', body: '主笔《时务报》，鼓吹维新。' },
      { title: '饮冰室主人', body: '天津饮冰室著书立说，著作等身。' },
    ],
    echoes: ['es-kangyouwei', 'es-zhangqiu', 'es-sunyatsen'],
  },

  // ── D 偏内：内省 + 处世 + 务实 ──
  {
    id: 'es-zhangliang',
    name: '张良',
    era: '西汉',
    domain: 'east-statesman',
    vector: [0.7, 0.5, 0.4, 0.5, 0.6, 0.5, 0.6, 0.9, 0.7, 0.7, 0.4, 0.5],
    signature: '愿弃人间事，欲从赤松子游。',
    bio: '字子房，韩国人。祖、父五世相韩。秦灭韩，刺客击始皇未中。圯桥受书，佐刘邦定天下。',
    portrait: 'portraits/east-statesman/zhangliang.svg',
    matchBlurb: '汝与 {{name}} 同，能于乱世全身而退，知止而后有定。',
    anecdotes: [
      { title: '圯桥授书', body: '下邳圯桥遇黄石公，受《太公兵法》。' },
      { title: '辞封万户', body: '佐汉定天下后，专意修道。' },
    ],
    echoes: ['es-xiaohe', 'es-fanli', 'es-zhou'],
  },
  {
    id: 'es-direnjie',
    name: '狄仁杰',
    era: '武周',
    domain: 'east-statesman',
    vector: [0.7, 0.5, 0.55, 0.55, 0.6, 0.45, 0.7, 0.95, 0.55, 0.55, 0.5, 0.5],
    signature: '以周兴亡为镜，可以明得失。',
    bio: '字怀英，山西太原人。举明经。初任大理寺丞，一年中断狱 17000 人，无冤诉。相武则天，再兴唐室。',
    portrait: 'portraits/east-statesman/direnjie.svg',
    matchBlurb: '汝与 {{name}} 同，明察秋毫，处事周全。',
    anecdotes: [
      { title: '一年断狱', body: '一年断案一万七千，无一冤诉。' },
      { title: '复唐之功', body: '保李氏、荐张柬之，促武则天还政于唐。' },
    ],
    echoes: ['es-fangxuanling', 'es-weizheng', 'es-xujie'],
  },
  {
    id: 'es-xujie',
    name: '徐阶',
    era: '明',
    domain: 'east-statesman',
    vector: [0.78, 0.5, 0.5, 0.55, 0.7, 0.5, 0.8, 0.85, 0.55, 0.6, 0.55, 0.65],
    signature: '能屈能伸。',
    bio: '字子升，号少湖，上海华亭人。嘉靖朝为相。隐忍多年，最终扳倒严嵩。后培养张居正。',
    portrait: 'portraits/east-statesman/xujie.svg',
    matchBlurb: '汝与 {{name}} 同，能屈能伸，知机而动。',
    anecdotes: [
      { title: '计除严嵩', body: '以孙女嫁严世蕃，设计扳倒严嵩。' },
      { title: '一纸三都', body: '门生故吏遍天下。' },
    ],
    echoes: ['es-zhangqiu', 'es-fan', 'es-direnjie'],
  },
  {
    id: 'es-zhangzhidong',
    name: '张之洞',
    era: '清',
    domain: 'east-statesman',
    vector: [0.7, 0.55, 0.55, 0.65, 0.7, 0.5, 0.7, 0.9, 0.6, 0.6, 0.55, 0.7],
    signature: '中学为体，西学为用。',
    bio: '字孝达，号香帅，直隶南皮人。晚清四大名臣之一。办洋务、兴实业、开学堂，主持《奏定学堂章程》。',
    portrait: 'portraits/east-statesman/zhangzhidong.svg',
    matchBlurb: '汝与 {{name}} 同，能融汇古今，缓图新变。',
    anecdotes: [
      { title: '中体西用', body: '「中学为体，西学为用」晚清洋务思想核心。' },
      { title: '汉阳造', body: '主持创办汉阳铁厂、湖北织布局。' },
    ],
    echoes: ['es-li', 'es-zhangqiu', 'es-liangqichao'],
  },
  {
    id: 'es-lihongzhang',
    name: '李鸿章',
    era: '清',
    domain: 'east-statesman',
    vector: [0.75, 0.5, 0.65, 0.55, 0.55, 0.45, 0.75, 0.85, 0.5, 0.5, 0.7, 0.6],
    signature: '一代人办一代事。',
    bio: '字少荃，安徽合肥人。师曾国藩，办淮军。任直隶总督、北洋大臣，主持洋务。',
    portrait: 'portraits/east-statesman/lihongzhang.svg',
    matchBlurb: '汝与 {{name}} 同，能在夹缝中求实事。',
    anecdotes: [
      { title: '淮军', body: '仿湘军制办淮军，平捻军主力。' },
      { title: '签马关', body: '1895 年签《马关条约》，背负骂名。' },
    ],
    echoes: ['es-zhangzhidong', 'es-zuo', 'es-zuo'],
  },
  {
    id: 'es-zhou',
    name: '周公',
    era: '西周',
    domain: 'east-statesman',
    vector: [0.7, 0.6, 0.5, 0.55, 0.8, 0.5, 0.85, 0.95, 0.6, 0.75, 0.5, 0.7],
    signature: '周监于二代，郁郁乎文哉！',
    bio: '姬旦，文王之子，武王之弟。辅武王伐纣。制礼作乐，分封诸侯，天下归心。',
    portrait: 'portraits/east-statesman/zhou.svg',
    matchBlurb: '汝与 {{name}} 同，能以礼乐化天下，不言而教。',
    anecdotes: [
      { title: '周公吐哺', body: '一沐三握发，一饭三吐哺，起以待士。' },
      { title: '制礼作乐', body: '奠定中华礼乐文明基础。' },
    ],
    echoes: ['es-yi', 'es-fan', 'es-zhuge'],
  },

  // ── E 极端内：稳健 + 处世 + 长虑 ──
  {
    id: 'es-yi',
    name: '伊尹',
    era: '商',
    domain: 'east-statesman',
    vector: [0.4, 0.4, 0.3, 0.35, 0.7, 0.4, 0.65, 0.95, 0.85, 0.85, 0.3, 0.5],
    signature: '调和鼎鼐，燮理阴阳。',
    bio: '名挚。夏末有莘氏之媵臣。负鼎俎以滋味说汤，致于王道。相汤、外丙、仲壬、太甲四朝。',
    portrait: 'portraits/east-statesman/yi.svg',
    matchBlurb: '汝与 {{name}} 同，能以调和之道安天下，不争而治。',
    anecdotes: [
      { title: '负鼎俎', body: '负鼎俎以滋味说汤。' },
      { title: '放太甲', body: '太甲不明，伊尹放之于桐宫三年。' },
    ],
    echoes: ['es-zhou', 'es-fanli', 'es-zhou'],
  },
  {
    id: 'es-fanli',
    name: '范蠡',
    era: '春秋',
    domain: 'east-statesman',
    vector: [0.5, 0.5, 0.5, 0.6, 0.6, 0.5, 0.7, 0.85, 0.85, 0.7, 0.6, 0.5],
    signature: '飞鸟尽，良弓藏；狡兔死，走狗烹。',
    bio: '字少伯，楚国宛人。佐越王勾践十年生聚、十年教训，灭吴。功成后泛舟五湖，称「陶朱公」经商。',
    portrait: 'portraits/east-statesman/fanli.svg',
    matchBlurb: '汝与 {{name}} 同，能全身而退，功成不居。',
    anecdotes: [
      { title: '勾践灭吴', body: '十年生聚，十年教训，辅勾践灭吴。' },
      { title: '三致千金', body: '改名「陶朱公」后，三致千金。' },
    ],
    echoes: ['es-zhangliang', 'es-yi', 'es-zuo'],
  },
  {
    id: 'es-zuo',
    name: '左宗棠',
    era: '清',
    domain: 'east-statesman',
    vector: [0.55, 0.5, 0.7, 0.7, 0.6, 0.45, 0.9, 0.75, 0.7, 0.65, 0.7, 0.45],
    signature: '抬棺出关。',
    bio: '字季高，湖南湘阴人。晚清四大名臣之一。平太平天国、捻军。督办新疆军务，抬棺出嘉峪关，收复新疆。',
    portrait: 'portraits/east-statesman/zuo.svg',
    matchBlurb: '汝与 {{name}} 同，能以暮年赴边关，知其不可犹为之。',
    anecdotes: [
      { title: '抬棺出关', body: '六十三岁抬棺出嘉峪关，收复新疆。' },
      { title: '收复新疆', body: '平阿古柏、收伊犁，西北重归版图。' },
    ],
    echoes: ['es-linze', 'es-haigui', 'es-yuefei'],
  },
  {
    id: 'es-sunyatsen',
    name: '孙中山',
    era: '民国',
    domain: 'east-statesman',
    vector: [0.6, 0.6, 0.6, 0.85, 0.7, 0.5, 0.9, 0.85, 0.5, 0.65, 0.85, 0.6],
    signature: '天下为公。',
    bio: '名文，字德明，号日新，后改逸仙。广东香山人。倡三民主义，领导辛亥革命，终结帝制。',
    portrait: 'portraits/east-statesman/sunyatsen.svg',
    matchBlurb: '汝与 {{name}} 同，能以信念撼千年之局，知其不可犹为之。',
    anecdotes: [
      { title: '驱除鞑虏', body: '领导辛亥革命，终结两千余年帝制。' },
      { title: '三民主义', body: '民族、民权、民生，三大主义。' },
    ],
    echoes: ['es-kangyouwei', 'es-zhangqiu', 'es-haigui'],
  },
  {
    id: 'es-liubow',
    name: '刘伯温',
    era: '明',
    domain: 'east-statesman',
    vector: [0.6, 0.45, 0.5, 0.6, 0.6, 0.5, 0.7, 0.9, 0.7, 0.7, 0.55, 0.55],
    signature: '三分天下诸葛亮，一统江山刘伯温。',
    bio: '名基，字伯温，浙江青田人。元末进士，弃官隐居。佐朱元璋灭陈友谅、张士诚，北伐中原。',
    portrait: 'portraits/east-statesman/liubow.svg',
    matchBlurb: '汝与 {{name}} 同，能洞察先机，谋定而后动。',
    anecdotes: [
      { title: '烧饼歌', body: '传说预言后世之事，民间称「烧饼歌」。' },
      { title: '佐朱灭元', body: '佐朱元璋统一天下。' },
    ],
    echoes: ['es-zhuge', 'es-zhangliang', 'es-fanju'],
  },
  {
    id: 'es-jiang',
    name: '姜尚',
    era: '周',
    domain: 'east-statesman',
    vector: [0.5, 0.4, 0.6, 0.7, 0.5, 0.5, 0.8, 0.85, 0.85, 0.85, 0.7, 0.4],
    signature: '愿者上钩。',
    bio: '姜姓，吕氏，名尚，字子牙，号太公望。年八十垂钓渭水，文王载与俱归，武王尊为「师尚父」。佐武王灭纣。',
    portrait: 'portraits/east-statesman/jiang.svg',
    matchBlurb: '汝与 {{name}} 同，能以一生待一遇，知命而不争。',
    anecdotes: [
      { title: '直钩钓王', body: '渭水垂钓，鱼钩离水三寸，愿者上钩。' },
      { title: '封神榜', body: '《封神演义》以其为背景，托名所作。' },
    ],
    echoes: ['es-yi', 'es-zhou', 'es-zhangliang'],
  },
];
