// 镜心 · 科技先贤 · 30 人
// 12 维向量分布：30 人 = 5 区段 × 6 人
//   A 极端外：思辨 ≥ 0.85 / 革新 ≥ 0.85 / 学识 ≥ 0.90 ── 蔡伦、张衡、祖冲之、毕昇、宋应星、徐光启
//   B 偏外：思辨 0.65-0.85 ── 沈括、郭守敬、黄道婆、李时珍、贾思勰、徐霞客
//   C 中段：0.40-0.60 ── 张仲景、华佗、孙思邈、裴秀、苏颂、李诫
//   D 偏内：思辨 0.20-0.40 ── 扁鹊、葛洪、郦道元、一行、秦九韶、鲁班
//   E 极端内：思辨 ≤ 0.20 ── 欧冶子、干将、马钧、竺可桢、茅以升、詹天佑

import type { Figure } from './figure.types';

export const FIGURES_EAST_SCIENTIST: readonly Figure[] = [
  // ── A 极端外：发现 / 发明 / 革新 / 大胆 ──
  {
    id: 'esci-cailun',
    name: '蔡伦',
    era: '汉',
    domain: 'east-scientist',
    vector: [0.92, 0.4, 0.88, 0.95, 0.5, 0.35, 0.85, 0.95, 0.4, 0.6, 0.85, 0.4],
    signature: '蔡侯纸，千年利。',
    bio: '字敬仲，桂阳人。东汉宦官。公元 105 年改进造纸术，废缣帛，以树皮麻头破布造纸，号「蔡侯纸」。',
    portrait: 'portraits/east-scientist/cailun.svg',
    matchBlurb: '汝与 {{name}} 同，以巧手易天下，能化腐朽为神奇。',
    anecdotes: [
      {
        title: '造纸',
        body: '改进西汉已有麻纸，以树皮、麻头、破布为原料，造出薄而韧的「蔡侯纸」。',
      },
      { title: '封侯', body: '造纸有功，封龙亭侯。' },
    ],
    echoes: ['esci-bi', 'esci-huang', 'esci-song'],
  },
  {
    id: 'esci-zhangheng',
    name: '张衡',
    era: '汉',
    domain: 'east-scientist',
    vector: [0.95, 0.45, 0.85, 0.9, 0.45, 0.55, 0.8, 0.98, 0.4, 0.65, 0.8, 0.65],
    signature: '候风地动，万里无差。',
    bio: '字平子，南阳人。东汉太史令。制浑天仪、地动仪、候风仪。著《灵宪》《西京赋》。',
    portrait: 'portraits/east-scientist/zhangheng.svg',
    matchBlurb: '汝与 {{name}} 同，仰观天文，俯察地理，能以器契天。',
    anecdotes: [
      { title: '地动仪', body: '公元 132 年造地动仪，八龙衔珠，测震方位。' },
      { title: '浑天仪', body: '以水力驱动，模拟天体运行。' },
    ],
    echoes: ['esci-cailun', 'esci-zu', 'esci-shen'],
  },
  {
    id: 'esci-zu',
    name: '祖冲之',
    era: '南北朝',
    domain: 'east-scientist',
    vector: [0.95, 0.4, 0.8, 0.9, 0.4, 0.5, 0.85, 0.98, 0.35, 0.7, 0.8, 0.55],
    signature: '圆率三五四一五九二。',
    bio: '字文远，范阳人。南北朝数学家、天文学家。算出圆周率 3.1415926-3.1415927 之间，领先欧洲千年。',
    portrait: 'portraits/east-scientist/zu.svg',
    matchBlurb: '汝与 {{name}} 同，能于毫厘之间求至理，致广大而尽精微。',
    anecdotes: [
      { title: '圆周率', body: '算出 π 介于 3.1415926 与 3.1415927 之间。' },
      { title: '大明历', body: '编《大明历》，首次引入「岁差」。' },
    ],
    echoes: ['esci-zhangheng', 'esci-qin', 'esci-shen'],
  },
  {
    id: 'esci-bi',
    name: '毕昇',
    era: '宋',
    domain: 'east-scientist',
    vector: [0.9, 0.4, 0.85, 0.95, 0.5, 0.4, 0.8, 0.95, 0.4, 0.55, 0.8, 0.45],
    signature: '不以木活字，惟胶泥为之。',
    bio: '北宋平民，雕版印刷工。庆历年间（约 1041-1048）发明泥活字印刷术。',
    portrait: 'portraits/east-scientist/bi.svg',
    matchBlurb: '汝与 {{name}} 同，能以小技易千古之法。',
    anecdotes: [
      { title: '泥活字', body: '以胶泥刻字，火烧令坚，排版印刷。' },
      { title: '未受重赏', body: '生平不详，活字术至元代才广泛应用。' },
    ],
    echoes: ['esci-cailun', 'esci-song', 'esci-li'],
  },
  {
    id: 'esci-song',
    name: '宋应星',
    era: '明',
    domain: 'east-scientist',
    vector: [0.92, 0.4, 0.85, 0.92, 0.5, 0.4, 0.85, 0.98, 0.4, 0.7, 0.8, 0.55],
    signature: '天覆地载，物穷其理。',
    bio: '字长庚，江西奉新人。明万历举人。著《天工开物》，系统记述农业、手工业技术，被誉为「中国 17 世纪工艺百科全书」。',
    portrait: 'portraits/east-scientist/song.svg',
    matchBlurb: '汝与 {{name}} 同，能于百工之中见大道。',
    anecdotes: [
      { title: '天工开物', body: '全书 18 卷，附 121 幅插图，详述百工技艺。' },
      { title: '海外流传', body: '传入日本、朝鲜、欧洲，影响深远。' },
    ],
    echoes: ['esci-xu', 'esci-jia', 'esci-li'],
  },
  {
    id: 'esci-xu',
    name: '徐光启',
    era: '明',
    domain: 'east-scientist',
    vector: [0.9, 0.4, 0.85, 0.9, 0.5, 0.45, 0.85, 0.98, 0.4, 0.7, 0.8, 0.6],
    signature: '欲求超胜，必须会通。',
    bio: '字子先，号玄扈，上海人。明万历进士。译《几何原本》前六卷，著《农政全书》。',
    portrait: 'portraits/east-scientist/xu.svg',
    matchBlurb: '汝与 {{name}} 同，能融汇中西，致知于用。',
    anecdotes: [
      { title: '几何原本', body: '与利玛窦合译欧几里得《几何原本》前六卷。' },
      { title: '农政全书', body: '60 卷，系统总结传统农学并融入西学。' },
    ],
    echoes: ['esci-song', 'esci-bi', 'esci-zhan'],
  },

  // ── B 偏外 ──
  {
    id: 'esci-shen',
    name: '沈括',
    era: '宋',
    domain: 'east-scientist',
    vector: [0.85, 0.5, 0.75, 0.8, 0.5, 0.5, 0.8, 0.98, 0.45, 0.7, 0.7, 0.65],
    signature: '以己之不知为不知。',
    bio: '字存中，钱塘人。北宋科学家、政治家。著《梦溪笔谈》，涉天文、数学、地理、物理、生物、医、药、文学等。',
    portrait: 'portraits/east-scientist/shen.svg',
    matchBlurb: '汝与 {{name}} 同，能格物致知，博而能精。',
    anecdotes: [
      { title: '梦溪笔谈', body: '笔记体著作 26 卷加补笔谈 3 卷、续笔谈 1 卷。' },
      { title: '活字印刷', body: '《笔谈》详记毕昇泥活字术。' },
    ],
    echoes: ['esci-bi', 'esci-song', 'esci-guo'],
  },
  {
    id: 'esci-guo',
    name: '郭守敬',
    era: '元',
    domain: 'east-scientist',
    vector: [0.88, 0.4, 0.8, 0.85, 0.4, 0.5, 0.85, 0.98, 0.4, 0.7, 0.8, 0.55],
    signature: '历之本在于测验，测验之器莫先仪表。',
    bio: '字若思，邢台人。元代天文学家、水利专家。制简仪、高表等十余种天文仪器，编《授时历》。',
    portrait: 'portraits/east-scientist/guo.svg',
    matchBlurb: '汝与 {{name}} 同，能以器契天，测万物之理。',
    anecdotes: [
      { title: '简仪', body: '简化浑仪，便于观测。' },
      { title: '授时历', body: '一年为 365.2425 日，与现行公历相同，但早 300 年。' },
    ],
    echoes: ['esci-zhangheng', 'esci-yi', 'esci-shen'],
  },
  {
    id: 'esci-huang',
    name: '黄道婆',
    era: '元',
    domain: 'east-scientist',
    vector: [0.8, 0.5, 0.85, 0.85, 0.55, 0.4, 0.85, 0.85, 0.45, 0.55, 0.75, 0.4],
    signature: '衣被天下。',
    bio: '松江乌泥泾人。少年流落崖州（今海南），从黎族习纺织技术。晚年返乡，推广搅车、弹弓、纺车、织机，使松江棉布甲天下。',
    portrait: 'portraits/east-scientist/huang.svg',
    matchBlurb: '汝与 {{name}} 同，能以一技养民，惠及天下。',
    anecdotes: [
      { title: '搅车', body: '去棉籽之具，日可处理百斤。' },
      { title: '衣被天下', body: '松江棉布「被服天下」，黄道婆被尊为「先棉」。' },
    ],
    echoes: ['esci-cailun', 'esci-bi', 'esci-jia'],
  },
  {
    id: 'esci-li',
    name: '李时珍',
    era: '明',
    domain: 'east-scientist',
    vector: [0.85, 0.5, 0.75, 0.85, 0.5, 0.5, 0.9, 0.98, 0.45, 0.8, 0.75, 0.6],
    signature: '医者贵在格物。',
    bio: '字东璧，号濒湖，湖北蕲春人。明代医药学家。历 27 年著《本草纲目》，载药 1892 种，方 11096 首。',
    portrait: 'portraits/east-scientist/li.svg',
    matchBlurb: '汝与 {{name}} 同，能以身试药，格物穷理。',
    anecdotes: [
      { title: '本草纲目', body: '190 万字，载药 1892 种，插图 1109 幅。' },
      { title: '东方药典', body: '传入日本、朝鲜、欧洲，被达尔文引用。' },
    ],
    echoes: ['esci-jia', 'esci-xu', 'esci-shen'],
  },
  {
    id: 'esci-jia',
    name: '贾思勰',
    era: '北魏',
    domain: 'east-scientist',
    vector: [0.78, 0.5, 0.7, 0.8, 0.5, 0.4, 0.8, 0.95, 0.4, 0.7, 0.7, 0.5],
    signature: '顺天时，量地利，则用力少而成功多。',
    bio: '山东益都人。北魏农学家。著《齐民要术》，中国现存最完整农书。',
    portrait: 'portraits/east-scientist/jia.svg',
    matchBlurb: '汝与 {{name}} 同，能于稼穑之中见大道。',
    anecdotes: [
      { title: '齐民要术', body: '10 卷 92 篇，涵盖农、林、牧、副、渔。' },
      { title: '酒醋酿造', body: '详述 30 余种酿造法。' },
    ],
    echoes: ['esci-xu', 'esci-li', 'esci-song'],
  },
  {
    id: 'esci-xuxiake',
    name: '徐霞客',
    era: '明',
    domain: 'east-scientist',
    vector: [0.85, 0.6, 0.7, 0.7, 0.4, 0.7, 0.85, 0.95, 0.4, 0.85, 0.85, 0.85],
    signature: '大丈夫当朝碧海而暮苍梧。',
    bio: '名弘祖，字振之，号霞客，江苏江阴人。明代地理学家、旅行家。30 余年游历 16 省，著《徐霞客游记》。',
    portrait: 'portraits/east-scientist/xuxiake.svg',
    matchBlurb: '汝与 {{name}} 同，能以足代笔，志在山河。',
    anecdotes: [
      { title: '游历', body: '30 余年游历，足迹遍 16 省。' },
      { title: '探溶洞', body: '对喀斯特地貌记述领先欧洲近 300 年。' },
    ],
    echoes: ['esci-xuxiake', 'esci-pei', 'esci-li'],
  },

  // ── C 中段 ──
  {
    id: 'esci-zhang',
    name: '张仲景',
    era: '汉',
    domain: 'east-scientist',
    vector: [0.75, 0.5, 0.6, 0.6, 0.6, 0.4, 0.8, 0.95, 0.5, 0.7, 0.6, 0.55],
    signature: '勤求古训，博采众方。',
    bio: '名机，南阳人。东汉医学家。著《伤寒杂病论》，确立辨证论治原则，奠基中医临床。',
    portrait: 'portraits/east-scientist/zhang.svg',
    matchBlurb: '汝与 {{name}} 同，能以仁心度人，传方于世。',
    anecdotes: [
      { title: '伤寒论', body: '397 法 113 方，为后世中医经典。' },
      { title: '医圣', body: '后世尊为「医圣」。' },
    ],
    echoes: ['esci-sun', 'esci-bianque', 'esci-huatuo'],
  },
  {
    id: 'esci-huatuo',
    name: '华佗',
    era: '汉',
    domain: 'east-scientist',
    vector: [0.7, 0.5, 0.7, 0.8, 0.5, 0.5, 0.8, 0.95, 0.5, 0.65, 0.75, 0.55],
    signature: '医者，意也。',
    bio: '字元化，沛国谯人。东汉医学家。精通内、妇、儿、针灸各科。创「麻沸散」为手术麻醉剂。',
    portrait: 'portraits/east-scientist/huatuo.svg',
    matchBlurb: '汝与 {{name}} 同，能以巧手夺天工，敢为天下先。',
    anecdotes: [
      { title: '麻沸散', body: '世界最早全身麻醉剂，早西方 1600 余年。' },
      { title: '五禽戏', body: '创编导引术，仿虎鹿熊猿鸟。' },
    ],
    echoes: ['esci-zhang', 'esci-sun', 'esci-bianque'],
  },
  {
    id: 'esci-sun',
    name: '孙思邈',
    era: '唐',
    domain: 'east-scientist',
    vector: [0.78, 0.5, 0.6, 0.65, 0.7, 0.5, 0.8, 0.98, 0.6, 0.85, 0.6, 0.6],
    signature: '大医精诚。',
    bio: '京兆华原人。唐代医学家。著《千金要方》《千金翼方》，被誉为「药王」。',
    portrait: 'portraits/east-scientist/sun.svg',
    matchBlurb: '汝与 {{name}} 同，能以大慈恻隐之心，普救含灵之苦。',
    anecdotes: [
      { title: '千金要方', body: '30 卷 232 门，5300 余方。' },
      { title: '大医精诚', body: '论医德千古名篇。' },
    ],
    echoes: ['esci-zhang', 'esci-bianque', 'esci-li'],
  },
  {
    id: 'esci-pei',
    name: '裴秀',
    era: '晋',
    domain: 'east-scientist',
    vector: [0.8, 0.5, 0.6, 0.7, 0.4, 0.5, 0.75, 0.95, 0.45, 0.7, 0.6, 0.55],
    signature: '制图六体。',
    bio: '字季彦，河东闻喜人。魏晋时期地图学家。创立「制图六体」理论，绘《禹贡地域图》。',
    portrait: 'portraits/east-scientist/pei.svg',
    matchBlurb: '汝与 {{name}} 同，能以方寸之图见万里之遥。',
    anecdotes: [
      { title: '制图六体', body: '分率、准望、道里、高下、方邪、迂直，世界最早制图理论。' },
      { title: '禹贡地域图', body: '18 幅，详载九州地理。' },
    ],
    echoes: ['esci-guo', 'esci-xuxiake', 'esci-li'],
  },
  {
    id: 'esci-su',
    name: '苏颂',
    era: '宋',
    domain: 'east-scientist',
    vector: [0.82, 0.5, 0.6, 0.7, 0.4, 0.55, 0.75, 0.98, 0.4, 0.7, 0.6, 0.55],
    signature: '以水为动力。',
    bio: '字子容，泉州人。北宋天文学家、机械工程师。主持造水运仪象台，集天文观测、演示、报时于一体。',
    portrait: 'portraits/east-scientist/su.svg',
    matchBlurb: '汝与 {{name}} 同，能以水转之器模拟天行。',
    anecdotes: [
      { title: '水运仪象台', body: '高约 12 米，集观测、演示、报时于一体。' },
      { title: '擒纵器', body: '现代机械钟表的先驱。' },
    ],
    echoes: ['esci-zhangheng', 'esci-guo', 'esci-ma'],
  },
  {
    id: 'esci-lijie',
    name: '李诫',
    era: '宋',
    domain: 'east-scientist',
    vector: [0.75, 0.55, 0.65, 0.6, 0.5, 0.7, 0.75, 0.95, 0.5, 0.7, 0.55, 0.55],
    signature: '经营造作，有规有矩。',
    bio: '字明仲，郑州管城人。北宋建筑学家。著《营造法式》，中国第一本完整建筑技术书籍。',
    portrait: 'portraits/east-scientist/lijie.svg',
    matchBlurb: '汝与 {{name}} 同，能于斧凿之间见矩度。',
    anecdotes: [
      { title: '营造法式', body: '34 卷，详述建筑规范、用料、构件。' },
      { title: '材份制', body: '以「材」为模数，标准化构件。' },
    ],
    echoes: ['esci-luban', 'esci-song', 'esci-xu'],
  },

  // ── D 偏内 ──
  {
    id: 'esci-bianque',
    name: '扁鹊',
    era: '春秋',
    domain: 'east-scientist',
    vector: [0.65, 0.5, 0.55, 0.55, 0.7, 0.5, 0.75, 0.95, 0.6, 0.7, 0.5, 0.55],
    signature: '望闻问切。',
    bio: '姓秦，名缓，字越人，渤海郡人。战国医学家。中医脉学之祖，「望闻问切」四诊法奠基人。',
    portrait: 'portraits/east-scientist/bianque.svg',
    matchBlurb: '汝与 {{name}} 同，能以四诊合参，洞察脏腑。',
    anecdotes: [
      { title: '望齐桓侯', body: '仅凭面色判断疾病由浅入深四阶段。' },
      { title: '起死回生', body: '针刺三阳五会，救活「死人」虢太子。' },
    ],
    echoes: ['esci-zhang', 'esci-sun', 'esci-huatuo'],
  },
  {
    id: 'esci-ge',
    name: '葛洪',
    era: '晋',
    domain: 'east-scientist',
    vector: [0.7, 0.5, 0.55, 0.6, 0.4, 0.5, 0.7, 0.95, 0.7, 0.85, 0.55, 0.55],
    signature: '神仙可学，不死可致。',
    bio: '字稚川，号抱朴子，丹阳句容人。东晋道教理论家、医学家、化学家。著《抱朴子》《肘后备急方》。',
    portrait: 'portraits/east-scientist/ge.svg',
    matchBlurb: '汝与 {{name}} 同，能于方外之术见真知。',
    anecdotes: [
      { title: '炼丹', body: '炼丹中发现化学反应，「丹砂烧之成水银，积变又还成丹砂」。' },
      { title: '肘后备急', body: '应急医方集，验便廉。' },
    ],
    echoes: ['esci-bianque', 'esci-yi', 'esci-zhang'],
  },
  {
    id: 'esci-lidaoyu',
    name: '郦道元',
    era: '北魏',
    domain: 'east-scientist',
    vector: [0.78, 0.5, 0.55, 0.55, 0.5, 0.55, 0.7, 0.95, 0.55, 0.75, 0.55, 0.6],
    signature: '山水有灵，亦通经史。',
    bio: '字善长，范阳涿州人。北魏地理学家。著《水经注》，为《水经》作注 40 卷，详述 1252 条河流。',
    portrait: 'portraits/east-scientist/lidaoyu.svg',
    matchBlurb: '汝与 {{name}} 同，能以文心映山水，注水以成经。',
    anecdotes: [
      { title: '水经注', body: '40 卷，1252 条河流。' },
      { title: '郦道元笔下三峡', body: '自三峡七百里中，两岸连山，略无阙处。' },
    ],
    echoes: ['esci-xuxiake', 'esci-pei', 'esci-li'],
  },
  {
    id: 'esci-yi',
    name: '一行',
    era: '唐',
    domain: 'east-scientist',
    vector: [0.78, 0.5, 0.55, 0.65, 0.4, 0.6, 0.7, 0.95, 0.6, 0.7, 0.5, 0.5],
    signature: '以天为镜。',
    bio: '俗名张遂，魏州昌乐人。唐代高僧、天文学家。主持编制《大衍历》，测子午线一度之距。',
    portrait: 'portraits/east-scientist/yi.svg',
    matchBlurb: '汝与 {{name}} 同，能以禅心契天文。',
    anecdotes: [
      { title: '大衍历', body: '首次正确处理不等间距二次差内插法。' },
      { title: '测子午线', body: '在 12 处观测北极高度，算出子午线一度约 132.03 公里。' },
    ],
    echoes: ['esci-guo', 'esci-zhangheng', 'esci-shen'],
  },
  {
    id: 'esci-qin',
    name: '秦九韶',
    era: '宋',
    domain: 'east-scientist',
    vector: [0.85, 0.5, 0.55, 0.6, 0.4, 0.5, 0.7, 0.98, 0.5, 0.7, 0.55, 0.55],
    signature: '数术穷天地。',
    bio: '字道古，四川人。南宋数学家。著《数书九章》，提出「大衍求一术」（中国剩余定理）。',
    portrait: 'portraits/east-scientist/qin.svg',
    matchBlurb: '汝与 {{name}} 同，能以算筹穷天地之数。',
    anecdotes: [
      { title: '大衍求一术', body: '中国剩余定理。' },
      { title: '数书九章', body: '18 卷 81 题，含高次方程数值解。' },
    ],
    echoes: ['esci-zu', 'esci-shen', 'esci-guo'],
  },
  {
    id: 'esci-luban',
    name: '鲁班',
    era: '春秋',
    domain: 'east-scientist',
    vector: [0.6, 0.5, 0.8, 0.8, 0.5, 0.5, 0.85, 0.9, 0.55, 0.7, 0.65, 0.4],
    signature: '工欲善其事，必先利其器。',
    bio: '姓公输，名般，鲁国人。春秋时期鲁国人，土木工匠祖师。传说发明锯、刨、曲尺、墨斗等。',
    portrait: 'portraits/east-scientist/luban.svg',
    matchBlurb: '汝与 {{name}} 同，能以巧手夺天工。',
    anecdotes: [
      { title: '班母与班妻', body: '传说锯的灵感来自茅草割手。' },
      { title: '攻与守', body: '公输般为楚造云梯，墨子九拒之。' },
    ],
    echoes: ['esci-cailun', 'esci-huang', 'esci-ouye'],
  },

  // ── E 极端内 ──
  {
    id: 'esci-ouye',
    name: '欧冶子',
    era: '春秋',
    domain: 'east-scientist',
    vector: [0.4, 0.5, 0.6, 0.65, 0.4, 0.55, 0.7, 0.85, 0.85, 0.85, 0.55, 0.4],
    signature: '铸得三千剑，一为知己鸣。',
    bio: '春秋末年越国人。铸剑名家，为越王铸湛卢、巨阙、胜邪、鱼肠、纯钧五剑。',
    portrait: 'portraits/east-scientist/ouye.svg',
    matchBlurb: '汝与 {{name}} 同，能以一技之极致，传千载之器。',
    anecdotes: [
      { title: '湛卢', body: '铸于湛卢山，列「越五剑」之首。' },
      { title: '欧冶池', body: '福建古田、福州冶山皆有欧冶子遗迹。' },
    ],
    echoes: ['esci-ganjiang', 'esci-luban', 'esci-cailun'],
  },
  {
    id: 'esci-ganjiang',
    name: '干将',
    era: '春秋',
    domain: 'east-scientist',
    vector: [0.4, 0.5, 0.6, 0.6, 0.4, 0.6, 0.7, 0.85, 0.85, 0.85, 0.55, 0.45],
    signature: '身既死兮神以灵，魂魄毅兮为鬼雄。',
    bio: '吴人。铸剑名家，与妻莫邪同铸雌雄二剑。',
    portrait: 'portraits/east-scientist/ganjiang.svg',
    matchBlurb: '汝与 {{name}} 同，能以一生执一技，与之共生死。',
    anecdotes: [
      { title: '干将莫邪', body: '以身殉剑，传说为名铸剑师。' },
      { title: '剑成而人亡', body: '「以身为剑」千古传。' },
    ],
    echoes: ['esci-ouye', 'esci-luban', 'esci-ge'],
  },
  {
    id: 'esci-ma',
    name: '马钧',
    era: '魏',
    domain: 'east-scientist',
    vector: [0.7, 0.5, 0.65, 0.75, 0.4, 0.55, 0.7, 0.9, 0.5, 0.7, 0.6, 0.45],
    signature: '天下之名巧也。',
    bio: '字德衡，三国魏扶风人。机械工程师。改进绫机、造指南车、造「水转百戏」、改进连弩。',
    portrait: 'portraits/east-scientist/ma.svg',
    matchBlurb: '汝与 {{name}} 同，能于机巧之中见大用。',
    anecdotes: [
      { title: '指南车', body: '利用差速齿轮，指南不偏。' },
      { title: '水转百戏', body: '以水力驱动的木偶戏。' },
    ],
    echoes: ['esci-su', 'esci-luban', 'esci-ouye'],
  },
  {
    id: 'esci-zhu',
    name: '竺可桢',
    era: '清',
    domain: 'east-scientist',
    vector: [0.85, 0.5, 0.55, 0.6, 0.5, 0.5, 0.8, 0.98, 0.6, 0.8, 0.55, 0.6],
    signature: '求是。',
    bio: '字藕舫，浙江绍兴人。近代地理学家、气象学家、教育家。中国近代地理学奠基人。',
    portrait: 'portraits/east-scientist/zhu.svg',
    matchBlurb: '汝与 {{name}} 同，能于风霜雨雪中见天道。',
    anecdotes: [
      { title: '日记', body: '记 38 年逐日天气，积 800 万字。' },
      { title: '求是', body: '执掌浙大 13 年，以「求是」为校训。' },
    ],
    echoes: ['esci-shen', 'esci-guo', 'esci-xu'],
  },
  {
    id: 'esci-mao',
    name: '茅以升',
    era: '清',
    domain: 'east-scientist',
    vector: [0.8, 0.55, 0.65, 0.7, 0.55, 0.5, 0.85, 0.98, 0.5, 0.7, 0.7, 0.55],
    signature: '桥梁工程是造福人民的事业。',
    bio: '字唐臣，江苏镇江人。近代桥梁工程学家、教育家。主持设计建造中国第一座现代化大桥钱塘江桥。',
    portrait: 'portraits/east-scientist/mao.svg',
    matchBlurb: '汝与 {{name}} 同，能以工程之笔写家国之桥。',
    anecdotes: [
      { title: '钱塘江桥', body: '1937 年建成，是中国人自己设计的首座现代化大桥。' },
      {
        title: '炸桥保国',
        body: '为阻日军，亲自指挥炸桥，留下「斗地风云突变色，炸桥挥泪断通途」。',
      },
    ],
    echoes: ['esci-zhan', 'esci-shen', 'esci-xu'],
  },
  {
    id: 'esci-zhan',
    name: '詹天佑',
    era: '清',
    domain: 'east-scientist',
    vector: [0.8, 0.55, 0.7, 0.75, 0.5, 0.5, 0.85, 0.95, 0.5, 0.7, 0.75, 0.55],
    signature: '各出所学，各尽所知，使国家富强不受外侮。',
    bio: '字眷诚，号达潮，江西婺源人。近代铁路工程学家。主持修建京张铁路，八达岭青龙桥「人」字形折返线。',
    portrait: 'portraits/east-scientist/zhan.svg',
    matchBlurb: '汝与 {{name}} 同，能以寸寸铁轨筑家国之脊。',
    anecdotes: [
      { title: '京张铁路', body: '中国人自主设计建造的第一条干线铁路。' },
      { title: '人字形线路', body: '巧妙解决八达岭坡度问题。' },
    ],
    echoes: ['esci-mao', 'esci-shen', 'esci-xu'],
  },
];
